// 炼丹系统 - 配方+丹药+毒性+解毒
// 从 v0.35 迁移 - 共 8 个常量

export const ALCHEMY_RECIPES: any = [
{id:'linggengdan',name:'灵根丹',icon:'💊',grade:'天级',herbsNeeded:0,furnaceLv:0,desc:'蜕凡境以上方可服用，随机觉醒灵根',effect:{type:'awaken_root',value:0},realmReq:0},
{id:'tizhidan',name:'体质丹',icon:'💊',grade:'天级',herbsNeeded:0,furnaceLv:0,desc:'随机重置体质',effect:{type:'reroll_constitution',value:0},realmReq:0},
{id:'hp_pill',name:'回血丹',icon:'💊',grade:'凡级',herbsNeeded:3,furnaceLv:1,desc:'恢复50%气血',effect:{type:'heal',value:.5},realmReq:0},
{id:'mp_pill',name:'回灵丹',icon:'💧',grade:'凡级',herbsNeeded:3,furnaceLv:1,desc:'恢复50%灵力',effect:{type:'mp_heal',value:.5},realmReq:0},
{id:'exp_pill',name:'聚灵丹',icon:'✨',grade:'黄级',herbsNeeded:5,furnaceLv:2,desc:'获得10分钟修为',effect:{type:'exp',value:600},realmReq:3},
{id:'atk_pill',name:'破甲丹',icon:'⚔️',grade:'黄级',herbsNeeded:6,furnaceLv:2,desc:'永久+5攻击',effect:{type:'perm_atk',value:5},realmReq:5},
{id:'def_pill',name:'铁骨丹',icon:'🛡️',grade:'黄级',herbsNeeded:6,furnaceLv:2,desc:'永久+5防御',effect:{type:'perm_def',value:5},realmReq:5},
{id:'break_pill',name:'破境丹',icon:'💥',grade:'玄级',herbsNeeded:10,furnaceLv:3,desc:'突破成功率+10%',effect:{type:'break_bonus',value:10},realmReq:10},
{id:'qi_pill',name:'大还丹',icon:'🌟',grade:'玄级',herbsNeeded:15,furnaceLv:4,desc:'获得60分钟修为',effect:{type:'exp',value:3600},realmReq:15},
{id:'reborn_pill',name:'转生丹',icon:'🔄',grade:'地级',herbsNeeded:25,furnaceLv:5,desc:'转世保留额外10%修为',effect:{type:'rebirth_bonus',value:10},realmReq:20},
{id:'soul_pill',name:'凝魄丹',icon:'🔮',grade:'地级',herbsNeeded:20,furnaceLv:5,desc:'突破中高境界瓶颈所需',effect:{type:'bottle_item',value:1},realmReq:22},
{id:'heaven_pill',name:'天元丹',icon:'✨',grade:'仙级',herbsNeeded:40,furnaceLv:7,desc:'突破超高境界瓶颈所需',effect:{type:'bottle_item',value:1},realmReq:36},
{id:'immortal_pill',name:'仙丹',icon:'💎',grade:'仙级',herbsNeeded:50,furnaceLv:7,desc:'永久+100全属性',effect:{type:'perm_all',value:100},realmReq:34},

{id:'bijie_pill_low',name:'下等避劫丹',icon:'⚡',grade:'玄级',herbsNeeded:15,furnaceLv:4,desc:'渡劫时减少雷劫伤害15%',effect:{type:'trib_reduce',value:15},realmReq:25,isTribPill:true},
{id:'bijie_pill_mid',name:'中等避劫丹',icon:'🌩️',grade:'地级',herbsNeeded:30,furnaceLv:6,desc:'渡劫时减少雷劫伤害35%',effect:{type:'trib_reduce',value:35},realmReq:30,isTribPill:true},
{id:'bijie_pill_high',name:'高等避劫丹',icon:'⛈️',grade:'天级',herbsNeeded:50,furnaceLv:8,desc:'渡劫时减少雷劫伤害65%',effect:{type:'trib_reduce',value:65},realmReq:35,isTribPill:true},{id:'cuitidan_1',name:'淬体丹·外劲',icon:'💪',grade:'凡级',herbsNeeded:2,furnaceLv:1,desc:'淬炼筋骨，突破外劲所需',effect:{type:'mortal_break',value:0},realmReq:0,isMortalPill:true},
{id:'cuitidan_2',name:'淬体丹·暗劲',icon:'💪',grade:'凡级',herbsNeeded:3,furnaceLv:1,desc:'淬炼内力，突破暗劲所需',effect:{type:'mortal_break',value:1},realmReq:0,isMortalPill:true},
{id:'cuitidan_3',name:'淬体丹·化劲',icon:'💪',grade:'凡级',herbsNeeded:5,furnaceLv:2,desc:'化劲通神，突破化劲所需',effect:{type:'mortal_break',value:2},realmReq:0,isMortalPill:true},
{id:'cuitidan_4',name:'淬体丹·宗师',icon:'💪',grade:'黄级',herbsNeeded:8,furnaceLv:2,desc:'一代宗师，突破宗师所需',effect:{type:'mortal_break',value:3},realmReq:0,isMortalPill:true},
{id:'cuitidan_5',name:'淬体丹·大宗师',icon:'💪',grade:'黄级',herbsNeeded:12,furnaceLv:3,desc:'武道巅峰，突破大宗师所需',effect:{type:'mortal_break',value:4},realmReq:0,isMortalPill:true},
{id:'cuitidan_6',name:'淬体丹·蜕凡',icon:'💪',grade:'玄级',herbsNeeded:18,furnaceLv:3,desc:'脱胎换骨，突破蜕凡所需',effect:{type:'mortal_break',value:5},realmReq:0,isMortalPill:true},
{id:'cuitidan_7',name:'淬体丹·先天',icon:'💪',grade:'玄级',herbsNeeded:25,furnaceLv:4,desc:'先天之境，凝聚灵气气旋所需',effect:{type:'mortal_break',value:6},realmReq:0,isMortalPill:true},

];

export const MEDICAL_PILLS: any = [

  {id:'med_regen_flesh',name:'生肌造化丹',icon:'🩹',grade:'凡级',herbsNeeded:4,furnaceLv:1,
  desc:'促进肌肉皮肤再生，对应现代外科清创缝合',effect:{type:'heal_part',targets:['skin','muscles'],value:0.5},
  medical:'对应医学：清创缝合术。外伤后清除坏死组织，缝合促进愈合。术后需保持伤口清洁干燥。',
  cureDesc:'治愈皮肤灼伤、冻伤、皮肤溃烂、肌肉拉伤',curesDebuffs:['skin_burn','frostbite','skin_rot','muscle_strain'],realmReq:2},
  {id:'med_blood_regen',name:'九转还血丹',icon:'🩸',grade:'凡级',herbsNeeded:5,furnaceLv:1,
  desc:'促进造血恢复血容量，对应现代输血补液',effect:{type:'heal_part',targets:['torso','heart','boneMarrow'],value:0.4},
  medical:'对应医学：输血和液体复苏。失血性休克时快速补充血容量，维持循环稳定。骨髓为造血器官，需同时恢复。',
  cureDesc:'治愈失血过多、元气大伤',curesDebuffs:['excessive_bleeding','vitality_loss'],realmReq:3},

  {id:'med_bone_set',name:'接骨续筋丹',icon:'🦴',grade:'黄级',herbsNeeded:6,furnaceLv:2,
  desc:'促进骨骼愈合，对应现代骨折复位固定术',effect:{type:'heal_part',targets:['bones','leftArm','rightArm','leftLeg','rightLeg'],value:0.4},
  medical:'对应医学：骨折复位+外固定/内固定术。将骨折端正确对位后用石膏或钢板固定，6-8周骨痂形成。粉碎性骨折需手术内固定。',
  cureDesc:'治愈骨裂、骨折、粉碎性骨折',curesDebuffs:['bone_crack','bone_fracture','bone_shatter'],realmReq:5},
  {id:'med_bone_nourish',name:'壮骨培元丹',icon:'💪',grade:'黄级',herbsNeeded:8,furnaceLv:2,
  desc:'强化骨骼密度，对应现代补钙+维生素D治疗',effect:{type:'heal_part',targets:['bones','boneMarrow'],value:0.6},
  medical:'对应医学：骨质疏松治疗。补充钙质和维生素D，促进骨密度恢复。严重者需双膦酸盐类药物。',
  cureDesc:'治愈骨质疏松、骨髓炎',curesDebuffs:['osteoporosis','osteomyelitis','marrow_infection'],realmReq:6},

  {id:'med_heart_restore',name:'养心凝神丹',icon:'❤️',grade:'黄级',herbsNeeded:10,furnaceLv:3,
  desc:'修复心脉损伤，对应现代心脏介入治疗',effect:{type:'heal_part',targets:['heart'],value:0.5},
  medical:'对应医学：心脏介入手术。冠脉造影+支架植入治疗冠心病；心包穿刺引流治疗心包填塞。术后需抗凝治疗。',
  cureDesc:'治愈心悸、心脉受损、血气逆行',curesDebuffs:['palpitation','heart_damaged','qi_reversal'],realmReq:8},
  {id:'med_liver_cleanse',name:'疏肝解毒丹',icon:'🫁',grade:'黄级',herbsNeeded:8,furnaceLv:2,
  desc:'疏肝理气、清热解毒，对应现代保肝+解毒治疗',effect:{type:'heal_part',targets:['liver'],value:0.5},
  medical:'对应医学：肝功能保护+毒物清除。使用保肝药物（如还原型谷胱甘肽），中毒时洗胃+血液净化。',
  cureDesc:'治愈肝气郁结、肝功能衰竭、中毒、剧毒入体',curesDebuffs:['liver_stagnation','liver_failure','poisoned','severe_poison'],realmReq:7},
  {id:'med_spleen_fortify',name:'健脾培土丹',icon:'🟤',grade:'黄级',herbsNeeded:6,furnaceLv:2,
  desc:'健脾益气、温阳散寒，对应现代消化功能调节',effect:{type:'heal_part',targets:['spleen','stomach'],value:0.5},
  medical:'对应医学：消化功能恢复。补充消化酶，调节肠道菌群。脾虚对应免疫力低下，需营养支持。',
  cureDesc:'治愈脾虚、脾阳虚、胃痉挛',curesDebuffs:['spleen_deficiency','spleen_yang_deficiency','stomach_spasm'],realmReq:6},
  {id:'med_lung_clear',name:'清肺化瘀丹',icon:'🫁',grade:'黄级',herbsNeeded:8,furnaceLv:2,
  desc:'清肺化痰、活血化瘀，对应现代呼吸系统治疗',effect:{type:'heal_part',targets:['lung'],value:0.5},
  medical:'对应医学：肺炎/气胸治疗。抗生素+氧疗治疗肺炎；胸腔闭式引流治疗气胸。严重者需机械通气。',
  cureDesc:'治愈肺气虚、肺炎',curesDebuffs:['lung_qi_deficiency','pneumonia'],realmReq:7},
  {id:'med_kidney_nourish',name:'补肾固精丹',icon:'🫘',grade:'玄级',herbsNeeded:10,furnaceLv:3,
  desc:'补肾益精、温阳化气，对应现代肾脏保护',effect:{type:'heal_part',targets:['kidney'],value:0.5},
  medical:'对应医学：肾功能保护。控制血压血糖，避免肾毒性药物。肾阳虚对应肾上腺功能减退，需激素替代。',
  cureDesc:'治愈肾精亏虚、肾阳虚',curesDebuffs:['kidney_deficiency','kidney_yang_deficiency'],realmReq:9},

  {id:'med_meridian_open',name:'通脉破障丹',icon:'🌀',grade:'玄级',herbsNeeded:8,furnaceLv:3,
  desc:'疏通经脉、活络止痛，对应现代神经修复治疗',effect:{type:'heal_part',targets:['meridians'],value:0.5},
  medical:'对应医学：神经损伤修复。神经减压术+神经营养药物（甲钴胺等）。严重者需神经移植。',
  cureDesc:'治愈经脉阻塞、灵气反噬、封脉',curesDebuffs:['meridian_block','qi_backlash','meridian_seal'],realmReq:8},
  {id:'med_meridian_repair',name:'续脉归元丹',icon:'🔮',grade:'玄级',herbsNeeded:12,furnaceLv:4,
  desc:'修复断裂经脉，对应现代神经显微外科手术',effect:{type:'heal_part',targets:['meridians','brain'],value:0.6},
  medical:'对应医学：显微神经外科。在显微镜下吻合断裂的神经纤维，术后需长期康复训练。',
  cureDesc:'治愈经脉断裂、经脉逆行、走火入魔、道基受损',curesDebuffs:['meridian_break','meridian_reverse','qi_deviation','dao_foundation_damage'],realmReq:12},

  {id:'med_brain_awaken',name:'醒脑开窍丹',icon:'🧠',grade:'玄级',herbsNeeded:10,furnaceLv:3,
  desc:'醒脑开窍、镇惊安神，对应现代脑外伤治疗',effect:{type:'heal_part',targets:['head','brain'],value:0.4},
  medical:'对应医学：脑外伤治疗。控制颅内压（甘露醇脱水），必要时去骨瓣减压术。脑震荡需安静休息。',
  cureDesc:'治愈脑震荡、脑损伤、脑水肿',curesDebuffs:['concussion','brain_damage','brain_edema'],realmReq:10},
  {id:'med_spirit_calm',name:'安神定魄丹',icon:'🌟',grade:'玄级',herbsNeeded:8,furnaceLv:3,
  desc:'安神定魄、宁心除烦，对应现代精神心理治疗',effect:{type:'heal_part',targets:['brain','heart'],value:0.4},
  medical:'对应医学：精神科治疗。抗焦虑/抗抑郁药物+心理疏导。严重者需住院治疗。',
  cureDesc:'治愈神经衰弱、识海动荡、心魔侵扰',curesDebuffs:['neurasthenia','sea_turbulence','heart_demon'],realmReq:10},
  {id:'med_memory_recall',name:'回魂忆梦丹',icon:'💭',grade:'地级',herbsNeeded:15,furnaceLv:5,
  desc:'恢复受损记忆，对应现代认知康复训练',effect:{type:'heal_part',targets:['brain'],value:0.7},
  medical:'对应医学：认知康复治疗。通过反复训练重建神经通路。脑损伤后记忆恢复需要长期康复。',
  cureDesc:'治愈记忆丧失',curesDebuffs:['memory_loss'],realmReq:15},

  {id:'med_emergency',name:'回天续命丹',icon:'💖',grade:'玄级',herbsNeeded:15,furnaceLv:4,
  desc:'急救丹药，快速止血续命，对应现代急救术',effect:{type:'heal_part',targets:['head','torso','leftArm','rightArm','leftLeg','rightLeg'],value:0.3},
  medical:'对应医学：创伤急救ABCDE法。A气道B呼吸C循环D神经E暴露。止血带+压迫止血+建立静脉通路。',
  cureDesc:'治愈各种急性外伤（止血急救）',curesDebuffs:['excessive_bleeding','internal_injury','shock_injury'],realmReq:8},
  {id:'med_full_restore',name:'太乙还生丹',icon:'✨',grade:'地级',herbsNeeded:25,furnaceLv:5,
  desc:'全面修复身体所有损伤，对应现代综合ICU治疗',effect:{type:'heal_all',value:0.3},
  medical:'对应医学：ICU综合治疗。多学科联合诊疗（MDT），器官功能支持（呼吸机、CRRT、ECMO等）。',
  cureDesc:'治愈所有类型伤病（全面修复）',curesDebuffs:'all',realmReq:18},
  {id:'med_dao_heal',name:'天道造化丹',icon:'☯️',grade:'仙级',herbsNeeded:50,furnaceLv:7,
  desc:'天道之力重塑道基，对应现代再生医学',effect:{type:'heal_all',value:1.0},
  medical:'对应医学：再生医学前沿。干细胞治疗+组织工程修复受损器官。目前仅处于临床试验阶段。',
  cureDesc:'完全治愈一切伤病（含道伤、碎丹等）',curesDebuffs:'all',realmReq:25},

  {id:'med_gallbladder_clear',name:'化石利胆丹',icon:'💚',grade:'黄级',herbsNeeded:5,furnaceLv:2,
  desc:'化石利胆，对应现代胆结石碎石术',effect:{type:'heal_part',targets:['gallbladder'],value:0.5},
  medical:'对应医学：胆结石治疗。体外冲击波碎石或腹腔镜胆囊切除术。小结石可用熊去氧胆酸溶石。',
  cureDesc:'治愈胆结石',curesDebuffs:['gallstone'],realmReq:6},
  {id:'med_intestine_clear',name:'通肠化滞丹',icon:'🟢',grade:'黄级',herbsNeeded:5,furnaceLv:2,
  desc:'通肠化滞、润肠通便，对应现代胃肠减压',effect:{type:'heal_part',targets:['smallIntestine','largeIntestine','stomach'],value:0.4},
  medical:'对应医学：肠梗阻治疗。胃肠减压+灌肠通便。完全性梗阻需手术治疗。',
  cureDesc:'治愈小肠梗阻、大肠燥结',curesDebuffs:['intestinal_block','constipation'],realmReq:5},
  {id:'med_bladder_clear',name:'清热利湿丹',icon:'🟡',grade:'黄级',herbsNeeded:5,furnaceLv:2,
  desc:'清热利湿，对应现代泌尿系统抗感染',effect:{type:'heal_part',targets:['bladder'],value:0.5},
  medical:'对应医学：泌尿系统感染治疗。抗生素+多饮水。膀胱炎一般口服喹诺酮类即可。',
  cureDesc:'治愈膀胱湿热',curesDebuffs:['bladder_heat'],realmReq:5},
  {id:'med_sanjiao_open',name:'理气通络丹',icon:'🟣',grade:'黄级',herbsNeeded:6,furnaceLv:2,
  desc:'理气通络，对应现代自主神经调节',effect:{type:'heal_part',targets:['sanjiao'],value:0.5},
  medical:'对应医学：自主神经功能紊乱治疗。调节生活方式+谷维素等神经调节药物。',
  cureDesc:'治愈三焦不通',curesDebuffs:['sanjiao_block'],realmReq:5},
  {id:'med_marrow_restore',name:'补髓生血丹',icon:'🔴',grade:'玄级',herbsNeeded:12,furnaceLv:4,
  desc:'补髓生血，对应现代骨髓移植',effect:{type:'heal_part',targets:['boneMarrow'],value:0.6},
  medical:'对应医学：骨髓移植/造血干细胞移植。用于治疗血液系统疾病。需HLA配型，移植后需抗排异。',
  cureDesc:'治愈骨髓炎、髓海空虚',curesDebuffs:['osteomyelitis','marrow_infection','marrow_depletion'],realmReq:12},

  {id:'med_dan_restore',name:'凝丹归元丹',icon:'💫',grade:'地级',herbsNeeded:20,furnaceLv:5,
  desc:'凝聚破碎金丹，对应现代器官修复（修仙化）',effect:{type:'heal_part',targets:['torso'],value:0.8},
  medical:'对应修仙医学：金丹乃修士根基，碎丹后需以天材地宝重塑丹基。类似器官再生。',
  cureDesc:'治愈碎丹',curesDebuffs:['golden_core_shatter'],realmReq:20},
  {id:'med_dao_heal_single',name:'渡劫化道丹',icon:'⚡',grade:'地级',herbsNeeded:18,furnaceLv:5,
  desc:'化解天劫道伤，需以雷劫之力淬体',effect:{type:'heal_part',targets:['brain','meridians'],value:0.6},
  medical:'对应修仙医学：天劫道伤乃大道之伤，非普通丹药可愈。需悟道+丹药双管齐下。',
  cureDesc:'治愈道伤',curesDebuffs:['dao_injury'],realmReq:22},
  {id:'med_lifespan_extend',name:'延寿续命丹',icon:'⏳',grade:'仙级',herbsNeeded:30,furnaceLv:6,
  desc:'增加寿元，对应现代抗衰老研究',effect:{type:'heal_part',targets:['brain'],value:0.5},
  medical:'对应修仙医学：延寿丹以万年灵药炼制，可延寿数十年。现实抗衰老研究（端粒酶、NAD+等）。',
  cureDesc:'治愈寿元损耗',curesDebuffs:['lifespan_drain'],realmReq:28},
  {id:'med_limb_regrow',name:'断肢重生丹',icon:'🦾',grade:'地级',herbsNeeded:15,furnaceLv:5,
  desc:'促进断肢再生，对应现代假肢+再生医学',effect:{type:'heal_part',targets:['leftArm','rightArm','leftLeg','rightLeg'],value:0.8},
  medical:'对应修仙医学：断肢再生需磅礴生命力。现实中截肢后需安装假肢；蝾螈等生物具有断肢再生能力。',
  cureDesc:'治愈断肢',curesDebuffs:['limb_sever'],realmReq:18},

  {id:'med_force_heal',name:'化瘀活血丹',icon:'👊',grade:'凡级',herbsNeeded:3,furnaceLv:1,
  desc:'化解力道内伤，促进血液循环',effect:{type:'heal_part',targets:['torso','muscles','bones'],value:0.4},
  medical:'力道伤主要为挫伤，深层组织出血。需活血化瘀，促进淤血吸收。',
  cureDesc:'治愈力道内伤、深层挫伤',curesDebuffs:['force_trauma'],realmReq:2},
  {id:'med_tear_heal',name:'止血生肌丹',icon:'🩸',grade:'黄级',herbsNeeded:5,furnaceLv:2,
  desc:'止血并促进伤口愈合',effect:{type:'heal_part',targets:['skin','muscles','torso'],value:0.5},
  medical:'撕裂伤为开放性创伤，需止血+清创+缝合。失血过多需输血补液。',
  cureDesc:'治愈撕裂伤口、止血',curesDebuffs:['tear_wound'],realmReq:3},
  {id:'med_pierce_heal',name:'续脏护腑丹',icon:'🗡️',grade:'玄级',herbsNeeded:8,furnaceLv:3,
  desc:'修复穿刺导致的内脏损伤',effect:{type:'heal_part',targets:['heart','liver','lung','stomach','torso'],value:0.4},
  medical:'穿刺伤深入体腔，可致脏器破裂、大出血。需紧急手术探查止血。',
  cureDesc:'治愈内脏穿刺伤',curesDebuffs:['pierce_wound'],realmReq:6},
  {id:'med_element_heal',name:'清心净体丹',icon:'🔥',grade:'黄级',herbsNeeded:6,furnaceLv:2,
  desc:'清除体内残余元素之力',effect:{type:'heal_part',targets:['meridians','skin','muscles'],value:0.5},
  medical:'元素灼伤不同于普通烧伤，残留元素之力会持续侵蚀经脉。',
  cureDesc:'治愈元素灼伤、清除残余元素',curesDebuffs:['elemental_burn'],realmReq:4},
  {id:'med_origin_heal',name:'造化生机丹',icon:'💫',grade:'地级',herbsNeeded:20,furnaceLv:5,
  desc:'修复部分本源损伤（缓解不可逆损伤的症状）',effect:{type:'heal_part',targets:['dantian','foundation','spiritualRoot'],value:0.15},
  medical:'本源损伤极难治愈，但可通过造化之力缓解症状。完全修复需成仙凝聚仙体。',
  cureDesc:'缓解本源损伤症状（不可完全治愈，成仙前）',curesDebuffs:['origin_damage'],realmReq:20},
  {id:'med_dantian_seal',name:'封丹固元丹',icon:'🌀',grade:'玄级',herbsNeeded:10,furnaceLv:4,
  desc:'封堵丹田裂纹，减少灵力外泄（不能完全修复）',effect:{type:'heal_part',targets:['dantian'],value:0.1},
  medical:'丹田裂纹无法真正修复，但可暂时封堵减少灵力损耗。',
  cureDesc:'封堵丹田裂纹，减少灵力外泄（不可逆损伤的缓解措施）',curesDebuffs:['dantian_crack'],realmReq:15},
  {id:'med_foundation_stabilize',name:'固基培元丹',icon:'🏗️',grade:'地级',herbsNeeded:15,furnaceLv:5,
  desc:'稳固根基裂缝，小幅恢复突破概率',effect:{type:'heal_part',targets:['foundation'],value:0.1},
  medical:'根基裂缝无法自然修复，但可通过大量天材地宝暂时稳固。',
  cureDesc:'稳固根基裂缝（不可逆损伤的缓解措施）',curesDebuffs:['foundation_crack'],realmReq:18},
  {id:'med_spirit_root_nurture',name:'蕴灵培根丹',icon:'🌿',grade:'地级',herbsNeeded:18,furnaceLv:5,
  desc:'滋养受损灵根，减缓灵根枯萎',effect:{type:'heal_part',targets:['spiritualRoot'],value:0.1},
  medical:'灵根断裂无法自然修复，但可通过灵蕴之物滋养减缓衰退。',
  cureDesc:'滋养受损灵根（不可逆损伤的缓解措施）',curesDebuffs:['spiritual_root_fracture'],realmReq:20},
];

export const PILL_TOXICITY: any = {

  hp_pill: { toxicity: 4, name: '回血丹', grade: '凡级', desc: '普通疗伤丹，毒性较低' },
  mp_pill: { toxicity: 4, name: '回灵丹', grade: '凡级', desc: '普通回灵丹，毒性较低' },
  exp_pill: { toxicity: 7, name: '聚气丹', grade: '黄级', desc: '聚气修炼丹，含有一定药毒' },
  break_pill: { toxicity: 12, name: '破境丹', grade: '玄级', desc: '强行破境之丹，药性猛烈，毒性较强' },
  bijie_pill_low: { toxicity: 15, name: '下等避劫丹', grade: '玄级', desc: '避劫丹药性极猛，毒性颇高' },
  bijie_pill_mid: { toxicity: 20, name: '中等避劫丹', grade: '地级', desc: '中等避劫丹蕴含大量药毒' },
  bijie_pill_high: { toxicity: 25, name: '高等避劫丹', grade: '天级', desc: '高等避劫丹药毒极重，非体质强横者不可多服' },
  rebirth_pill: { toxicity: 10, name: '转世丹', grade: '地级', desc: '转世丹记录修为，药毒中等' },
  immortal_pill: { toxicity: 30, name: '仙丹', grade: '仙级', desc: '仙丹蕴含仙力，凡体承受不住其药毒' },
  qi_pill: { toxicity: 10, name: '大还丹', grade: '玄级', desc: '大还丹蕴含浓郁灵气，药毒中等偏高' },
  atk_pill: { toxicity: 8, name: '破甲丹', grade: '黄级', desc: '破甲丹激发肉身潜力，含有一定药毒' },
  def_pill: { toxicity: 8, name: '铁骨丹', grade: '黄级', desc: '铁骨丹强化骨骼，含有一定药毒' },
  reborn_pill: { toxicity: 15, name: '转生丹', grade: '地级', desc: '转生丹牵动轮回之力，药毒颇重' },
  soul_pill: { toxicity: 12, name: '凝魄丹', grade: '地级', desc: '凝魄丹温养神魂，药毒中等' },
};

export const TOXICITY_EFFECTS: any = [
  { threshold: 0,  name: '无丹毒',     icon: '✅', desc: '体内无丹毒残留', penalties: {}, dmgPerTick: 0, healReduction: 0 },
  { threshold: 10, name: '轻微药毒',   icon: '🟢', desc: '丹药残留轻微毒素，影响不大', penalties: { pillEfficiency: -5 }, dmgPerTick: 0, healReduction: 0.05 },
  { threshold: 25, name: '丹毒淤积',   icon: '🟡', desc: '体内药毒淤积，经脉运转不畅，修炼速度下降', penalties: { pillEfficiency: -15, expRate: -8, mpRegen: -10 }, dmgPerTick: 0.15, healReduction: 0.12 },
  { threshold: 40, name: '药毒入体',   icon: '🟠', desc: '药毒侵入经脉，气血修炼皆受阻', penalties: { pillEfficiency: -30, expRate: -15, atk: -10, def: -10, hpRegen: -20 }, dmgPerTick: 0.4, healReduction: 0.25 },
  { threshold: 55, name: '丹毒攻心',   icon: '🔴', desc: '药毒攻心，气血运行严重受阻', penalties: { pillEfficiency: -50, expRate: -25, atk: -20, def: -20, critRate: -15, maxHp: -10 }, dmgPerTick: 1.0, healReduction: 0.4 },
  { threshold: 70, name: '毒入骨髓',   icon: '🟣', desc: '药毒深入骨髓，根基受损，服用丹药可能反噬', penalties: { pillEfficiency: -70, expRate: -40, atk: -35, def: -35, maxHp: -20, maxMp: -15 }, dmgPerTick: 2.0, healReduction: 0.6, pillBacklash: 0.2 },
  { threshold: 85, name: '药毒噬体',   icon: '⚫', desc: '药毒反噬肉身，生机断绝，随时可能暴毙', penalties: { pillEfficiency: -90, expRate: -60, atk: -50, def: -50, maxHp: -40, maxMp: -30 }, dmgPerTick: 4.0, healReduction: 0.8, pillBacklash: 0.4 },
  { threshold: 95, name: '丹毒绝命',   icon: '💀', desc: '药毒已达极致，命悬一线！再服丹药必死无疑！', penalties: { pillEfficiency: -100, expRate: -80, atk: -70, def: -70, maxHp: -60, maxMp: -50 }, dmgPerTick: 8.0, healReduction: 1.0, pillBacklash: 0.7 },
];

export const TOXICITY_NATURAL_DECAY: any = 0.02; // 每秒自然减少0.02点;

export const DETOX_METHODS: any = [
  { id: 'detox_herb', name: '清心草', icon: '🌿', desc: '以清心草熬制汤药，温和解毒', cost: { herbs: 20 }, reduceRange: [5, 15], minToxicity: 0 },
  { id: 'detox_pill', name: '解毒丹', icon: '💊', desc: '特制解毒丹，效果显著', cost: { gold: 500, herbs: 50 }, reduceRange: [15, 30], minToxicity: 0, requiresAlchemy: 3 },
  { id: 'detox_med', name: '百草灵液', icon: '🧪', desc: '百草精华提炼，强力解毒', cost: { gold: 2000, herbs: 150 }, reduceRange: [30, 50], minToxicity: 0, requiresAlchemy: 5 },
  { id: 'detox_qi', name: '灵气洗髓', icon: '🌀', desc: '消耗50%灵力洗髓伐毛，以纯正灵气冲刷药毒', cost: { mp: 0.5 }, reduceRange: [20, 40], minToxicity: 0, isQiMethod: true },
  { id: 'detox_sweat', name: '闭关排毒', icon: '🧘', desc: '闭关修炼以汗液排出毒素，需消耗时间', cost: { time: 300 }, reduceRange: [8, 20], minToxicity: 0, isTimeMethod: true },
];

export const ANIMAL_BODY_PART_MEDICAL: any = {

  mammal_quad: {
  typeName: '哺乳动物(四足)', example: '虎/狼/熊/牛',
  parts: {
  head:     { lethality: 0.90, vitalOrgan: true, desc: '大脑为中枢，颅骨较厚但中枢同样脆弱', criticalZones: ['脑干', '大脑'], mortalityNote: '哺乳动物脑干损伤致死率接近100%' },
  torso:    { lethality: 0.85, vitalOrgan: true, desc: '胸腔含心肺，腹腔含肝脾胃肠', criticalZones: ['心脏', '主动脉', '肺'], mortalityNote: '心脏破裂或主动脉断裂可在数分钟内致死' },
  heart:    { lethality: 0.98, vitalOrgan: true, desc: '哺乳动物心脏为循环动力源', criticalZones: ['心室', '冠状动脉'], mortalityNote: '心脏穿透伤致死率>90%' },
  lung:     { lethality: 0.80, vitalOrgan: true, desc: '双肺负责气体交换', criticalZones: ['肺门'], mortalityNote: '双肺损毁致窒息死亡' },
  liver:    { lethality: 0.70, vitalOrgan: true, desc: '哺乳动物肝脏血供丰富', criticalZones: ['肝门'], mortalityNote: '大出血致死' },
  kidney:   { lethality: 0.30, vitalOrgan: false, desc: '有两颗肾可代偿', criticalZones: ['肾蒂'], mortalityNote: '单侧损毁不致命' },
  leftArm:  { lethality: 0.15, vitalOrgan: false, desc: '前肢', criticalZones: [], mortalityNote: '不致命但影响行动' },
  rightArm: { lethality: 0.15, vitalOrgan: false, desc: '前肢', criticalZones: [], mortalityNote: '不致命但影响行动' },
  leftLeg:  { lethality: 0.25, vitalOrgan: false, desc: '后肢，股动脉', criticalZones: ['股动脉'], mortalityNote: '股动脉断裂可致大量失血' },
  rightLeg: { lethality: 0.25, vitalOrgan: false, desc: '后肢', criticalZones: ['股动脉'], mortalityNote: '同左后肢' },
  },
  },

  mammal_biped: {
  typeName: '哺乳动物(双足)', example: '猿猴/人形妖兽',
  parts: {
  head:     { lethality: 0.95, vitalOrgan: true, desc: '灵长类脑容量大，颅脑损伤致命', criticalZones: ['脑干', '大脑皮层'], mortalityNote: '脑干损伤致死率接近100%' },
  torso:    { lethality: 0.85, vitalOrgan: true, desc: '与人类相似的胸腹腔结构', criticalZones: ['心脏', '主动脉', '肝脏'], mortalityNote: '主动脉破裂2分钟内致死' },
  leftArm:  { lethality: 0.15, vitalOrgan: false, desc: '上肢', criticalZones: ['肱动脉'], mortalityNote: '极少致命' },
  rightArm: { lethality: 0.15, vitalOrgan: false, desc: '上肢', criticalZones: ['肱动脉'], mortalityNote: '极少致命' },
  leftLeg:  { lethality: 0.25, vitalOrgan: false, desc: '下肢', criticalZones: ['股动脉'], mortalityNote: '股动脉断裂致死率30-50%' },
  rightLeg: { lethality: 0.25, vitalOrgan: false, desc: '下肢', criticalZones: ['股动脉'], mortalityNote: '同左腿' },
  },
  },

  reptile: {
  typeName: '爬行动物', example: '蛇/蜥蜴/龟/鳄鱼',
  parts: {
  head:     { lethality: 0.85, vitalOrgan: true, desc: '爬行动物头部含脑和重要感官，但某些蛇砍头后仍可反射性咬人', criticalZones: ['脑干', '延髓'], mortalityNote: '脑干损伤致死，但反射弧可维持数分钟活动' },
  torso:    { lethality: 0.80, vitalOrgan: true, desc: '心脏和肺位于胸腔', criticalZones: ['心脏', '肺'], mortalityNote: '心脏停跳致死，但冷血动物代谢慢，死亡过程较哺乳动物长' },
  leftArm:  { lethality: 0.20, vitalOrgan: false, desc: '前肢/无（蛇类无四肢）', criticalZones: [], mortalityNote: '断肢不致命' },
  rightArm: { lethality: 0.20, vitalOrgan: false, desc: '前肢/无', criticalZones: [], mortalityNote: '断肢不致命' },
  leftLeg:  { lethality: 0.20, vitalOrgan: false, desc: '后肢/无', criticalZones: [], mortalityNote: '断肢不致命' },
  rightLeg: { lethality: 0.20, vitalOrgan: false, desc: '后肢/无', criticalZones: [], mortalityNote: '断肢不致命' },
  },
  specialNote: '蛇类砍头后身体仍可活动1-2小时（冷血代谢慢），龟类头部缩回时几乎无弱点',
  },

  avian: {
  typeName: '鸟类', example: '鹰/雷鹰/凤凰',
  parts: {
  head:     { lethality: 0.90, vitalOrgan: true, desc: '鸟类头部相对身体比例小但同样致命', criticalZones: ['脑干', '延髓'], mortalityNote: '脑干损伤致死率极高' },
  torso:    { lethality: 0.85, vitalOrgan: true, desc: '鸟类有气囊系统，肺损伤影响更大', criticalZones: ['心脏', '肺', '气囊'], mortalityNote: '鸟类气囊穿孔致呼吸效率剧降' },
  leftArm:  { lethality: 0.30, vitalOrgan: false, desc: '翅膀（鸟类飞行能力核心）', criticalZones: ['肱骨', '胸肌附着点'], mortalityNote: '单翼折断丧失飞行能力但不致命' },
  rightArm: { lethality: 0.30, vitalOrgan: false, desc: '翅膀', criticalZones: ['肱骨'], mortalityNote: '同左翼' },
  leftLeg:  { lethality: 0.20, vitalOrgan: false, desc: '腿部', criticalZones: ['股动脉'], mortalityNote: '腿部损伤影响站立/行走' },
  rightLeg: { lethality: 0.20, vitalOrgan: false, desc: '腿部', criticalZones: ['股动脉'], mortalityNote: '同左腿' },
  },
  specialNote: '鸟类有9个气囊系统，一处穿孔可影响全身气体交换。双翼全折断=丧失飞行能力',
  },

  arthropod: {
  typeName: '昆虫/节肢动物', example: '妖蜂/蜘蛛/蝎子',
  parts: {
  head:     { lethality: 0.70, vitalOrgan: true, desc: '昆虫头部含脑和主要感官，但分散式神经系统使其更耐损伤', criticalZones: ['脑', '触角'], mortalityNote: '部分昆虫（蟑螂）无头可存活数周' },
  torso:    { lethality: 0.80, vitalOrgan: true, desc: '含消化、呼吸、循环系统', criticalZones: ['心脏管', '气管系统'], mortalityNote: '气管系统受损致窒息' },
  leftArm:  { lethality: 0.05, vitalOrgan: false, desc: '足/翅膀', criticalZones: [], mortalityNote: '断足不致命' },
  rightArm: { lethality: 0.05, vitalOrgan: false, desc: '足/翅膀', criticalZones: [], mortalityNote: '断足不致命' },
  leftLeg:  { lethality: 0.05, vitalOrgan: false, desc: '足', criticalZones: [], mortalityNote: '断足不致命' },
  rightLeg: { lethality: 0.05, vitalOrgan: false, desc: '足', criticalZones: [], mortalityNote: '断足不致命' },
  },
  specialNote: '昆虫为开管循环系统，血淋巴不携氧，断肢出血极少。需要摧毁中枢神经或气管系统才能有效致死',
  },

  aquatic: {
  typeName: '水生动物', example: '水蛟/蛟龙/海兽',
  parts: {
  head:     { lethality: 0.88, vitalOrgan: true, desc: '水生动物头部同样致命', criticalZones: ['脑干', '鳃弓神经'], mortalityNote: '脑干损伤致死' },
  torso:    { lethality: 0.85, vitalOrgan: true, desc: '含心脏和鳃/肺', criticalZones: ['心脏', '鳃', '鳔'], mortalityNote: '鳃损伤致无法呼吸（水生）或心脏停跳' },
  leftArm:  { lethality: 0.15, vitalOrgan: false, desc: '鳍/前肢', criticalZones: [], mortalityNote: '鳍损伤影响游泳但不致命' },
  rightArm: { lethality: 0.15, vitalOrgan: false, desc: '鳍/前肢', criticalZones: [], mortalityNote: '同左鳍' },
  leftLeg:  { lethality: 0.20, vitalOrgan: false, desc: '尾鳍/后肢', criticalZones: ['尾动脉'], mortalityNote: '尾部大血管损伤可致大量失血' },
  rightLeg: { lethality: 0.20, vitalOrgan: false, desc: '尾鳍/后肢', criticalZones: ['尾动脉'], mortalityNote: '同左' },
  },
  specialNote: '水生动物靠鳃呼吸（鱼类）或肺呼吸（鲸类），鳃损伤=窒息。水中失血速度更快（水流冲散凝血）',
  },

  spirit: {
  typeName: '灵体/妖兽', example: '妖魂/鬼修/魔物',
  parts: {
  head:     { lethality: 0.95, vitalOrgan: true, desc: '灵核所在，意识中枢', criticalZones: ['灵核', '魂魄'], mortalityNote: '灵核破碎致魂飞魄散' },
  torso:    { lethality: 0.80, vitalOrgan: true, desc: '灵力汇聚之所', criticalZones: ['妖丹', '灵脉'], mortalityNote: '妖丹破碎致修为归零' },
  leftArm:  { lethality: 0.10, vitalOrgan: false, desc: '灵力臂', criticalZones: [], mortalityNote: '灵力臂消散不致命' },
  rightArm: { lethality: 0.10, vitalOrgan: false, desc: '灵力臂', criticalZones: [], mortalityNote: '同左' },
  leftLeg:  { lethality: 0.10, vitalOrgan: false, desc: '灵力足', criticalZones: [], mortalityNote: '不致命' },
  rightLeg: { lethality: 0.10, vitalOrgan: false, desc: '灵力足', criticalZones: [], mortalityNote: '不致命' },
  },
  specialNote: '灵体需摧毁灵核或妖丹才能彻底消灭，物理攻击效果减半',
  },
};

export const BODY_PART_MEDICAL: any = {
  head:     { lethality: 0.95, vitalOrgan: true, bloodSupply: 'extreme', nerves: 'extreme', desc: '大脑为中枢神经系统核心，颅内出血可在数分钟内致命；脑干控制呼吸心跳', criticalZones: ['脑干', '大脑皮层', '小脑'], mortalityNote: '脑干损伤致死率接近100%' },
  torso:     { lethality: 0.85, vitalOrgan: true, bloodSupply: 'high', nerves: 'high', desc: '胸腔含心肺，腹腔含肝脾胃肠；穿透伤可致大出血、气胸、脏器破裂', criticalZones: ['心脏', '主动脉', '肝脏', '脾脏'], mortalityNote: '主动脉破裂可在2分钟内失血致死' },
  leftArm:   { lethality: 0.15, vitalOrgan: false, bloodSupply: 'moderate', nerves: 'moderate', desc: '肱动脉受损可致大量失血，但通常不致命', criticalZones: ['肱动脉', '桡神经'], mortalityNote: '单臂损伤极少致命' },
  rightArm:  { lethality: 0.15, vitalOrgan: false, bloodSupply: 'moderate', nerves: 'moderate', desc: '同左臂，优势手受伤影响战斗力更大', criticalZones: ['肱动脉', '正中神经'], mortalityNote: '同左臂' },
  leftLeg:   { lethality: 0.25, vitalOrgan: false, bloodSupply: 'high', nerves: 'moderate', desc: '股动脉为人体最大外周动脉，断裂后可在数分钟内失血2000ml以上致死', criticalZones: ['股动脉', '股神经', '腘动脉'], mortalityNote: '股动脉断裂致死率约30-50%' },
  rightLeg:  { lethality: 0.25, vitalOrgan: false, bloodSupply: 'high', nerves: 'moderate', desc: '同左腿', criticalZones: ['股动脉', '坐骨神经'], mortalityNote: '同左腿' },
  heart:     { lethality: 0.98, vitalOrgan: true, bloodSupply: 'extreme', nerves: 'extreme', desc: '心脏为血液循环动力源，心包填塞可在数分钟内致命', criticalZones: ['左心室', '冠状动脉', '心包'], mortalityNote: '心脏穿透伤院前死亡率>80%' },
  liver:     { lethality: 0.75, vitalOrgan: true, bloodSupply: 'extreme', nerves: 'moderate', desc: '肝脏血供极为丰富，破裂后可快速失血致死', criticalZones: ['肝门', '肝静脉'], mortalityNote: 'III级以上肝破裂死亡率约50%' },
  spleen:    { lethality: 0.60, vitalOrgan: true, bloodSupply: 'high', nerves: 'low', desc: '脾脏血供丰富，外伤极易破裂出血', criticalZones: ['脾门', '脾蒂'], mortalityNote: '脾破裂如不手术，死亡率约25-30%' },
  lung:      { lethality: 0.80, vitalOrgan: true, bloodSupply: 'high', nerves: 'moderate', desc: '双肺负责气体交换；气胸可在数分钟内致命', criticalZones: ['肺门', '主支气管'], mortalityNote: '张力性气胸可在数分钟内致死' },
  kidney:    { lethality: 0.45, vitalOrgan: true, bloodSupply: 'high', nerves: 'moderate', desc: '肾蒂血管丰富，损伤可致大量腹膜后出血；但有两颗肾可代偿', criticalZones: ['肾蒂', '肾盂'], mortalityNote: '单侧肾损伤极少致命' },
  gallbladder: { lethality: 0.20, vitalOrgan: false, bloodSupply: 'low', nerves: 'low', desc: '胆囊储存胆汁，破裂可致胆汁性腹膜炎', criticalZones: ['胆囊颈'], mortalityNote: '胆囊损伤极少直接致命' },
  stomach:     { lethality: 0.25, vitalOrgan: false, bloodSupply: 'moderate', nerves: 'moderate', desc: '胃酸具有强腐蚀性，穿孔可致腹膜炎', criticalZones: ['胃左动脉', '贲门'], mortalityNote: '胃穿孔如不治疗可致感染性休克' },
  smallIntestine: { lethality: 0.20, vitalOrgan: false, bloodSupply: 'moderate', nerves: 'low', desc: '小肠为营养吸收主要场所；穿孔致肠内容物外溢引发腹膜炎', criticalZones: ['肠系膜上动脉'], mortalityNote: '肠系膜血管损伤可致肠坏死' },
  largeIntestine: { lethality: 0.15, vitalOrgan: false, bloodSupply: 'low', nerves: 'low', desc: '大肠含大量细菌，穿孔可致严重腹腔感染', criticalZones: ['结肠中动脉'], mortalityNote: '结肠穿孔感染致死率较高但非即刻' },
  bladder:       { lethality: 0.10, vitalOrgan: false, bloodSupply: 'low', nerves: 'low', desc: '膀胱充盈时易破裂，尿液外渗致腹膜炎', criticalZones: ['膀胱颈'], mortalityNote: '膀胱破裂极少直接致命' },
  sanjiao:       { lethality: 0.15, vitalOrgan: false, bloodSupply: 'low', nerves: 'low', desc: '三焦为中医概念，对应胸腹腔功能分区', criticalZones: [], mortalityNote: '中医概念，对应实际脏器损伤' },
  brain:      { lethality: 0.99, vitalOrgan: true, bloodSupply: 'extreme', nerves: 'extreme', desc: '大脑为意识和生命中枢；颅内压升高可致脑疝压迫脑干致死', criticalZones: ['脑干', '丘脑', '脑桥'], mortalityNote: '脑疝形成后致死率极高' },
  meridians:  { lethality: 0.10, vitalOrgan: false, bloodSupply: 'none', nerves: 'extreme', desc: '经脉为灵气运行通道（修仙概念），阻塞致修炼停滞', criticalZones: [], mortalityNote: '非实体器官，阻塞影响修炼但不直接致命' },
  muscles:    { lethality: 0.05, vitalOrgan: false, bloodSupply: 'moderate', nerves: 'moderate', desc: '肌肉组织，损伤致力量下降；横纹肌溶解可致急性肾衰竭', criticalZones: ['肌腱附着点'], mortalityNote: '单纯肌肉损伤极少致命' },
  skin:       { lethality: 0.03, vitalOrgan: false, bloodSupply: 'moderate', nerves: 'high', desc: '皮肤为人体最大器官，烧伤面积>30%可致命', criticalZones: [], mortalityNote: '大面积烧伤致死率高但非即刻' },
  bones:      { lethality: 0.08, vitalOrgan: false, bloodSupply: 'low', nerves: 'low', desc: '骨骼支撑和保护作用；骨盆骨折可致大量内出血', criticalZones: ['骨盆', '脊柱'], mortalityNote: '骨盆骨折失血致死率约10%' },
  boneMarrow: { lethality: 0.12, vitalOrgan: false, bloodSupply: 'high', nerves: 'low', desc: '骨髓负责造血；损伤致贫血、免疫低下', criticalZones: ['红骨髓'], mortalityNote: '慢性致死而非即刻' },
  dantian: { lethality: 0.5, vitalOrgan: true, bloodSupply: 'none', nerves: 'extreme', desc: '丹田为储存灵力之所（修仙概念），破碎后灵力无法储存', criticalZones: ['丹核'], mortalityNote: '丹田破碎导致灵力归零，修为大降', irreversible: true },
  foundation: { lethality: 0.4, vitalOrgan: true, bloodSupply: 'none', nerves: 'extreme', desc: '根基为修炼之基（修仙概念），崩塌后突破概率大降', criticalZones: ['道基'], mortalityNote: '根基崩塌导致突破成功率归零', irreversible: true },
  spiritualRoot: { lethality: 0.45, vitalOrgan: true, bloodSupply: 'none', nerves: 'extreme', desc: '灵根为感应天地灵气之源（修仙概念），枯萎后修炼速度暴跌', criticalZones: ['灵核'], mortalityNote: '灵根枯萎导致修炼速度接近零', irreversible: true },
};
