// 战斗系统 - 元素+伤害+种族
// 从 v0.35 迁移 - 共 9 个常量

export const ATTACK_ELEMENTS: any = {
  none:    { name: '无属性', icon: '⚪', color: '#aaa', desc: '纯物理攻击，不附带元素' },
  fire:    { name: '火', icon: '🔥', color: '#e74c3c', desc: '灼烧伤害，持续燃烧' },
  water:   { name: '水', icon: '💧', color: '#3498db', desc: '冰冻减速，侵蚀防御' },
  earth:   { name: '土', icon: '🪨', color: '#d4a574', desc: '沉重碾压，粉碎护甲' },
  metal:   { name: '金', icon: '⚔️', color: '#c0c0c0', desc: '锐利穿透，破甲伤害' },
  wood:    { name: '木', icon: '🌿', color: '#27ae60', desc: '缠绕束缚，持续毒素' },
  lightning:{ name: '雷', icon: '⚡', color: '#f1c40f', desc: '麻痹眩晕，穿透防御' },
  wind:    { name: '风', icon: '🌪️', color: '#1abc9c', desc: '极速切割，范围攻击' },
  ice:     { name: '冰', icon: '❄️', color: '#74b9ff', desc: '冻结减速，冰晶碎裂' },
  dark:    { name: '暗', icon: '🌑', color: '#2c3e50', desc: '侵蚀腐蚀，虚弱敌人' },
  light:   { name: '光', icon: '☀️', color: '#f39c12', desc: '净化灼烧，克制阴邪' },
  poison:  { name: '毒', icon: '☠️', color: '#2ecc71', desc: '持续毒伤，削弱体质' },
  void:    { name: '虚空', icon: '🌀', color: '#8e44ad', desc: '空间撕裂，无视防御' },
  chaos:   { name: '混沌', icon: '💫', color: '#e67e22', desc: '混乱之力，随机效果' },
  blood:   { name: '血', icon: '🩸', color: '#c0392b', desc: '吸血回生，血祭增伤' },
};

export const DAMAGE_CATEGORIES: any = {
  force: { name: '力道伤', icon: '👊', desc: '钝器冲击造成的挫伤，伤及皮下组织', color: '#e67e22',
  affectParts: ['torso','head','leftArm','rightArm','leftLeg','rightLeg','bones','muscles'],
  radiation: 0.15, healRate: 0.8, // 自然恢复速率
  },
  tear: { name: '撕裂伤', icon: '🩸', desc: '利器切割造成的开放性创伤，大量失血', color: '#e74c3c',
  affectParts: ['skin','muscles','torso','leftArm','rightArm','leftLeg','rightLeg'],
  radiation: 0.25, healRate: 0.5, bleedRate: 0.02,
  },
  pierce: { name: '洞察伤', icon: '🗡️', desc: '穿刺伤深入内脏，可致脏器破裂', color: '#c0392b',
  affectParts: ['heart','liver','lung','spleen','kidney','torso','stomach'],
  radiation: 0.35, healRate: 0.3,
  },
  elemental: { name: '属性伤', icon: '🔥', desc: '五行元素之力灼烧/冻结/侵蚀', color: '#9b59b6',
  affectParts: ['skin','muscles','meridians','lung','liver'],
  radiation: 0.4, healRate: 0.4, elemental: true,
  },
  origin: { name: '本源伤', icon: '💫', desc: '直接攻击生命本源，极难治愈', color: '#8e44ad',
  affectParts: ['dantian','foundation','spiritualRoot','heart','brain'],
  radiation: 0.5, healRate: 0.1, irreversible: false,
  },
  daoFoundation: { name: '道基伤', icon: '🏚️', desc: '道基崩裂之伤，动摇修炼根本', color: '#7f8c8d',
  affectParts: ['foundation','meridians','dantian','brain'],
  radiation: 0.3, healRate: 0.05, // 极难自然恢复
  },
  spiritualRootDmg: { name: '灵根伤', icon: '🥀', desc: '灵根受损，修炼资质下降', color: '#27ae60',
  affectParts: ['spiritualRoot','meridians','dantian'],
  radiation: 0.2, healRate: 0.03,
  },
  dantianDmg: { name: '丹田伤', icon: '🕳️', desc: '丹田破裂，灵力外泄', color: '#2980b9',
  affectParts: ['dantian','meridians','foundation'],
  radiation: 0.3, healRate: 0.05,
  },
};

export const DAMAGE_TYPE_NAMES: any = {
  physical_blunt:'钝器冲击',physical_sharp:'利器切割',physical_pierce:'穿刺伤害',
  fire:'火焰灼烧',ice:'寒冰侵袭',thunder:'雷电轰击',poison:'毒素侵蚀',
  spiritual:'精神冲击',qi:'灵气暴走',dark:'阴邪侵蚀',void:'虚空之力'
};

export const SPECIES_ATTACK_DATA: any = {

  '蛇': { primaryAttack: '毒牙咬击', attackPart: 'fang', damageType: 'physical_pierce', element: 'poison', desc: '毒蛇以管牙/沟牙注入毒液；蟒蛇以缠绕绞杀为主', special: '毒液注入（神经毒素/血液毒素/细胞毒素）', bodyPartIcon: '🦷' },
  '蟒': { primaryAttack: '缠绕绞杀', attackPart: 'muscle', damageType: 'physical_blunt', element: 'none', desc: '蟒蛇以强大体侧肌肉缠绕猎物，持续施压致窒息', special: '绞杀压力约6psi，阻断血液循环和呼吸', bodyPartIcon: '💪' },

  '鹰': { primaryAttack: '利爪抓击', attackPart: 'claw', damageType: 'physical_pierce', element: 'none', desc: '鹰爪握力达体重10倍，可刺穿猎物内脏', special: '角雕爪长13cm，握力50kg/cm²', bodyPartIcon: '🐾' },
  '鹤': { primaryAttack: '喙啄攻击', attackPart: 'beak', damageType: 'physical_pierce', element: 'none', desc: '鹤以长喙精准啄击', special: '高速啄击可达6m/s', bodyPartIcon: '🔶' },
  '鸦': { primaryAttack: '喙啄+群攻', attackPart: 'beak', damageType: 'physical_blunt', element: 'none', desc: '乌鸦聪明且群体攻击', special: '可记住人类面孔并报复', bodyPartIcon: '🔶' },

  '虎': { primaryAttack: '掌击+咬喉', attackPart: 'fang', damageType: 'physical_sharp', element: 'none', desc: '虎掌击力达450kg，犬齿可穿刺颈椎', special: '单掌拍击力约1吨', bodyPartIcon: '🦷' },
  '狮': { primaryAttack: '群体围猎+咬喉', attackPart: 'fang', damageType: 'physical_sharp', element: 'none', desc: '狮群协作猎杀，咬合力约650psi', special: '雄狮鬃毛保护颈部', bodyPartIcon: '🦷' },
  '熊': { primaryAttack: '掌击', attackPart: 'limb', damageType: 'physical_blunt', element: 'none', desc: '熊掌击力可达800kg以上', special: '爪长10-15cm，可撕裂和击打', bodyPartIcon: '🐾' },
  '狼': { primaryAttack: '群体消耗+咬击', attackPart: 'fang', damageType: 'physical_sharp', element: 'none', desc: '狼群战术性围猎消耗猎物体力', special: '咬合力约400psi，耐力极佳', bodyPartIcon: '🦷' },
  '猿': { primaryAttack: '拳击+投掷', attackPart: 'limb', damageType: 'physical_blunt', element: 'none', desc: '灵长类以拳击和投掷攻击', special: '银背大猩猩握力是人类10倍', bodyPartIcon: '💪' },
  '狐': { primaryAttack: '偷袭咬击', attackPart: 'fang', damageType: 'physical_pierce', element: 'none', desc: '狐狸灵活偷袭，咬击快速', special: '可装死诱敌', bodyPartIcon: '🦷' },

  '蜥': { primaryAttack: '尾鞭+咬击', attackPart: 'tail', damageType: 'physical_blunt', element: 'none', desc: '蜥蜴以尾鞭和咬击防御', special: '科莫多巨蜥咬合力+细菌感染', bodyPartIcon: '💫' },
  '龟': { primaryAttack: '咬击+壳撞', attackPart: 'head', damageType: 'physical_blunt', element: 'earth', desc: '龟以坚硬外壳防御+有力咬击', special: '鳄龟咬合力约450N', bodyPartIcon: '🦷' },

  '蜂': { primaryAttack: '毒刺蜇击', attackPart: 'stinger', damageType: 'physical_pierce', element: 'poison', desc: '蜂以蜇针注入毒液，蜜蜂蜇后死亡', special: '毒液含蜂毒肽（melittin），引起溶血', bodyPartIcon: '🗡️' },
  '蝎': { primaryAttack: '尾刺注射', attackPart: 'stinger', damageType: 'physical_pierce', element: 'poison', desc: '蝎以尾刺注射神经毒素', special: '蝎毒含Na+和K+通道毒素', bodyPartIcon: '🗡️' },
  '蛛': { primaryAttack: '毒牙咬+蛛网缠', attackPart: 'fang', damageType: 'physical_pierce', element: 'poison', desc: '蜘蛛以蛛网束缚+毒牙注入消化液', special: '黑寡妇毒液含α-拉特罗毒素', bodyPartIcon: '🦷' },
  '蜈蚣': { primaryAttack: '毒颚咬击', attackPart: 'head', damageType: 'physical_pierce', element: 'poison', desc: '蜈蚣以第一对毒爪（颚足）注入毒液', special: '蜈蚣毒含组胺和心脏毒素', bodyPartIcon: '🦷' },

  '牛': { primaryAttack: '犄角顶撞', attackPart: 'horn', damageType: 'physical_pierce', element: 'earth', desc: '牛以犄角顶撞+蹄踏', special: '冲撞速度可达40km/h', bodyPartIcon: '🐂' },
  '鹿': { primaryAttack: '犄角撞击', attackPart: 'horn', damageType: 'physical_blunt', element: 'none', desc: '鹿以角撞击（雄鹿繁殖季争斗）', special: '马鹿角展可达1m', bodyPartIcon: '🐂' },
  '马': { primaryAttack: '后蹄踢击', attackPart: 'limb', damageType: 'physical_blunt', element: 'none', desc: '马以后蹄踢击防御', special: '踢击力可达2000N', bodyPartIcon: '🐾' },

  '象': { primaryAttack: '踩踏+象鼻', attackPart: 'limb', damageType: 'physical_blunt', element: 'earth', desc: '大象以体重踩踏+象鼻抽打', special: '体重3-5吨，踩踏力无可匹敌', bodyPartIcon: '🐾' },
};

export const MONSTER_INTERNAL_ORGANS: any = {
  quadruped: { // 四足哺乳动物（狼、熊、虎、鹿等）
  heart:  { name: '心脏', icon: '❤️', hpPct: 0.06, lethality: 0.95, position: 'front-center', desc: '位于胸腔左侧第3-5肋间，泵血中枢。心脏停跳10秒内即意识丧失，3-5分钟不可逆脑死亡。',
  fatalWound: '心包填塞（血液填塞心包导致心脏无法舒张）、冠脉断裂、心肌穿透伤。致死时间：大出血时30秒-2分钟。',
  medicalData: '哺乳动物心脏位于胸腔纵隔内，约占体重0.5-0.7%。心包为纤维浆膜囊，心包腔含15-50ml浆液。穿透性心脏损伤死亡率高达70-80%（Bolanos等, 2021）。' },
  lung:   { name: '肺脏', icon: '🫁', hpPct: 0.08, lethality: 0.75, position: 'front-center', desc: '双肺位于胸腔，占据大部分胸腔空间。肺破裂导致气胸/血气胸，窒息死亡。',
  fatalWound: '张力性气胸（单向阀导致胸腔积气）、肺大血管破裂。致死时间：张力性气胸可在数分钟内致命。',
  medicalData: '犬肺约占体重2.5%。肺泡展开面积约70m²（大型犬）。气胸时纵隔移位导致静脉回流障碍，死亡率高。' },
  liver:  { name: '肝脏', icon: '🟤', hpPct: 0.07, lethality: 0.70, position: 'front-right', desc: '位于右季肋区，最大实体器官。肝脏血流量极大（25%心输出量），破裂可致致命出血。',
  fatalWound: '肝脏碎裂导致失血性休克。致死时间：肝门静脉或肝动脉断裂可在1-3分钟内致死。',
  medicalData: '肝脏是腹腔内最易受伤的器官（钝性腹部伤中占首位）。肝脏接受25%心输出量，约1.5L/min。肝破裂分为I-VI级，III级以上死亡率显著升高。' },
  spleen: { name: '脾脏', icon: '💜', hpPct: 0.04, lethality: 0.55, position: 'front-left', desc: '位于左季肋区，血库功能。脾破裂导致腹腔内大出血。',
  fatalWound: '脾蒂断裂导致快速失血。致死时间：脾门部破裂可在5-15分钟内致死。',
  medicalData: '脾脏是最常被损伤的腹部脏器之一。脾脏储血约250ml（大型犬），破裂时可失血500-1500ml。' },
  kidney: { name: '肾脏', icon: '🫘', hpPct: 0.04, lethality: 0.50, position: 'back', desc: '位于腹膜后，双肾。肾破裂导致腹膜后血肿和肾功能衰竭。',
  fatalWound: '肾蒂断裂可致快速失血。单肾损伤通常不致命，双肾碎裂致尿毒症死亡。',
  medicalData: '肾脏血流量占心输出量20-25%，但仅占体重0.5%。肾外伤后高血压发生率可达25%。' },
  brain:  { name: '大脑', icon: '🧠', hpPct: 0.05, lethality: 0.99, position: 'head', desc: '位于颅腔内，神经中枢。脑组织极其脆弱，任何穿透伤几乎必然致命。',
  fatalWound: '颅内出血（硬膜外/下血肿）、脑干损伤。致死时间：脑干直接损伤即刻死亡。',
  medicalData: '犬脑约占体重0.6-1.0%。颅内压正常5-12mmHg，超过20mmHg脑疝风险极高。脑干（延髓）控制呼吸和心血管中枢，损伤后迅速死亡。' },
  spine:  { name: '脊柱', icon: '🦴', hpPct: 0.05, lethality: 0.60, position: 'back', desc: '中枢神经通道。脊髓断裂导致截瘫，高位颈髓断裂可致呼吸停止。',
  fatalWound: 'C1-C3脊髓损伤导致膈肌瘫痪，窒息死亡。致死时间：立即-数分钟。',
  medicalData: '脊髓损伤平面决定预后。C3以上损伤致呼吸停止需即刻死亡。胸腰段损伤致后肢瘫痪但不立即致命。' },
  stomach: { name: '胃', icon: '🟢', hpPct: 0.04, lethality: 0.30, position: 'front-center', desc: '消化器官。穿孔导致胃内容物进入腹腔引起化学性腹膜炎。',
  fatalWound: '胃穿孔后继发感染性腹膜炎，败血症。致死时间：数小时至数天。',
  medicalData: '胃穿孔后胃酸（pH 1-2）和消化酶进入腹腔，6小时内即可发生严重化学性腹膜炎。' },
  intestine: { name: '肠道', icon: '〰️', hpPct: 0.05, lethality: 0.25, position: 'front-lower', desc: '消化吸收器官。肠破裂导致粪便性腹膜炎。',
  fatalWound: '多段肠破裂导致弥漫性腹膜炎、败血症。致死时间：12-72小时。',
  medicalData: '肠内容物含10⁸-10¹¹ CFU/ml细菌。肠破裂后感染性腹膜炎死亡率高达30-50%。' },
  spine_cord: { name: '脊髓', icon: '⚡', hpPct: 0.03, lethality: 0.70, position: 'back', desc: '神经传导通道。直接损伤导致传导阻断。',
  fatalWound: '高位颈髓损伤致呼吸心跳停止。',
  medicalData: '脊髓对机械损伤极度敏感。完全横断后损伤平面以下功能完全丧失。' },
  body:   { name: '躯干', icon: '🐾', hpPct: 0.18, lethality: 0.35, position: 'center', desc: '承载心肺肝脾等要害脏器的躯体外壳。',
  fatalWound: '躯干大面积穿透伤导致多脏器联合损伤。',
  medicalData: '四足动物躯干容纳胸腔和腹腔所有脏器。大面积穿透伤往往涉及多器官联合损伤，死亡率随损伤器官数量指数级上升。' },
  tail:   { name: '尾巴', icon: '💫', hpPct: 0.06, lethality: 0.10, position: 'back', desc: '平衡和辅助攻击器官。',
  fatalWound: '尾巴断裂导致失去平衡。',
  medicalData: '多数哺乳动物尾巴为平衡器官，断裂通常不致命。但尾椎骨折可损伤马尾神经。' },
  },

  serpentine_snake: { // 纯蛇类（无龙族特征）——基于真实蛇类解剖学
  head:   { name: '蛇首', icon: '🐍', hpPct: 0.10, lethality: 0.88, desc: '蛇头为攻击要害，含毒牙（管牙/沟牙）及感知器官（颊窝、犁鼻器）。毒蛇头部呈典型三角形。',
  fatalWound: '颅骨碎裂致脑死亡；毒腺破裂导致毒液反噬自身组织。',
  medicalData: '蛇类头部含大脑（约占体重0.05-0.1%）、毒腺（上颌后方）、颊窝（蝮蛇科红外感应器）及犁鼻器（Jacobson器官，味觉化学感受）。蛇脑虽小但控制所有自主功能。毒蛇毒腺由咬肌压缩，毒液通过中空毒牙注入猎物。' },
  heart:  { name: '蛇心', icon: '❤️', hpPct: 0.06, lethality: 0.85, desc: '蛇心为三腔心脏（两心房一心室），位于躯干前1/3处。心搏频率极低（蟒蛇仅15-25次/分），但每次泵血量大。',
  fatalWound: '心脏穿透导致循环衰竭。蛇类血液含高效携氧血红蛋白，失血极快致死。',
  medicalData: '蛇类心脏位于体长前25-33%处。三腔心允许混合动脉血和静脉血，但效率低于四腔心。蟒蛇在消化期间心脏质量可增大40%以满足代谢需求（Secor & Diamond, 1995）。' },
  lung:   { name: '蛇肺', icon: '🫁', hpPct: 0.06, lethality: 0.60, desc: '蛇类仅有右肺发育（左肺退化或缺失），右肺极长，延伸至体长40%处。前段为呼吸部，后段为气囊。',
  fatalWound: '肺破裂导致气胸，窒息死亡。大型蛇类因体长，肺损伤后呼吸效率骤降。',
  medicalData: '蟒蛇保留退化的左肺。右肺前段含肺泡进行气体交换，后段为薄壁气囊（可储存空气）。蛇类呼吸频率极低（静息时1-4次/分），靠肋间肌扩张体腔吸气。' },
  liver:  { name: '蛇肝', icon: '🟤', hpPct: 0.07, lethality: 0.55, desc: '蛇肝分多叶，是最大消化腺体。功能包括解毒、胆汁分泌、糖原储存。毒蛇肝脏对自身毒液有特殊抗性。',
  fatalWound: '肝脏大面积撕裂导致腹腔内大出血，失血性休克。',
  medicalData: '蛇类肝脏占体重2-4%，分2-3叶。消化期间肝脏代谢活动激增（可增大10-30%）。蛇类血浆中含有针对自身毒液的中和蛋白（inhibitory proteins）。' },
  venom_gland: { name: '毒腺', icon: '☠️', hpPct: 0.04, lethality: 0.70, desc: '毒蛇特有毒腺位于上颌后方，由咬肌包围。挤压毒腺可将毒液通过毒牙注入猎物。毒液含神经毒素、血液毒素或细胞毒素。',
  fatalWound: '毒腺破裂导致毒液反噬自身血循环。',
  medicalData: '毒腺是特化的唾液腺。眼镜蛇科毒液以神经毒素为主（α-神经毒素阻断乙酰胆碱受体）；蝰蛇科以血液毒素为主（磷脂酶A2破坏红细胞膜、金属蛋白酶引起凝血障碍）。毒腺含抗自身毒液蛋白，防止自中毒。' },
  spine:  { name: '脊柱', icon: '🦴', hpPct: 0.08, lethality: 0.65, desc: '蛇类脊柱由200-400块椎骨组成（蟒蛇可达400+），是全身骨架主体。脊髓贯穿整个脊柱，控制全身运动。',
  fatalWound: '高位脊髓断裂（前1/3段）可导致呼吸肌瘫痪致死；中后段断裂致后半身瘫痪。',
  medicalData: '蛇类每块椎骨连接一对肋骨（除尾椎外）。脊柱提供侧向弯曲的运动能力，但不能上下弯曲。每节椎骨有独立的脊神经分出，控制对应体节的肌肉和感觉。' },
  scale:  { name: '蛇鳞', icon: '🛡️', hpPct: 0.10, lethality: 0.08, desc: '蛇鳞为角质化表皮鳞片，提供物理防护和减少摩擦。蜕皮时整层脱落。',
  fatalWound: '大面积鳞片脱落导致脱水和感染风险。',
  medicalData: '蛇鳞由β-角蛋白构成（与人类指甲同源）。腹鳞特化用于运动（与肋骨末端肌肉配合产生"蠕动"运动）。蜕皮周期因物种和营养状态而异，幼蛇更频繁。' },
  muscle: { name: '缠绕肌', icon: '💪', hpPct: 0.15, lethality: 0.35, desc: '蟒蛇/蚺蛇的主要攻击器官——强壮的体侧肌肉群，用于缠绕绞杀猎物。缠绕时施加持续压力使猎物无法呼吸。',
  fatalWound: '肌肉大面积撕裂丧失缠绕能力。',
  medicalData: '蟒蛇缠绕力可达6psi（约41kPa），足以阻断猎物血液循环。每次猎物呼气时蛇会收紧，阻止再次吸气（Boback et al., 2015）。绞杀致死原因是缺氧而非骨骼断裂。' },
  body:   { name: '蛇躯', icon: '🐍', hpPct: 0.20, lethality: 0.40, desc: '蛇躯容纳所有内脏器官，由脊柱和肋骨构成骨架，外覆肌肉和鳞片。',
  fatalWound: '躯干大面积穿透伤导致多脏器联合损伤。',
  medicalData: '蛇体内脏呈线性排列以适应细长体型。消化道从口腔到泄殖腔直线排列，消化时肠道表面积可增大数倍以适应大餐后的高代谢需求。' },
  tail:   { name: '蛇尾', icon: '💫', hpPct: 0.06, lethality: 0.10, desc: '蛇尾含尾椎，用于平衡和部分物种的辅助攻击（如响尾蛇的响环、钩尾蛇的尾尖）。',
  fatalWound: '尾部断裂通常不致命，但丧失响尾警告功能。',
  medicalData: '蛇尾长度约占体长10-20%。部分树栖蛇类尾部具缠绕功能（缠尾蛇）。响尾蛇尾端角质响环由每次蜕皮残留构成。泄殖腔位于躯干与尾部交界处。' },
  fang:   { name: '毒牙', icon: '🦷', hpPct: 0.03, lethality: 0.50, desc: '毒蛇的注射器官。前毒牙类（眼镜蛇科）毒牙固定；后毒牙类（游蛇科）毒牙在口腔后部；管牙类（蝰蛇科）毒牙可折叠。',
  fatalWound: '毒牙断裂丧失毒液注射能力。',
  medicalData: '毒牙是特化的上颌齿。管牙（solenoglyphous）中空如注射针头，长度可达2cm（加蓬咝蝰）。沟牙（proteroglyphous）表面有导液沟。毒牙定期更替（备用牙随时准备替换）。' },
  },
  serpentine_dragon: { // 龙族——拥有灵力器官和翅膀等龙族特有结构
  head:   { name: '龙头', icon: '🐲', hpPct: 0.10, lethality: 0.92, desc: '龙首为要害，脑部位于颅腔内。龙角是灵力汇聚之处，可引动天雷。',
  fatalWound: '龙脑碎裂即死，龙角断裂导致灵力外泄。',
  medicalData: '龙族大脑远大于蛇类，含灵力结晶节点（灵核分部）。龙角为灵力天线，可感应天地灵气波动。龙族已开灵智，首级即命门。' },
  heart:  { name: '龙心', icon: '❤️‍🔥', hpPct: 0.08, lethality: 0.90, desc: '龙心位于躯干前1/3处，跳动缓慢但力量巨大。龙心内含灵力结晶，每一次搏动都释放灵力波动。',
  fatalWound: '龙心破裂，龙血（含高浓度灵力）瞬间外泄。',
  medicalData: '龙族心脏为三腔（两心房一心室）但含灵力结晶核心，搏动频率15-25次/分钟。灵力结晶碎裂后灵力暴走可引发体内灵爆。龙血含高浓度灵力，呈金红色。' },
  lung:   { name: '龙肺', icon: '🫁', hpPct: 0.06, lethality: 0.65, desc: '龙肺硕大，延伸至躯干中段。含火灵力晶体，可喷吐龙息（高温灵焰）。',
  fatalWound: '龙肺爆裂导致龙息失控反噬。',
  medicalData: '龙类仅右肺发育但极长，延伸至体长40%处。龙肺含火灵力晶体矩阵，压缩灵力后经口腔喷出形成龙息。龙息温度可达3000°C（太阳表面约5500°C）。' },
  liver:  { name: '龙肝', icon: '🟤', hpPct: 0.06, lethality: 0.60, desc: '龙肝为龙族排毒器官，含龙毒（龙族特有毒素，对凡人致命）。',
  fatalWound: '龙肝碎裂，龙毒反噬全身。',
  medicalData: '龙肝分叶明显，解毒功能极强。龙肝浓缩了龙族独有的龙血毒素（一种混合型神经-血液毒素），破裂后毒素逆流进入血液循环。龙族对自身毒素免疫。' },
  meridian: { name: '龙脉', icon: '🌀', hpPct: 0.07, lethality: 0.75, desc: '龙族经脉沿躯干延伸，是灵力运行的主干道。龙脉网络远比凡人经脉复杂。',
  fatalWound: '龙脉断裂，灵力暴走失控。',
  medicalData: '类比脊髓神经丛但含灵力传导功能。龙脉是龙族特有的灵力传导系统，断裂后灵力紊乱可引发体内爆破。龙脉沿脊柱两侧延伸，每隔数尺有灵力节点（类穴位）。' },
  scale:  { name: '龙鳞', icon: '🛡️', hpPct: 0.12, lethality: 0.10, desc: '龙鳞为外层防御，极为坚硬，含金属元素结晶。',
  fatalWound: '龙鳞全部脱落导致防御崩溃。',
  medicalData: '龙鳞含有金属元素结晶（铁、铜、钛的灵力合金），硬度堪比金刚石（莫氏硬度10）。龙鳞按五行属性呈不同颜色：金鳞银白、木鳞翠绿、水鳞靛蓝、火鳞赤红、土鳞金黄。' },
  wing:   { name: '龙翼', icon: '🌬️', hpPct: 0.08, lethality: 0.20, desc: '有翼龙族的飞行器官，翼展可达体长2-3倍。',
  fatalWound: '龙翼断裂丧失飞行能力。',
  medicalData: '翼膜含大量血管和灵力脉络。龙翼断裂时出血量大但非致命。无翼龙（如蛟龙、应龙幼体）不具此部位。翼骨结构类似蝙蝠，由延长的指骨支撑翼膜。' },
  claw:   { name: '龙爪', icon: '🦅', hpPct: 0.06, lethality: 0.15, desc: '龙族攻击利器，五爪金龙为最高品阶。',
  fatalWound: '丧失攻击能力。',
  medicalData: '龙爪为角质结构，含灵力加持。五爪龙为皇族血统标志。龙爪断裂可再生但需数年，再生期间灵力凝聚于爪根处。' },
  tail:   { name: '龙尾', icon: '💫', hpPct: 0.10, lethality: 0.25, desc: '龙尾为辅助攻击和平衡器官。龙尾末端可凝聚灵力进行鞭击。',
  fatalWound: '失去平衡能力。',
  medicalData: '龙尾含尾椎和灵力储存结构。龙尾鞭击可产生音爆（超过音速）。尾部断裂后部分龙族可再生，需消耗大量灵力。' },
  body:   { name: '龙躯', icon: '🐉', hpPct: 0.20, lethality: 0.50, desc: '龙躯承载所有脏器。龙躯内有灵力循环系统，遍布龙脉。',
  fatalWound: '躯干大面积穿透伤可损及多个脏器。',
  medicalData: '躯干是所有内脏器官的容器，大面积损伤往往涉及多个器官联合损伤，死亡率极高。龙躯内灵力密度远高于凡间生物，破裂后灵力外泄可伤及近身者。' },
  horn:   { name: '龙角', icon: '🔱', hpPct: 0.05, lethality: 0.30, desc: '龙角为灵力汇聚与天雷引动之器。',
  fatalWound: '龙角断裂导致灵力控制力下降。',
  medicalData: '龙角由角蛋白和灵力结晶共同构成，类似鹿角但含灵力结构。龙角是灵力天线，断裂后灵力感应能力大幅下降。' },
  },
  humanoid: { // 魔族/不死族等类人形态
  head:    { name: '头部', icon: '💀', hpPct: 0.08, lethality: 0.95, desc: '控制中枢', fatalWound: '颅骨碎裂', medicalData: '类人结构，致命性与人类相似。' },
  torso:   { name: '躯干', icon: '💥', hpPct: 0.25, lethality: 0.60, desc: '脏器容器', fatalWound: '脏器大面积损伤', medicalData: '容纳心肺肝脾等要害器官。' },
  heart:   { name: '心脏', icon: '❤️', hpPct: 0.06, lethality: 0.90, desc: '泵血中枢', fatalWound: '心脏停跳', medicalData: '与人类心脏结构类似。' },
  lung:    { name: '肺部', icon: '🫁', hpPct: 0.07, lethality: 0.70, desc: '呼吸器官', fatalWound: '窒息', medicalData: '双肺结构。' },
  arm_l:   { name: '左臂', icon: '💪', hpPct: 0.06, lethality: 0.10, desc: '肢体', fatalWound: '失血过多', medicalData: '非致命部位。' },
  arm_r:   { name: '右臂', icon: '💪', hpPct: 0.06, lethality: 0.10, desc: '肢体', fatalWound: '失血过多', medicalData: '非致命部位。' },
  leg_l:   { name: '左腿', icon: '🦵', hpPct: 0.07, lethality: 0.10, desc: '肢体', fatalWound: '失血过多', medicalData: '股动脉损伤可致命。' },
  leg_r:   { name: '右腿', icon: '🦵', hpPct: 0.07, lethality: 0.10, desc: '肢体', fatalWound: '失血过多', medicalData: '股动脉损伤可致命。' },
  spine:   { name: '脊柱', icon: '🦴', hpPct: 0.05, lethality: 0.55, desc: '中枢神经', fatalWound: '高位截瘫', medicalData: '脊髓损伤预后取决于损伤平面。' },
  brain:   { name: '大脑', icon: '🧠', hpPct: 0.05, lethality: 0.98, desc: '神经中枢', fatalWound: '脑死亡', medicalData: '中枢神经不可再生。' },
  dantian: { name: '魔丹/丹田', icon: '🌀', hpPct: 0.06, lethality: 0.85, desc: '能量核心', fatalWound: '魔丹碎裂，灵力暴走', medicalData: '修仙体系核心，碎裂后灵力反噬。' },
  },
  ethereal: { // 灵族/鬼族
  soul_core: { name: '灵核', icon: '👻', hpPct: 0.15, lethality: 0.95, desc: '灵体核心，存续之所', fatalWound: '灵核碎裂，魂飞魄散', medicalData: '灵体不具物理器官，灵核为能量凝聚核心。' },
  body:      { name: '灵体', icon: '💀', hpPct: 0.35, lethality: 0.40, desc: '灵力构成的躯体', fatalWound: '灵体溃散', medicalData: '灵体由魂力凝聚，损伤后灵力逸散。' },
  eye:       { name: '邪眼', icon: '👁️', hpPct: 0.10, lethality: 0.60, desc: '窥视万物之眼', fatalWound: '邪眼碎裂导致灵识崩溃', medicalData: '灵族感知器官，连接灵识。' },
  aura:      { name: '阴气', icon: '🌫️', hpPct: 0.15, lethality: 0.20, desc: '灵体外围的灵力场', fatalWound: '阴气耗尽', medicalData: '灵力场为灵体提供持续防护。' },
  claw:      { name: '鬼爪', icon: '🦴', hpPct: 0.15, lethality: 0.50, desc: '灵力凝聚的攻击爪', fatalWound: '爪碎', medicalData: '灵力凝聚物。' },
  },
  elemental: { // 元素生物
  core:    { name: '元素核心', icon: '💎', hpPct: 0.15, lethality: 0.95, desc: '元素之力凝聚的核心', fatalWound: '核心碎裂，元素失控', medicalData: '元素生命的能量核心，碎裂即死亡。' },
  body:    { name: '元素体', icon: '🔥', hpPct: 0.40, lethality: 0.30, desc: '纯粹元素构成的躯体', fatalWound: '元素耗散', medicalData: '元素生命无固定形态。' },
  flow:    { name: '元素流', icon: '🌊', hpPct: 0.20, lethality: 0.40, desc: '体内元素循环通道', fatalWound: '元素暴走', medicalData: '元素循环类似血液循环。' },
  aura:    { name: '元素场', icon: '⚡', hpPct: 0.15, lethality: 0.15, desc: '外围元素能量场', fatalWound: '能量场溃散', medicalData: '主动防护层。' },
  shell:   { name: '元素外壳', icon: '🪨', hpPct: 0.10, lethality: 0.05, desc: '凝固的外层防护', fatalWound: '外壳碎裂', medicalData: '防御层。' },
  },
  plant: { // 植物类
  root:     { name: '灵根', icon: '🌿', hpPct: 0.15, lethality: 0.85, desc: '灵根为核心，断根即死', fatalWound: '灵根断裂', medicalData: '植物根系为生命之源。灵根类似动物心脏。' },
  trunk:    { name: '树干', icon: '🪵', hpPct: 0.30, lethality: 0.40, desc: '躯干主体', fatalWound: '树干折断', medicalData: '维管束为运输系统。' },
  branch:   { name: '枝条', icon: '🌾', hpPct: 0.12, lethality: 0.15, desc: '攻击/感知枝条', fatalWound: '枝条断裂', medicalData: '非核心器官。' },
  leaf:     { name: '灵叶', icon: '🍃', hpPct: 0.10, lethality: 0.20, desc: '光合/灵力吸收', fatalWound: '灵叶脱落', medicalData: '类比肺脏呼吸功能。' },
  flower:   { name: '灵花', icon: '🌸', hpPct: 0.08, lethality: 0.35, desc: '灵力/毒素发射器', fatalWound: '灵花凋零', medicalData: '生殖/防御器官。' },
  sap:      { name: '灵液', icon: '💧', hpPct: 0.15, lethality: 0.25, desc: '灵液循环系统', fatalWound: '灵液枯竭', medicalData: '类比血液系统。' },
  core:     { name: '木心', icon: '💚', hpPct: 0.10, lethality: 0.80, desc: '树心为灵力储存处', fatalWound: '木心碎裂', medicalData: '年轮中心最老的部分，储存灵力。' },
  },
  insectoid: { // 昆虫类
  head:     { name: '头部', icon: '🐛', hpPct: 0.08, lethality: 0.90, desc: '触角和复眼所在', fatalWound: '头部碎裂', medicalData: '昆虫头部含触角、复眼和口器。' },
  thorax:   { name: '胸节', icon: '🔴', hpPct: 0.20, lethality: 0.70, desc: '运动中枢，足和翅附着处', fatalWound: '胸节碎裂', medicalData: '三对足附着在胸节。' },
  abdomen:  { name: '腹节', icon: '🟡', hpPct: 0.25, lethality: 0.60, desc: '消化和生殖器官所在', fatalWound: '腹节碎裂', medicalData: '内脏集中在腹节。蜜蜂腹部有螫针。' },
  shell:    { name: '甲壳', icon: '🪲', hpPct: 0.15, lethality: 0.10, desc: '外骨骼防护', fatalWound: '甲壳碎裂', medicalData: '几丁质外骨骼。' },
  wing:     { name: '翅翼', icon: '🦋', hpPct: 0.08, lethality: 0.15, desc: '飞行器官', fatalWound: '翅翼断裂', medicalData: '膜质翅，断裂后不可再生。' },
  leg:      { name: '虫足', icon: '🦂', hpPct: 0.12, lethality: 0.10, desc: '运动器官', fatalWound: '足断', medicalData: '断足可再生蜕皮。' },
  stinger:  { name: '毒刺', icon: '🗡️', hpPct: 0.05, lethality: 0.20, desc: '攻击器官', fatalWound: '毒刺断', medicalData: '部分蜂类螫针带倒刺，使用后死亡。' },
  venom:    { name: '毒囊', icon: '☠️', hpPct: 0.07, lethality: 0.35, desc: '储存毒液', fatalWound: '毒囊破裂，毒液反噬', medicalData: '毒腺分泌毒液储存。' },
  },
  avian: { // 鸟类/猛禽类——基于真实鸟类解剖学
  head:     { name: '鸟首', icon: '🦅', hpPct: 0.08, lethality: 0.85, desc: '鸟类头部含喙（攻击/取食器官）、眼（视力极佳，猛禽视力为人类4-8倍）和脑。',
  fatalWound: '颅骨碎裂致脑死亡。',
  medicalData: '鸟类头骨薄而轻但坚固。猛禽视力极锐利（鹰眼分辨率为人类8倍），双眼视野达340°。鸟喙为角蛋白构成，无齿但锋利。鹰喙可撕裂猎物皮肉。' },
  heart:    { name: '鸟心', icon: '❤️', hpPct: 0.05, lethality: 0.85, desc: '鸟类心脏为四腔心，搏动极快（小型鸟1000+次/分，鹰约300次/分），代谢率极高。',
  fatalWound: '心脏穿透导致快速失血。',
  medicalData: '鸟类四腔心比例占体重比例远高于哺乳类（蜂鸟心脏占体重2.5%）。高心率支持飞行的高代谢需求。鸟类血红蛋白含线粒体，携氧效率高于哺乳类。' },
  lung:     { name: '气囊', icon: '🫁', hpPct: 0.06, lethality: 0.55, desc: '鸟类肺部含气囊系统（9个气囊），呼吸效率远高于哺乳类——双向气流使氧气交换更充分。',
  fatalWound: '气囊破裂导致飞行能力丧失。',
  medicalData: '鸟类呼吸系统独特：气囊延伸至中空的骨骼内。吸气和呼气时空气均通过肺部（单向气流系统），氧气交换效率是哺乳类的3倍。气囊破裂不会立即致命但丧失飞行能力。' },
  liver:    { name: '鸟肝', icon: '🟤', hpPct: 0.06, lethality: 0.50, desc: '鸟类肝脏分两叶，是代谢中枢。',
  fatalWound: '肝脏碎裂导致腹腔大出血。',
  medicalData: '鸟类肝脏代谢速率极高以支持飞行。猛禽肝脏含有较高的维生素A（以猎物肝脏为食的鸟类尤甚）。' },
  wing:     { name: '翼翅', icon: '🦅', hpPct: 0.12, lethality: 0.15, desc: '鸟类飞行器官。猛禽翅膀宽大可翱翔，游隼翅膀窄长利于高速俯冲（最快390km/h）。',
  fatalWound: '翅膀骨折丧失飞行能力。',
  medicalData: '鸟类翅膀由前肢特化：肱骨、桡骨、尺骨、腕骨、掌骨和指骨支撑飞羽。飞羽（remiges）由角蛋白构成。翅膀骨折在野外等同于死亡（无法捕食或逃避天敌）。' },
  claw:     { name: '利爪', icon: '🐾', hpPct: 0.06, lethality: 0.30, desc: '猛禽的杀伤武器。鹰爪握力可达体重10倍（角雕约50kg握力），可刺穿猎物内脏。',
  fatalWound: '利爪断裂丧失主要攻击能力。',
  medicalData: '猛禽后趾和前趾配合形成握持结构。角雕（Harpia harpyja）爪长13cm，握力达50kg/cm²。爪由角蛋白构成，持续生长。' },
  beak:     { name: '铁喙', icon: '🔶', hpPct: 0.05, lethality: 0.35, desc: '鸟类取食和攻击用的角质喙。猛禽喙带钩状弯折，可撕裂皮肉和折断骨骼。',
  fatalWound: '喙断裂导致无法取食。',
  medicalData: '鸟喙由角蛋白（keratin）包裹颌骨构成。秃鹫喙可撕裂厚实的兽皮。鹰喙上缘有突起（tomial tooth）用于切断猎物脊椎。喙终生生长，磨损后再生。' },
  spine:    { name: '脊柱', icon: '🦴', hpPct: 0.06, lethality: 0.60, desc: '鸟类脊柱轻量化但坚固，尾综骨（pygostyle）支撑尾羽用于飞行控制。',
  fatalWound: '脊髓断裂导致瘫痪。',
  medicalData: '鸟类颈椎节数多（天鹅可达25节），灵活度极高。胸椎融合（synsacrum）增加飞行时的刚性。尾综骨是尾椎融合体，支撑舵尾羽。' },
  crop:     { name: '嗉囊', icon: '🫄', hpPct: 0.04, lethality: 0.20, desc: '鸟类食道膨大部，用于暂时储存和软化食物。猛禽嗉囊可储存大量食物。',
  fatalWound: '嗉囊破裂导致食物残渣进入体腔。',
  medicalData: '嗉囊是食道的外突膨大部（非独立器官）。食物在嗉囊中被唾液和水分软化。猛禽可一次性吞下大量食物（秃鹫可食自身体重15%的食物）。' },
  body:     { name: '鸟躯', icon: '🐦', hpPct: 0.18, lethality: 0.35, desc: '鸟类躯体流线型，骨骼中空（充气骨）减轻重量，龙骨突（keel）附着强大胸肌驱动翅膀。',
  fatalWound: '躯干大面积损伤涉及多脏器。',
  medicalData: '鸟类骨骼含气囊延伸的中空结构（充气骨 pneumatic bones），重量轻但强度高（类似工程桁架结构）。胸骨龙骨突附着胸大肌（downstroke）和胸小肌（upstroke，通过滑轮状肱骨近端转向）。' },
  tail:     { name: '尾羽', icon: '🪶', hpPct: 0.06, lethality: 0.08, desc: '尾羽用于飞行转向和平衡。尾综骨支撑尾羽扇面。',
  fatalWound: '尾羽脱落导致飞行控制下降。',
  medicalData: '尾羽（rectrices）由尾综骨（pygostyle）支撑。尾羽用于飞行中的转向、减速和着陆制动。尾羽脱落可在下次换羽时再生。' },
  },
  quadruped_real: { // 真实四足哺乳动物——基于哺乳动物解剖学
  head:     { name: '头部', icon: '🐺', hpPct: 0.08, lethality: 0.88, desc: '头部含大脑、眼睛、耳朵和口鼻。犬科嗅觉灵敏度为人类10000-100000倍。',
  fatalWound: '颅骨碎裂致脑死亡。',
  medicalData: '哺乳动物头骨保护大脑。犬科动物口鼻部长，咬合力强（灰狼约400psi）。嗅觉受体数量：人类约600万，狼约3亿。' },
  heart:    { name: '心脏', icon: '❤️', hpPct: 0.05, lethality: 0.92, desc: '四腔心，泵血中枢。',
  fatalWound: '心脏停跳致循环衰竭。',
  medicalData: '哺乳动物四腔心，完全分离体循环和肺循环。大型犬心率70-120次/分。心脏停跳10秒内意识丧失。' },
  lung:     { name: '肺脏', icon: '🫁', hpPct: 0.07, lethality: 0.70, desc: '双肺，气体交换器官。',
  fatalWound: '张力性气胸致死。',
  medicalData: '犬肺约占体重2.5%。肺泡面积大（大型犬约50-70m²）。张力性气胸时纵隔移位阻断静脉回流，数分钟致命。' },
  liver:    { name: '肝脏', icon: '🟤', hpPct: 0.07, lethality: 0.60, desc: '最大内脏器官，解毒和代谢中枢。',
  fatalWound: '肝门静脉断裂致快速失血。',
  medicalData: '肝脏接收25%心输出量。肝破裂分I-VI级，III级以上死亡率显著上升。肝脏有强大再生能力（切除75%仍可再生）。' },
  spleen:   { name: '脾脏', icon: '💜', hpPct: 0.04, lethality: 0.50, desc: '血库器官，免疫功能。',
  fatalWound: '脾蒂断裂致快速失血。',
  medicalData: '脾脏储血约250ml（大型犬）。脾破裂为最常见腹部钝伤。脾切除后其他器官代偿免疫功能。' },
  kidney:   { name: '肾脏', icon: '🫘', hpPct: 0.04, lethality: 0.45, desc: '排泄和内分泌器官。',
  fatalWound: '肾蒂断裂致失血。',
  medicalData: '肾脏血流量占心输出量20-25%。单肾损伤通常不致命，双肾碎裂致尿毒症。' },
  brain:    { name: '大脑', icon: '🧠', hpPct: 0.04, lethality: 0.98, desc: '神经中枢。',
  fatalWound: '脑干损伤即刻死亡。',
  medicalData: '犬脑占体重0.6-1.0%。颅内压正常5-12mmHg，超20mmHg脑疝风险极高。' },
  spine:    { name: '脊柱', icon: '🦴', hpPct: 0.05, lethality: 0.55, desc: '中枢神经通道。',
  fatalWound: '高位颈髓损伤致呼吸停止。',
  medicalData: '脊髓损伤平面决定预后。胸腰段损伤致后肢瘫痪但不立即致命。' },
  stomach:  { name: '胃', icon: '🟢', hpPct: 0.04, lethality: 0.25, desc: '消化器官。',
  fatalWound: '胃穿孔继发腹膜炎。',
  medicalData: '犬胃pH 1-2。胃穿孔后6小时内可发生严重化学性腹膜炎。反刍动物有四个胃室。' },
  intestine:{ name: '肠道', icon: '〰️', hpPct: 0.05, lethality: 0.20, desc: '消化吸收器官。',
  fatalWound: '弥漫性腹膜炎、败血症。',
  medicalData: '肠内容物含10⁸-10¹¹ CFU/ml细菌。肠破裂感染性腹膜炎死亡率30-50%。' },
  body:     { name: '躯干', icon: '🐾', hpPct: 0.16, lethality: 0.30, desc: '容纳所有脏器。',
  fatalWound: '多脏器联合损伤。',
  medicalData: '躯干容纳胸腹腔所有脏器。多器官联合损伤死亡率指数级上升。' },
  limb:     { name: '四肢', icon: '🦴', hpPct: 0.12, lethality: 0.10, desc: '运动器官。',
  fatalWound: '肢体骨折。',
  medicalData: '四肢骨折非致命但影响运动能力。股动脉损伤可致命（失血500-1000ml/分钟）。' },
  tail:     { name: '尾巴', icon: '💫', hpPct: 0.05, lethality: 0.08, desc: '平衡和通讯器官。',
  fatalWound: '尾椎骨折。',
  medicalData: '尾巴为平衡器官。尾椎骨折可损伤马尾神经。' },
  fang:     { name: '獠牙', icon: '🦷', hpPct: 0.03, lethality: 0.35, desc: '食肉动物的攻击武器。',
  fatalWound: '犬齿断裂。',
  medicalData: '犬科犬齿咬合力约400psi（灰狼）。猫科犬齿更短但可精确穿刺颈椎间隙致猎物瘫痪。' },
  horn:     { name: '犄角', icon: '🐂', hpPct: 0.04, lethality: 0.25, desc: '有蹄类攻击和防御武器。',
  fatalWound: '角心断裂。',
  medicalData: '牛角由角心骨+角质鞘构成（与鹿角不同，鹿角每年脱落）。角用于种内争斗和防御。撞击力可达数百牛顿。' },
  },
};

export const MONSTER_RACE_DATA: any = {
  beast: {
  name: '兽族', icon: '🐺',
  cultivationBranches: ['炼体', '血气', '淬骨'],
  primaryDefense: 'physical',
  bodyStructure: 'quadruped',
  weaknessElements: ['金', '雷'],
  resistanceElements: ['土'],
  soulBranch: '兽魂',
  desc: '以炼体为主，肉身强横，血气旺盛',
  },
  dragon: {
  name: '龙族', icon: '🐲',
  cultivationBranches: ['炼体', '五行', '龙息', '淬骨', '经脉'],
  primaryDefense: 'elemental',
  bodyStructure: 'serpentine',
  weaknessElements: [],
  resistanceElements: ['火', '水', '金', '木', '土'],
  soulBranch: '龙魂',
  desc: '五行兼修，龙息为攻，龙鳞为守',
  },
  demon: {
  name: '魔族', icon: '👹',
  cultivationBranches: ['魔体', '魔元', '魔魂', '噬灵'],
  primaryDefense: 'dark',
  bodyStructure: 'humanoid',
  weaknessElements: ['光', '雷'],
  resistanceElements: ['暗', '冥'],
  soulBranch: '魔魂',
  desc: '以魔元护体，魔魂不灭',
  },
  spirit: {
  name: '灵族', icon: '👻',
  cultivationBranches: ['灵体', '灵元', '灵觉', '魂炼'],
  primaryDefense: 'spiritual',
  bodyStructure: 'ethereal',
  weaknessElements: ['雷', '火'],
  resistanceElements: ['水', '风'],
  soulBranch: '灵魄',
  desc: '灵体虚幻，灵魂攻击为主',
  },
  undead: {
  name: '不死族', icon: '💀',
  cultivationBranches: ['尸骨', '死气', '冥炼', '怨念'],
  primaryDefense: 'dark',
  bodyStructure: 'humanoid',
  weaknessElements: ['光', '火'],
  resistanceElements: ['暗', '毒'],
  soulBranch: '冥魂',
  desc: '以死气护体，不惧肉身损伤',
  },
  elemental: {
  name: '元素族', icon: '🔥',
  cultivationBranches: ['元素体', '元素共鸣', '淬炼'],
  primaryDefense: 'elemental',
  bodyStructure: 'elemental',
  weaknessElements: [],
  resistanceElements: [],
  soulBranch: '元素之灵',
  desc: '由纯粹元素构成，物理攻击效果减半',
  },
  plant: {
  name: '植族', icon: '🌳',
  cultivationBranches: ['灵根', '生机', '木行', '淬骨'],
  primaryDefense: 'physical',
  bodyStructure: 'plant',
  weaknessElements: ['火', '金'],
  resistanceElements: ['水', '土'],
  soulBranch: '草木之灵',
  desc: '以灵根为核心，生机旺盛，再生能力强',
  },
  insect: {
  name: '虫族', icon: '🐝',
  cultivationBranches: ['毒体', '甲壳', '蜂群意识'],
  primaryDefense: 'physical',
  bodyStructure: 'insectoid',
  weaknessElements: ['火'],
  resistanceElements: ['毒', '土'],
  soulBranch: '虫魂',
  desc: '甲壳坚硬，群体作战，多以毒攻为主',
  },
};

export const MONSTER_REALM_TIERS: any = [
  { name: '凡兽', level: 0, statMult: 1.0, bloodQiMult: 0.3, soulMult: 0.2, temperingMax: 5, desc: '未开灵智的野兽' },
  { name: '妖灵', level: 1, statMult: 1.5, bloodQiMult: 0.5, soulMult: 0.4, temperingMax: 10, desc: '初开灵智，能吞吐日月精华' },
  { name: '妖兵', level: 2, statMult: 2.2, bloodQiMult: 0.7, soulMult: 0.6, temperingMax: 15, desc: '凝聚妖丹，实力堪比筑基修士' },
  { name: '妖将', level: 3, statMult: 3.5, bloodQiMult: 1.0, soulMult: 0.8, temperingMax: 25, desc: '妖将之境，统御一方妖族' },
  { name: '妖王', level: 4, statMult: 5.0, bloodQiMult: 1.5, soulMult: 1.2, temperingMax: 40, desc: '妖王之尊，实力接近化神期' },
  { name: '妖皇', level: 5, statMult: 8.0, bloodQiMult: 2.0, soulMult: 1.8, temperingMax: 60, desc: '妖皇之境，可化形为人' },
  { name: '妖帝', level: 6, statMult: 12.0, bloodQiMult: 3.0, soulMult: 2.5, temperingMax: 80, desc: '妖帝降临，天地变色' },
  { name: '太古妖祖', level: 7, statMult: 20.0, bloodQiMult: 5.0, soulMult: 4.0, temperingMax: 100, desc: '太古妖族始祖，天道之下的至强存在' },
];

export const ENEMY_TYPES: any = [

  { name: '散修喽啰', icon: '🥷', hp: 30,  atk: 8,  speed: 0.8, loot: ['spirit_stone'],         exp: 15,  tier: 0, species: 'human' },
  { name: '宗门弟子', icon: '⚔️', hp: 60,  atk: 15, speed: 1.0, loot: ['spirit_stone','hp_pill_s'], exp: 30, tier: 1, species: 'human' },
  { name: '长老护法', icon: '🧙', hp: 120, atk: 25, speed: 0.7, loot: ['spirit_stone_m','hp_pill_m'], exp: 60, tier: 2, species: 'human' },
  { name: '魔道修士', icon: '😈', hp: 200, atk: 40, speed: 1.2, loot: ['exp_pill','spirit_stone_m'], exp: 100, tier: 3, species: 'human' },
  { name: '上古残魂', icon: '👻', hp: 400, atk: 60, speed: 0.5, loot: ['exp_pill','spirit_stone_l'], exp: 200, tier: 4, species: 'human' },
  { name: '灰狼',   icon: '🐺', hp: 25,  atk: 10, speed: 1.3, loot: ['beast_skin'],  exp: 12,  tier: 0, species: 'beast' },
  { name: '毒蛇',   icon: '🐍', hp: 20,  atk: 18, speed: 1.1, loot: ['poison_sac'],  exp: 18,  tier: 0, species: 'beast' },
  { name: '妖狐',   icon: '🦊', hp: 50,  atk: 20, speed: 1.4, loot: ['demon_core','herb'], exp: 35, tier: 1, species: 'beast' },
  { name: '石傀儡', icon: '🗿', hp: 150, atk: 30, speed: 0.4, loot: ['ore','spirit_stone'], exp: 50, tier: 2, species: 'beast' },
  { name: '蛟龙',   icon: '🐉', hp: 500, atk: 70, speed: 0.8, loot: ['dragon_core','spirit_stone_l'], exp: 250, tier: 4, species: 'beast' },

  { name: '灵明石猴', icon: '🐒', hp: 45,  atk: 14, speed: 1.5, loot: ['herb','spirit_stone'], exp: 25, tier: 1, species: 'beast', continent: 0 },
  { name: '仙鹤童子', icon: '🦢', hp: 80,  atk: 22, speed: 1.2, loot: ['herb','exp_pill'], exp: 40, tier: 2, species: 'beast', continent: 0 },

  { name: '沙魔',   icon: '🏜️', hp: 70,  atk: 16, speed: 0.9, loot: ['ore','spirit_stone'], exp: 28, tier: 1, species: 'beast', continent: 1 },
  { name: '蝎妖',   icon: '🦂', hp: 55,  atk: 25, speed: 1.0, loot: ['poison_sac','demon_core'], exp: 35, tier: 1, species: 'beast', continent: 1 },

  { name: '山贼头目', icon: '🏴', hp: 65,  atk: 18, speed: 0.9, loot: ['spirit_stone','hp_pill_s'], exp: 30, tier: 1, species: 'human', continent: 2 },
  { name: '水匪',   icon: '🚣', hp: 40,  atk: 15, speed: 1.1, loot: ['spirit_stone'], exp: 22, tier: 0, species: 'human', continent: 2 },

  { name: '冰魄精', icon: '🧊', hp: 90,  atk: 20, speed: 0.7, loot: ['exp_pill','spirit_stone_m'], exp: 45, tier: 2, species: 'beast', continent: 3 },
  { name: '雪域熊王', icon: '🐻‍❄️', hp: 180, atk: 35, speed: 0.5, loot: ['beast_skin','demon_core'], exp: 70, tier: 3, species: 'beast', continent: 3 },
];

export const RACE_LIFESPAN_MULT: any = {
  '人族':1, '先天人族':1.2,
  '天人':3, '金翅大鹏鸟':2.5,
  '阿修罗':1.5, '夜叉':1.3, '罗刹':1.4,
  '妖族·狐':2.5, '妖族·龙':5, '妖族·蛇':3, '妖族·虎':2,
  '妖族·鹤':4, '妖族·龟':8, '妖族·树':10, '妖族·石':15,
  '鬼族·幽魂':-1, '鬼族·厉鬼':-1, '鬼族·冥王':-1, '魂族':-1,
  '魔族·天魔':3, '魔族·心魔':2, '魔族·血魔':2.5, '邪族':1.8,

  '幽魂':-1, '怨灵':-1, '阴神':-1, '冥鬼':-1, '鬼王':-1,
};
