// 秘境塔 - 卡牌+怪物+药水+遗物
// 从 v0.35 迁移 - 共 5 个常量

export const SPIRE_CARDS: any = [

  {id:'palm_thunder',name:'掌心雷',type:'attack',cost:1,rarity:'common',desc:'造成{d}伤害',icon:'🖐️',damage:6,upgraded_damage:9},
  {id:'sword_qi',name:'剑气斩',type:'attack',cost:1,rarity:'common',desc:'造成{d}伤害',icon:'⚔️',damage:9,upgraded_damage:12},
  {id:'heaven_thunder',name:'天雷引',type:'attack',cost:2,rarity:'uncommon',desc:'造成{d}伤害×2次',icon:'⚡',damage:10,hits:2,upgraded_damage:13},
  {id:'flying_sword',name:'飞剑术',type:'attack',cost:1,rarity:'common',desc:'造成{d}伤害,抽1张牌',icon:'🗡️',damage:5,upgraded_damage:8,effects:[{type:'draw',value:1}]},
  {id:'earth_slash',name:'裂地斩',type:'attack',cost:2,rarity:'uncommon',desc:'造成{d}伤害',icon:'💥',damage:14,upgraded_damage:18},
  {id:'qi_blast',name:'元气弹',type:'attack',cost:3,rarity:'rare',desc:'造成{d}伤害',icon:'🌟',damage:20,upgraded_damage:26},
  {id:'wind_strike',name:'御风击',type:'attack',cost:0,rarity:'common',desc:'造成{d}伤害',icon:'🌪️',damage:4,upgraded_damage:6},
  {id:'purple_nine',name:'紫雷九击',type:'attack',cost:3,rarity:'rare',desc:'造成{d}伤害×3次',icon:'💜',damage:7,hits:3,upgraded_damage:9},
  {id:'soul_stab',name:'追魂刺',type:'attack',cost:1,rarity:'uncommon',desc:'造成{d}伤害,易伤敌人额外+4',icon:'👁️',damage:8,upgraded_damage:10,
  customCalc:(ctx)=>{let d=ctx.getDamage();if(ctx.target.vulnerable>0)d+=4;return d;}},
  {id:'frost_palm',name:'寒冰掌',type:'attack',cost:1,rarity:'common',desc:'造成{d}伤害,施加2层虚弱',icon:'❄️',damage:5,upgraded_damage:7,
  effects:[{type:'debuff',status:'weak',value:2}]},
  {id:'flame_technique',name:'烈焰术',type:'attack',cost:2,rarity:'uncommon',desc:'造成{d}伤害,施加3层灼烧',icon:'🔥',damage:12,upgraded_damage:15,
  effects:[{type:'debuff',status:'burn',value:3}]},
  {id:'armor_break',name:'破甲击',type:'attack',cost:1,rarity:'common',desc:'造成{d}伤害,施加2层易伤',icon:'🔨',damage:6,upgraded_damage:8,
  effects:[{type:'debuff',status:'vulnerable',value:2}]},
  {id:'demon_subdue',name:'伏魔斩',type:'attack',cost:2,rarity:'uncommon',desc:'造成{d}伤害,消耗敌方2层增益',icon:'👹',damage:10,upgraded_damage:13,
  effects:[{type:'dispel',value:2}]},
  {id:'dragon_roar',name:'龙吟击',type:'attack',cost:2,rarity:'rare',desc:'造成{d}伤害,施加1层虚弱+1层易伤',icon:'🐉',damage:12,upgraded_damage:16,
  effects:[{type:'debuff',status:'weak',value:1},{type:'debuff',status:'vulnerable',value:1}]},
  {id:'thunder_god',name:'雷神之怒',type:'attack',cost:3,rarity:'rare',desc:'造成{d}伤害,如果击杀敌人则恢复等量生命',icon:'⚡',damage:25,upgraded_damage:32,
  effects:[{type:'lifesteal'}]},
  {id:'bone_cutter',name:'断骨掌',type:'attack',cost:1,rarity:'common',desc:'造成{d}伤害,下次攻击+3',icon:'💀',damage:7,upgraded_damage:10,
  effects:[{type:'buff',status:'strength',value:1,duration:'combat'}]},
  {id:'shadow_stab',name:'暗影刺',type:'attack',cost:1,rarity:'uncommon',desc:'造成{d}伤害,每有一层虚弱额外+3',icon:'🌑',damage:4,upgraded_damage:6,
  customCalc:(ctx)=>{let d=ctx.getDamage();d+=(ctx.target.weak||0)*3;return d;}},
  {id:'blood_technique',name:'血煞掌',type:'attack',cost:0,rarity:'uncommon',desc:'失去3生命,造成{d}伤害',icon:'🩸',damage:11,upgraded_damage:15,
  effects:[{type:'selfDamage',value:3}]},
  {id:'heaven_earth',name:'天地同寿',type:'attack',cost:2,rarity:'rare',desc:'造成等同于已损失生命的伤害',icon:'☯️',damage:0,upgraded_damage:0,
  customCalc:(ctx)=>Math.max(0,ctx.player.maxHp-ctx.player.hp)},
  {id:'sword_rain',name:'万剑诀',type:'attack',cost:2,rarity:'rare',desc:'造成{d}伤害×4次',icon:'🌧️',damage:4,hits:4,upgraded_damage:5},
  {id:'void_slash',name:'虚空斩',type:'attack',cost:1,rarity:'uncommon',desc:'造成{d}伤害,无视格挡',icon:'🕳️',damage:7,upgraded_damage:10,
  effects:[{type:'piercing'}]},
  {id:'spirit_crush',name:'碎灵掌',type:'attack',cost:2,rarity:'uncommon',desc:'造成{d}伤害,移除目标等量格挡',icon:'💫',damage:10,upgraded_damage:14,
  effects:[{type:'blockBreak'}]},
  {id:'five_elements',name:'五行轮回',type:'attack',cost:1,rarity:'common',desc:'造成{d}伤害,随机施加1种debuff',icon:'🔄',damage:7,upgraded_damage:10,
  effects:[{type:'randomDebuff',value:2}]},
  {id:'moonlight',name:'月华斩',type:'attack',cost:1,rarity:'common',desc:'造成{d}伤害,抽2张牌然后弃1张',icon:'🌙',damage:6,upgraded_damage:9,
  effects:[{type:'draw',value:2},{type:'discard',value:1}]},
  {id:'sun_strike',name:'烈阳击',type:'attack',cost:2,rarity:'uncommon',desc:'造成{d}伤害,本回合攻击+2',icon:'☀️',damage:10,upgraded_damage:14,
  effects:[{type:'tempStrength',value:2}]},
  {id:'ghost_hand',name:'幽冥鬼手',type:'attack',cost:1,rarity:'uncommon',desc:'造成{d}伤害,获得等量格挡',icon:'👻',damage:5,upgraded_damage:8,
  effects:[{type:'blockFromDamage'}]},
  {id:'demon_flame',name:'魔焰焚天',type:'attack',cost:2,rarity:'rare',desc:'造成{d}伤害,施加5层灼烧',icon:'😈',damage:8,upgraded_damage:12,
  effects:[{type:'debuff',status:'burn',value:5}]},
  {id:'jade_sword',name:'碧玉剑诀',type:'attack',cost:1,rarity:'common',desc:'造成{d}伤害,如果满血则+6',icon:'💎',damage:6,upgraded_damage:8,
  customCalc:(ctx)=>{let d=ctx.getDamage();if(ctx.player.hp>=ctx.player.maxHp)d+=6;return d;}},
  {id:'spirit_arrow',name:'灵矢穿云',type:'attack',cost:1,rarity:'common',desc:'造成{d}伤害',icon:'🏹',damage:7,upgraded_damage:10},
  {id:'heavenly_sword',name:'天剑诀',type:'attack',cost:3,rarity:'rare',desc:'造成{d}伤害,消耗所有手牌,每消耗1张+4伤害',icon:'✨',damage:10,upgraded_damage:14,
  customCalc:(ctx)=>{let d=ctx.getDamage();d+=(ctx.handCount||0)*4;return d;}},
  {id:'qi_wave',name:'气波功',type:'attack',cost:1,rarity:'common',desc:'造成{d}伤害×2次',icon:'💨',damage:4,hits:2,upgraded_damage:6},
  {id:'demon_seal',name:'封魔印',type:'attack',cost:2,rarity:'uncommon',desc:'造成{d}伤害,敌人下回合跳过',icon:'📜',damage:8,upgraded_damage:12,
  effects:[{type:'skipTurn'}]},

  {id:'qi_shield',name:'护体罡气',type:'skill',cost:1,rarity:'common',desc:'获得{b}格挡',icon:'🛡️',block:5,upgraded_block:8},
  {id:'golden_bell',name:'金钟罩',type:'skill',cost:2,rarity:'uncommon',desc:'获得{b}格挡',icon:'🔔',block:12,upgraded_block:16},
  {id:'spirit_shield',name:'灵气盾',type:'skill',cost:1,rarity:'common',desc:'获得{b}格挡,抽1张牌',icon:'🔮',block:6,upgraded_block:9,
  effects:[{type:'draw',value:1}]},
  {id:'xuanwu_guard',name:'玄武护体',type:'skill',cost:3,rarity:'rare',desc:'获得{b}格挡',icon:'🐢',block:20,upgraded_block:26},
  {id:'shrink_earth',name:'缩地成寸',type:'skill',cost:1,rarity:'uncommon',desc:'获得{b}格挡,下次攻击+3',icon:'📏',block:5,upgraded_block:7,
  effects:[{type:'buff',status:'strength',value:3,duration:'once'}]},
  {id:'divine_step',name:'神行百变',type:'skill',cost:0,rarity:'common',desc:'获得{b}格挡,抽1张牌',icon:'💨',block:3,upgraded_block:5,
  effects:[{type:'draw',value:1}]},
  {id:'qiankun_throw',name:'乾坤一掷',type:'skill',cost:1,rarity:'uncommon',desc:'造成等同于格挡值的伤害',icon:'🎯',block:0,upgraded_block:0,
  customCalc:(ctx)=>ctx.player.block},
  {id:'steal_heaven',name:'偷天换日',type:'skill',cost:1,rarity:'uncommon',desc:'抽{v}张牌',icon:'🃏',effects:[{type:'draw',value:2}],upgraded_effects:[{type:'draw',value:3}]},
  {id:'gather_qi',name:'聚灵术',type:'skill',cost:1,rarity:'common',desc:'本回合+{v}灵力',icon:'🌀',effects:[{type:'energy',value:1}],upgraded_effects:[{type:'energy',value:2}]},
  {id:'soul_attack',name:'神魂攻击',type:'skill',cost:2,rarity:'rare',desc:'施加5层虚弱+5层易伤',icon:'👁️',
  effects:[{type:'debuff',status:'weak',value:5},{type:'debuff',status:'vulnerable',value:5}],upgraded_effects:[{type:'debuff',status:'weak',value:6},{type:'debuff',status:'vulnerable',value:6}]},
  {id:'iron_skin',name:'铁布衫',type:'skill',cost:1,rarity:'common',desc:'获得{b}格挡,获得2层护体',icon:'🪨',block:6,upgraded_block:9,
  effects:[{type:'buff',status:'artifact',value:2}]},
  {id:'cloud_step',name:'凌波微步',type:'skill',cost:1,rarity:'uncommon',desc:'获得{b}格挡,获得1层虚无',icon:'☁️',block:4,upgraded_block:6,
  effects:[{type:'buff',status:'intangible',value:1,duration:1}]},
  {id:'qi_absorb',name:'吸灵术',type:'skill',cost:1,rarity:'uncommon',desc:'获得敌方格挡值一半的格挡',icon:'🔄',block:0,upgraded_block:0,
  customCalc:(ctx)=>Math.floor(ctx.target.block/2)+5},
  {id:'second_wind',name:'回天术',type:'skill',cost:0,rarity:'uncommon',desc:'弃所有手牌,每弃1张获3格挡',icon:'♻️',block:0,upgraded_block:0,
  effects:[{type:'discardAll',blockPer:3}],upgraded_effects:[{type:'discardAll',blockPer:4}]},
  {id:'body_tempering',name:'淬体术',type:'skill',cost:1,rarity:'rare',desc:'获得等同于力量层数×3的格挡',icon:'💪',block:0,upgraded_block:0,
  customCalc:(ctx)=>(ctx.player.strength||0)*4+5},
  {id:'mental_clarity',name:'清心诀',type:'skill',cost:0,rarity:'common',desc:'移除自身所有debuff,抽1张牌',icon:'🧹',
  effects:[{type:'cleanse'},{type:'draw',value:1}]},
  {id:'earth_wall',name:'土墙术',type:'skill',cost:1,rarity:'common',desc:'获得{b}格挡,下回合+3格挡',icon:'🧱',block:7,upgraded_block:10,
  effects:[{type:'nextTurnBlock',value:3}]},
  {id:'double_qi',name:'双重灵盾',type:'skill',cost:2,rarity:'rare',desc:'格挡值翻倍',icon:'✖️',block:0,upgraded_block:0,
  effects:[{type:'doubleBlock'}]},
  {id:'spirit_siphon',name:'灵魂汲取',type:'skill',cost:1,rarity:'uncommon',desc:'造成{d}伤害,回复等量生命',icon:'💗',damage:5,upgraded_damage:8,
  effects:[{type:'lifesteal'}]},
  {id:'counter_stance',name:'反击架势',type:'skill',cost:1,rarity:'uncommon',desc:'获得{b}格挡,获得2层荆棘',icon:'↩️',block:5,upgraded_block:8,
  effects:[{type:'buff',status:'thorns',value:2}]},
  {id:'qi_burst',name:'灵气爆发',type:'skill',cost:0,rarity:'rare',desc:'本回合+2灵力,抽2张牌',icon:'💥',
  effects:[{type:'energy',value:2},{type:'draw',value:2}]},
  {id:'mirror_image',name:'镜花水月',type:'skill',cost:1,rarity:'uncommon',desc:'获得{b}格挡,下回合抽额外2张',icon:'🪞',block:4,upgraded_block:7,
  effects:[{type:'buff',status:'drawNextTurn',value:2}]},

  {id:'sword_will',name:'剑意',type:'power',cost:1,rarity:'uncommon',desc:'每回合开始获得{v}力量',icon:'⚔️',
  effects:[{type:'passiveBuff',status:'strength',value:1}],upgraded_effects:[{type:'passiveBuff',status:'strength',value:2}]},
  {id:'spirit_body',name:'灵体',type:'power',cost:1,rarity:'uncommon',desc:'每回合开始获得{v}格挡',icon:'✨',
  effects:[{type:'passiveBlock',value:3}],upgraded_effects:[{type:'passiveBlock',value:5}]},
  {id:'heaven_eye',name:'天眼通',type:'power',cost:1,rarity:'rare',desc:'可以看到敌人全部意图',icon:'👁️',
  effects:[{type:'seeIntent'}],upgraded_effects:[{type:'seeIntent'}],upgraded_cost:0},
  {id:'immortal_body',name:'不灭体',type:'power',cost:2,rarity:'rare',desc:'每回合回复{v}生命',icon:'💚',
  effects:[{type:'passiveRegen',value:2}],upgraded_effects:[{type:'passiveRegen',value:3}]},
  {id:'cloud_walk',name:'踏云步',type:'power',cost:1,rarity:'uncommon',desc:'每回合额外抽{v}张牌',icon:'☁️',
  effects:[{type:'passiveDraw',value:1}],upgraded_effects:[{type:'passiveDraw',value:1}],upgraded_cost:0},
  {id:'thorn_body',name:'荆棘之体',type:'power',cost:1,rarity:'uncommon',desc:'每回合开始获得{v}层荆棘',icon:'🌵',
  effects:[{type:'passiveBuff',status:'thorns',value:1}],upgraded_effects:[{type:'passiveBuff',status:'thorns',value:2}]},
  {id:'qi_armor',name:'灵气铠甲',type:'power',cost:2,rarity:'rare',desc:'每回合开始获得{v}格挡',icon:'🛡️',
  effects:[{type:'passiveBlock',value:6}],upgraded_effects:[{type:'passiveBlock',value:8}]},
  {id:'devour_soul',name:'噬魂',type:'power',cost:2,rarity:'rare',desc:'击杀敌人时回复{v}生命',icon:'👻',
  effects:[{type:'killHeal',value:5}],upgraded_effects:[{type:'killHeal',value:8}]},
  {id:'metal_body',name:'金刚不坏',type:'power',cost:2,rarity:'rare',desc:'每回合开始获得1层护体',icon:'🪨',
  effects:[{type:'passiveBuff',status:'artifact',value:1}]},
  {id:'demon_aura',name:'魔气缠身',type:'power',cost:1,rarity:'uncommon',desc:'敌人每回合开始受到1层灼烧',icon:'😈',
  effects:[{type:'enemyPassive',status:'burn',value:1}],upgraded_effects:[{type:'enemyPassive',status:'burn',value:2}]},
  {id:'life_convert',name:'生命转化',type:'power',cost:0,rarity:'rare',desc:'最大生命-10,每回合+2灵力',icon:'💔',
  effects:[{type:'maxHpTrade',value:-10,energy:2}],upgraded_effects:[{type:'maxHpTrade',value:-8,energy:2}]},
  {id:'dodge_master',name:'闪避大师',type:'power',cost:1,rarity:'uncommon',desc:'每回合开始获得{v}层虚无',icon:'💨',
  effects:[{type:'passiveBuff',status:'intangible',value:1,duration:1}],upgraded_effects:[{type:'passiveBuff',status:'intangible',value:1,duration:1}],upgraded_cost:0},
];

export const SPIRE_MONSTERS: any = {

  act1_normal:[
  {name:'妖狼',icon:'🐺',hp:42,atk:6,block:0,intents:[{type:'attack',value:6},{type:'attack',value:9},{type:'attack',value:6}]},
  {name:'毒蛇',icon:'🐍',hp:35,atk:8,block:0,intents:[{type:'attack',value:8},{type:'debuff',status:'poison',value:3},{type:'attack',value:6}]},
  {name:'石龟',icon:'🐢',hp:60,atk:4,block:0,intents:[{type:'block',value:8},{type:'attack',value:4},{type:'block',value:8},{type:'attack',value:12}]},
  {name:'妖蜂群',icon:'🐝',hp:28,atk:10,block:0,intents:[{type:'attack',value:3,hits:3},{type:'attack',value:5,hits:2},{type:'debuff',status:'weak',value:1}]},
  {name:'树妖',icon:'🌳',hp:50,atk:5,block:0,intents:[{type:'buff',status:'strength',value:1},{type:'attack',value:5},{type:'attack',value:8},{type:'block',value:6}]},
  {name:'幽魂',icon:'👻',hp:32,atk:7,block:0,intents:[{type:'attack',value:7},{type:'debuff',status:'weak',value:2},{type:'attack',value:7},{type:'buff',status:'intangible',value:1,duration:1}]},
  {name:'赤狐',icon:'🦊',hp:38,atk:8,block:0,intents:[{type:'attack',value:8},{type:'attack',value:5,hits:2},{type:'debuff',status:'vulnerable',value:2}]},
  {name:'黑熊',icon:'🐻',hp:55,atk:10,block:0,intents:[{type:'attack',value:10},{type:'buff',status:'strength',value:2},{type:'attack',value:14}]},
  ],
  act1_elite:[
  {name:'赤炎虎',icon:'🐅',hp:95,atk:12,block:0,intents:[{type:'attack',value:12},{type:'buff',status:'strength',value:2},{type:'attack',value:18},{type:'attack',value:12}]},
  {name:'碧眼蟾蜍',icon:'🐸',hp:75,atk:10,block:0,intents:[{type:'debuff',status:'poison',value:5},{type:'attack',value:10},{type:'debuff',status:'weak',value:3},{type:'attack',value:15}]},
  {name:'血蝠王',icon:'🦇',hp:68,atk:14,block:0,intents:[{type:'attack',value:14},{type:'attack',value:7,hits:2},{type:'heal',value:8},{type:'attack',value:20}]},
  ],
  act1_boss:{name:'九头蛇',icon:'🐍',hp:200,atk:15,block:0,intents:[
  {type:'attack',value:15},{type:'attack',value:8,hits:2},{type:'buff',status:'strength',value:3},
  {type:'attack',value:20},{type:'debuff',status:'poison',value:4},{type:'attack',value:12,hits:2}
  ],ascBuff:{hp:30,atk:2}},

  act2_normal:[
  {name:'魔化修士',icon:'🧛',hp:65,atk:12,block:5,intents:[{type:'attack',value:12},{type:'block',value:10},{type:'attack',value:16},{type:'debuff',status:'vulnerable',value:2}]},
  {name:'雷角兽',icon:'🐂',hp:80,atk:14,block:0,intents:[{type:'attack',value:14},{type:'attack',value:20},{type:'debuff',status:'weak',value:2},{type:'attack',value:10,hits:2}]},
  {name:'冰霜巨人',icon:'🗿',hp:100,atk:10,block:8,intents:[{type:'block',value:15},{type:'attack',value:10},{type:'attack',value:18},{type:'block',value:10}]},
  {name:'影魔',icon:'👤',hp:55,atk:15,block:0,intents:[{type:'attack',value:15},{type:'buff',status:'intangible',value:1,duration:1},{type:'attack',value:20},{type:'debuff',status:'weak',value:3}]},
  {name:'火焰蜥蜴',icon:'🦎',hp:70,atk:11,block:0,intents:[{type:'attack',value:11},{type:'debuff',status:'burn',value:4},{type:'attack',value:16},{type:'attack',value:8,hits:2}]},
  {name:'石像鬼',icon:'🗿',hp:90,atk:8,block:10,intents:[{type:'block',value:12},{type:'attack',value:8,hits:2},{type:'attack',value:20},{type:'block',value:8}]},
  {name:'邪修',icon:'🧙',hp:50,atk:13,block:0,intents:[{type:'debuff',status:'vulnerable',value:3},{type:'attack',value:13},{type:'buff',status:'strength',value:2},{type:'attack',value:18}]},
  {name:'毒沼蛙',icon:'🐸',hp:60,atk:9,block:0,intents:[{type:'debuff',status:'poison',value:4},{type:'attack',value:9},{type:'attack',value:14},{type:'debuff',status:'poison',value:6}]},
  ],
  act2_elite:[
  {name:'天魔将',icon:'😈',hp:130,atk:18,block:5,intents:[{type:'attack',value:18},{type:'buff',status:'strength',value:3},{type:'attack',value:12,hits:2},{type:'attack',value:25}]},
  {name:'冥界守卫',icon:'⚰️',hp:150,atk:12,block:10,intents:[{type:'block',value:15},{type:'attack',value:12,hits:2},{type:'debuff',status:'vulnerable',value:3},{type:'attack',value:30}]},
  {name:'远古石魔',icon:'🧱',hp:160,atk:10,block:12,intents:[{type:'block',value:20},{type:'attack',value:10,hits:3},{type:'attack',value:25},{type:'block',value:15}]},
  ],
  act2_boss:{name:'混沌兽',icon:'🌀',hp:320,atk:20,block:0,intents:[
  {type:'attack',value:20},{type:'attack',value:12,hits:2},{type:'buff',status:'strength',value:3},{type:'debuff',status:'vulnerable',value:3},
  {type:'attack',value:30},{type:'block',value:15},{type:'attack',value:15,hits:3}
  ],ascBuff:{hp:50,atk:3}},

  act3_normal:[
  {name:'虚空魔虫',icon:'🐛',hp:90,atk:16,block:0,intents:[{type:'attack',value:16},{type:'debuff',status:'poison',value:5},{type:'attack',value:22},{type:'attack',value:10,hits:2}]},
  {name:'远古龙蜥',icon:'🐲',hp:120,atk:14,block:8,intents:[{type:'attack',value:14},{type:'block',value:15},{type:'attack',value:24},{type:'buff',status:'strength',value:3}]},
  {name:'幽冥狼群',icon:'🐺',hp:75,atk:18,block:0,intents:[{type:'attack',value:6,hits:3},{type:'attack',value:10,hits:2},{type:'debuff',status:'weak',value:3},{type:'attack',value:25}]},
  {name:'天雷兽',icon:'⚡',hp:95,atk:20,block:0,intents:[{type:'attack',value:20},{type:'attack',value:8,hits:3},{type:'debuff',status:'vulnerable',value:3},{type:'attack',value:28}]},
  {name:'炎魔',icon:'👹',hp:110,atk:15,block:5,intents:[{type:'attack',value:15},{type:'debuff',status:'burn',value:5},{type:'attack',value:22},{type:'attack',value:12,hits:2}]},
  {name:'幻影修者',icon:'🥷',hp:70,atk:22,block:0,intents:[{type:'buff',status:'intangible',value:1,duration:1},{type:'attack',value:22},{type:'attack',value:30},{type:'debuff',status:'weak',value:4}]},
  {name:'腐化灵兽',icon:'🦅',hp:85,atk:17,block:0,intents:[{type:'attack',value:17},{type:'debuff',status:'poison',value:6},{type:'attack',value:12,hits:2},{type:'heal',value:15}]},
  {name:'深渊触手',icon:'🐙',hp:100,atk:13,block:0,intents:[{type:'attack',value:6,hits:3},{type:'attack',value:18},{type:'debuff',status:'vulnerable',value:4},{type:'attack',value:10,hits:3}]},
  ],
  act3_elite:[
  {name:'虚空之主',icon:'🌌',hp:180,atk:22,block:10,intents:[{type:'attack',value:22},{type:'buff',status:'strength',value:4},{type:'attack',value:15,hits:2},{type:'attack',value:35}]},
  {name:'天魔将·暗',icon:'😈',hp:200,atk:18,block:15,intents:[{type:'block',value:20},{type:'attack',value:18,hits:2},{type:'debuff',status:'weak',value:4},{type:'attack',value:40}]},
  {name:'远古巨蟒',icon:'🐍',hp:220,atk:16,block:8,intents:[{type:'attack',value:16},{type:'debuff',status:'poison',value:8},{type:'attack',value:28},{type:'attack',value:10,hits:3}]},
  ],
  act3_boss:{name:'天道残影',icon:'☯️',hp:450,atk:25,block:0,intents:[
  {type:'attack',value:25},{type:'attack',value:15,hits:2},{type:'buff',status:'strength',value:4},{type:'debuff',status:'vulnerable',value:4},
  {type:'attack',value:40},{type:'block',value:25},{type:'attack',value:20,hits:3},{type:'buff',status:'intangible',value:1,duration:1},
  ],ascBuff:{hp:80,atk:5}},
};

export const SPIRE_POTIONS: any = [
  {id:'heal_pill',name:'回灵丹',icon:'💊',desc:'回复20生命',rarity:'common',effect:{type:'heal',value:20},combat:true},
  {id:'qi_pill',name:'聚气散',icon:'🧪',desc:'本回合获得2灵力',rarity:'common',effect:{type:'energy',value:2},combat:true},
  {id:'shield_pill',name:'护体丹',icon:'🛡️',desc:'获得12格挡',rarity:'common',effect:{type:'block',value:12},combat:true},
  {id:'rage_pill',name:'狂暴丹',icon:'💪',desc:'本回合获得3力量',rarity:'uncommon',effect:{type:'tempBuff',status:'strength',value:3},combat:true},
  {id:'swift_pill',name:'疾风散',icon:'💨',desc:'本回合获得3敏捷',rarity:'uncommon',effect:{type:'tempBuff',status:'dexterity',value:3},combat:true},
  {id:'antidote',name:'解毒丹',icon:'🧹',desc:'移除自身所有debuff',rarity:'common',effect:{type:'cleanse'},combat:true},
  {id:'transform',name:'化形液',icon:'🔄',desc:'敌人跳过1回合',rarity:'rare',effect:{type:'skipTurn'},combat:true},
  {id:'poison_flask',name:'毒液瓶',icon:'☠️',desc:'施加8层中毒',rarity:'uncommon',effect:{type:'debuff',status:'poison',value:8},combat:true},
  {id:'fire_flask',name:'烈焰瓶',icon:'🔥',desc:'施加6层灼烧',rarity:'uncommon',effect:{type:'debuff',status:'burn',value:6},combat:true},
  {id:'elixir',name:'仙丹',icon:'✨',desc:'回复30%最大生命',rarity:'rare',effect:{type:'healPercent',value:0.3},combat:true},
  {id:'berserk_flask',name:'血怒液',icon:'🩸',desc:'本回合+3能量,失去5生命',rarity:'rare',effect:{type:'energyHP',energy:3,hp:5},combat:true},
  {id:'ancient_potion',name:'太古神水',icon:'🏺',desc:'获得3层护体',rarity:'rare',effect:{type:'buff',status:'artifact',value:3},combat:true},
  {id:'sight_potion',name:'天眼水',icon:'👁️',desc:'本回合显示敌人意图',rarity:'common',effect:{type:'seeIntent'},combat:true},
  {id:'draw_potion',name:'通灵液',icon:'📜',desc:'抽3张牌',rarity:'uncommon',effect:{type:'draw',value:3},combat:true},
  {id:'block_potion',name:'玄铁液',icon:'🪨',desc:'获得12格挡,获得1层荆棘',rarity:'uncommon',effect:{type:'block',value:12,buff:{status:'thorns',value:1}},combat:true},
  {id:'strength_potion',name:'元力液',icon:'⚔️',desc:'本场战斗+2力量',rarity:'rare',effect:{type:'buff',status:'strength',value:2},combat:true},
  {id:'dexterity_potion',name:'灵巧液',icon:'🦶',desc:'本场战斗+2敏捷',rarity:'rare',effect:{type:'buff',status:'dexterity',value:2},combat:true},
];

export const SPIRE_RELICS: any = [

  {id:'spirit_pearl',name:'聚灵珠',rarity:'common',icon:'🔮',desc:'战斗开始时获得1灵力',trigger:'combatStart',effect:{type:'energy',value:1}},
  {id:'jade_pendant',name:'护身玉佩',rarity:'common',icon:'💚',desc:'每场战斗开始获得3格挡',trigger:'combatStart',effect:{type:'block',value:3}},
  {id:'soul_wood',name:'养魂木',rarity:'common',icon:'🪵',desc:'每场战斗结束回复3生命',trigger:'combatEnd',effect:{type:'heal',value:3}},
  {id:'storage_bag',name:'储物袋',rarity:'common',icon:'👝',desc:'药水栏位+1',trigger:'passive',effect:{type:'potionSlots',value:1}},
  {id:'spirit_stone',name:'灵石袋',rarity:'common',icon:'💰',desc:'战斗胜利金币+25%',trigger:'combatEnd',effect:{type:'goldMult',value:0.25}},
  {id:'lucky_clover',name:'幸运草',rarity:'common',icon:'🍀',desc:'精英战斗后奖励多1个选择',trigger:'eliteReward',effect:{type:'extraCardChoice',value:1}},
  {id:'spirit_lantern',name:'灵灯',rarity:'common',icon:'🏮',desc:'每层开始时揭示3个节点',trigger:'floorStart',effect:{type:'reveal',value:3}},
  {id:'bone_flute',name:'骨笛',rarity:'common',icon:'🦴',desc:'战斗开始获得1层力量',trigger:'combatStart',effect:{type:'buff',status:'strength',value:1}},
  {id:'tea_cup',name:'灵茶杯',rarity:'common',icon:'🍵',desc:'休息处额外回复5生命',trigger:'rest',effect:{type:'bonusHeal',value:5}},
  {id:'crystal_ring',name:'水晶戒',rarity:'common',icon:'💍',desc:'每回合开始获得1格挡',trigger:'turnStart',effect:{type:'block',value:1}},

  {id:'herb_bag',name:'灵草袋',rarity:'uncommon',icon:'🌿',desc:'每经过3个非战斗节点获得1瓶回灵丹',trigger:'nodePass',effect:{type:'potionEvery',value:3,potion:'heal_pill'}},
  {id:'divine_boots',name:'神行靴',rarity:'uncommon',icon:'👢',desc:'每回合开始获得1敏捷',trigger:'turnStart',effect:{type:'buff',status:'dexterity',value:1}},
  {id:'heaven_mirror',name:'玄天镜',rarity:'uncommon',icon:'🪞',desc:'回合结束未受伤则抽1张牌',trigger:'turnEnd',effect:{type:'drawIfUnharmed',value:1}},
  {id:'divine_compass',name:'天机盘',rarity:'uncommon',icon:'🧭',desc:'战斗开始查看敌人全部意图',trigger:'combatStart',effect:{type:'seeAllIntent'}},
  {id:'five_flag',name:'五行旗',rarity:'uncommon',icon:'🚩',desc:'攻击牌额外造成2伤害',trigger:'passive',effect:{type:'damageBonus',value:2}},
  {id:'spirit_ring',name:'灵戒',rarity:'uncommon',icon:'💍',desc:'每回合+1能量上限',trigger:'passive',effect:{type:'maxEnergy',value:1}},
  {id:'moon_pendant',name:'月牙坠',rarity:'uncommon',icon:'🌙',desc:'每场战斗第一次攻击伤害翻倍',trigger:'firstAttack',effect:{type:'doubleDamage'}},
  {id:'blood_stone',name:'血晶石',rarity:'uncommon',icon:'🩸',desc:'击杀敌人时获得3格挡',trigger:'kill',effect:{type:'block',value:3}},
  {id:'ancient_seal',name:'上古封印',rarity:'uncommon',icon:'📜',desc:'Boss战斗开始施加3层虚弱',trigger:'bossStart',effect:{type:'debuff',status:'weak',value:3}},
  {id:'void_crystal',name:'虚空结晶',rarity:'uncommon',icon:'💎',desc:'每层开始恢复1点灵力上限(最高+3)',trigger:'floorStart',effect:{type:'maxEnergyStack',value:1,max:3}},
  {id:'thunder_bead',name:'天雷珠',rarity:'uncommon',icon:'⚡',desc:'每回合对所有敌人造成1伤害',trigger:'turnEnd',effect:{type:'aoe',value:1}},
  {id:'spirit_bell',name:'招魂铃',rarity:'uncommon',icon:'🔔',desc:'战斗开始抽额外1张牌',trigger:'combatStart',effect:{type:'draw',value:1}},

  {id:'nine_turn',name:'九转金丹',rarity:'boss',icon:'💊',desc:'Boss战开始时回满生命(仅限1次)',trigger:'bossStart',effect:{type:'fullHealOnce'}},
  {id:'void_ring',name:'虚空戒',rarity:'boss',icon:'💍',desc:'每回合+1灵力,最大生命-20',trigger:'passive',effect:{type:'maxHpTrade',value:-20,energy:1}},
  {id:'ancient_elixir',name:'万年灵液',rarity:'boss',icon:'🧪',desc:'每回合开始随机获得力量/敏捷/格挡各1',trigger:'turnStart',effect:{type:'randomBuff'}},
  {id:'dragon_heart',name:'龙心',rarity:'boss',icon:'❤️',desc:'最大生命+25,每回合回复2生命',trigger:'passive',effect:{type:'maxHpHeal',hp:25,regen:2}},
  {id:'emperor_seal',name:'天帝印',rarity:'boss',icon:'👑',desc:'每场战斗+2能量,但只能抽4张牌',trigger:'combatStart',effect:{type:'energyDraw',energy:2,draw:-1}},
  {id:'chaos_orb',name:'混沌珠',rarity:'boss',icon:'🌀',desc:'每3回合获得1层虚无',trigger:'turnStart',effect:{type:'everyN',n:3,buff:{status:'intangible',value:1,duration:1}}},
  {id:'yin_yang_jade',name:'阴阳玉',rarity:'boss',icon:'☯️',desc:'受到伤害时50%几率反弹等量伤害',trigger:'onHit',effect:{type:'reflect',chance:0.5}},
];

export const SPIRE_STARTER_DECK: any = [
  'palm_thunder','palm_thunder','palm_thunder','palm_thunder','palm_thunder',
  'sword_qi','sword_qi','sword_qi','sword_qi',
  'qi_shield','qi_shield','qi_shield','qi_shield','qi_shield',
  'spirit_shield','spirit_shield',
];
