// 功法技法 - 5系+熟练度+SVG动画
// 从 v0.35 迁移 - 共 13 个常量

export const TECHNIQUES: any = [
{id:'basic',name:'吐纳术',type:'基础',grade:'凡级',desc:'最基础的修炼法门',bonus:0,reqRealm:0,element:'无'},
{id:'qingyun',name:'青云诀',type:'法修',grade:'黄级',desc:'正道基础功法，修炼稳健',bonus:.15,reqRealm:3,element:'木'},
{id:'lieyan',name:'烈焰功',type:'法修',grade:'黄级',desc:'火系功法，攻击附带灼烧',bonus:.12,reqRealm:3,element:'火',combatBonus:{atk:.1}},
{id:'tijue',name:'金刚体诀',type:'体修',grade:'黄级',desc:'体修入门功法，强化肉身',bonus:.1,reqRealm:5,element:'金',combatBonus:{def:.15,hp:.1}},
{id:'xuanyin',name:'玄阴真经',type:'法修',grade:'玄级',desc:'阴属性功法',bonus:.25,reqRealm:10,element:'水'},
{id:'leiting',name:'雷霆诀',type:'法修',grade:'玄级',desc:'雷系功法',bonus:.2,reqRealm:12,element:'雷',combatBonus:{atk:.2}},
{id:'hunluo',name:'混罗天功',type:'法修',grade:'地级',desc:'远古功法，全面增幅',bonus:.35,reqRealm:15,element:'无'},
{id:'taiyi',name:'太乙真功',type:'法修',grade:'地级',desc:'道家正统功法',bonus:.4,reqRealm:18,element:'金'},
{id:'jiange',name:'剑罡诀',type:'剑修',grade:'地级',desc:'以剑入道，攻伐无双',bonus:.3,reqRealm:18,element:'金',combatBonus:{atk:.35}},
{id:'bahuang',name:'八荒六合功',type:'法修',grade:'天级',desc:'上古大能所创',bonus:.55,reqRealm:22,element:'无'},
{id:'huntian',name:'混沌天经',type:'法修',grade:'仙级',desc:'混沌之力，超越五行',bonus:.7,reqRealm:30,element:'混沌'},
{id:'taigu',name:'太古神王诀',type:'体修',grade:'仙级',desc:'太古体修至高功法',bonus:.6,reqRealm:34,element:'无',combatBonus:{hp:.5,def:.3}},
{id:'xuanming',name:'玄冥大道',type:'法修',grade:'神级',desc:'大道之法',bonus:1.0,reqRealm:40,element:'无'},
{id:'hongmeng',name:'鸿蒙造化功',type:'法修',grade:'至高',desc:'鸿蒙初开时的无上功法',bonus:1.5,reqRealm:45,element:'混沌'},
];

export const COMBAT_TECHNIQUES_BENYUAN: any = [
  {id:'by_001',name:'开天辟地',category:'本源',element:'chaos',dmgType:'true_damage',grade:'至高',realmReq:50,baseDmg:1000,desc:'开天辟地之威，万物归始',effect:'destroy_all',svgAnim:'chaos'},
  {id:'by_002',name:'万道归一',category:'本源',element:'void',dmgType:'true_damage',grade:'至高',realmReq:52,baseDmg:1200,desc:'万道归一，大道至简',effect:'void_annihilate',svgAnim:'void'},
  {id:'by_003',name:'混沌之拳',category:'本源',element:'chaos',dmgType:'true_damage',grade:'至高',realmReq:55,baseDmg:1500,desc:'混沌初开的力量凝聚于一拳',effect:'chaos_destroy',svgAnim:'chaos'},
  {id:'by_004',name:'时间长河',category:'本源',element:'void',dmgType:'true_damage',grade:'至高',realmReq:58,baseDmg:1800,desc:'以时间长河冲刷一切',effect:'time_erode',svgAnim:'void'},
  {id:'by_005',name:'大道无形',category:'本源',element:'chaos',dmgType:'true_damage',grade:'至高',realmReq:60,baseDmg:2000,desc:'大道无形，生育天地',effect:'genesis',svgAnim:'chaos'},

  {id:'by_006',name:'一念花开',category:'本源',element:'chaos',dmgType:'true_damage',grade:'至高',realmReq:55,baseDmg:1500,desc:'一念之间，花开世界生灭',effect:'create_destroy',svgAnim:'chaos'},
  {id:'by_007',name:'万法归宗',category:'本源',element:'void',dmgType:'true_damage',grade:'至高',realmReq:58,baseDmg:1800,desc:'万法归于一宗',effect:'all_tech_fusion',svgAnim:'void'},
  {id:'by_008',name:'超脱之拳',category:'本源',element:'chaos',dmgType:'true_damage',grade:'至高',realmReq:60,baseDmg:2100,desc:'超脱大道之拳',effect:'transcendence',svgAnim:'chaos'},
  {id:'by_009',name:'天道崩塌',category:'本源',element:'void',dmgType:'true_damage',grade:'至高',realmReq:62,baseDmg:2400,desc:'天道崩塌，法则破碎',effect:'law_destruction',svgAnim:'void'},
  {id:'by_010',name:'不朽之光',category:'本源',element:'light',dmgType:'true_damage',grade:'至高',realmReq:58,baseDmg:1900,desc:'不朽之光照耀万界',effect:'immortal_light',svgAnim:'light'},
  {id:'by_011',name:'永恒黑暗',category:'本源',element:'dark',dmgType:'true_damage',grade:'至高',realmReq:58,baseDmg:1850,desc:'永恒黑暗吞噬一切',effect:'eternal_darkness',svgAnim:'dark'},
  {id:'by_012',name:'起源之火',category:'本源',element:'fire',dmgType:'true_damage',grade:'至高',realmReq:56,baseDmg:1600,desc:'起源之火焚烧万界',effect:'origin_flame',svgAnim:'fire'},
  {id:'by_013',name:'终末之冰',category:'本源',element:'ice',dmgType:'true_damage',grade:'至高',realmReq:56,baseDmg:1550,desc:'终末之冰冻结永恒',effect:'ending_frost',svgAnim:'ice'},
  {id:'by_014',name:'破界之力',category:'本源',element:'void',dmgType:'true_damage',grade:'至高',realmReq:62,baseDmg:2500,desc:'破开一界之力',effect:'world_break',svgAnim:'void'},
  {id:'by_015',name:'无中生有',category:'本源',element:'chaos',dmgType:'true_damage',grade:'至高',realmReq:60,baseDmg:2050,desc:'无中生有，创造万物',effect:'creation',svgAnim:'chaos'},
];

export const COMBAT_TECHNIQUES_DAOFA: any = [
  {id:'df_001',name:'一气化三清',category:'道法',element:'chaos',dmgType:'true_damage',grade:'仙级',realmReq:40,baseDmg:400,desc:'一气化出三具分身同时攻击',effect:'triple_hit_true',svgAnim:'chaos'},
  {id:'df_002',name:'因果律·斩',category:'因果',element:'void',dmgType:'true_damage',grade:'神级',realmReq:44,baseDmg:550,desc:'斩断因果，必中之击',effect:'guaranteed_hit_void',svgAnim:'void'},
  {id:'df_003',name:'大命运术',category:'命运',element:'chaos',dmgType:'true_damage',grade:'神级',realmReq:46,baseDmg:600,desc:'操控命运之力，改写战局',effect:'random_debuff_all',svgAnim:'chaos'},
  {id:'df_004',name:'时空裂斩',category:'时空',element:'void',dmgType:'true_damage',grade:'神级',realmReq:45,baseDmg:580,desc:'撕裂时空的斩击',effect:'time_skip',svgAnim:'void'},
  {id:'df_005',name:'天地同寿',category:'道法',element:'light',dmgType:'true_damage',grade:'神级',realmReq:48,baseDmg:700,desc:'以自身寿元换取绝强一击',effect:'sacrifice_hp_50',svgAnim:'light'},

  {id:'df_006',name:'大道至简',category:'道法',element:'chaos',dmgType:'true_damage',grade:'神级',realmReq:45,baseDmg:580,desc:'大道至简，一击破万法',effect:'simplify_destroy',svgAnim:'chaos'},
  {id:'df_007',name:'天道酬勤',category:'天道',element:'light',dmgType:'true_damage',grade:'神级',realmReq:46,baseDmg:620,desc:'天道酬勤，越战越勇',effect:'stacking_dmg_up',svgAnim:'light'},
  {id:'df_008',name:'阴阳逆转',category:'道法',element:'chaos',dmgType:'true_damage',grade:'神级',realmReq:47,baseDmg:660,desc:'逆转阴阳，颠倒乾坤',effect:'reverse_hp',svgAnim:'chaos'},
  {id:'df_009',name:'五行归一',category:'五行',element:'chaos',dmgType:'true_damage',grade:'神级',realmReq:46,baseDmg:600,desc:'五行归一，万法合一',effect:'all_element_fusion',svgAnim:'chaos'},
  {id:'df_010',name:'虚空湮灭',category:'虚空',element:'void',dmgType:'true_damage',grade:'神级',realmReq:48,baseDmg:720,desc:'虚空湮灭，万物归虚',effect:'void_total_annihilate',svgAnim:'void'},
  {id:'df_011',name:'命运之轮',category:'命运',element:'chaos',dmgType:'true_damage',grade:'神级',realmReq:49,baseDmg:750,desc:'转动命运之轮',effect:'random_fate',svgAnim:'chaos'},
  {id:'df_012',name:'因果律·逆转',category:'因果',element:'void',dmgType:'true_damage',grade:'神级',realmReq:49,baseDmg:740,desc:'逆转因果，反果为因',effect:'reverse_causality',svgAnim:'void'},
  {id:'df_013',name:'时间长河·截断',category:'时空',element:'void',dmgType:'true_damage',grade:'神级',realmReq:48,baseDmg:700,desc:'截断时间长河',effect:'time_cutoff',svgAnim:'void'},
  {id:'df_014',name:'空间折叠',category:'时空',element:'void',dmgType:'true_damage',grade:'神级',realmReq:47,baseDmg:640,desc:'折叠空间压缩敌人',effect:'space_compress',svgAnim:'void'},
  {id:'df_015',name:'造化之手',category:'造化',element:'chaos',dmgType:'true_damage',grade:'神级',realmReq:49,baseDmg:760,desc:'造化之手重塑天地',effect:'reshape_reality',svgAnim:'chaos'},
  {id:'df_016',name:'太初之力',category:'太初',element:'chaos',dmgType:'true_damage',grade:'神级',realmReq:48,baseDmg:710,desc:'太初之力，万物之始',effect:'primordial_power',svgAnim:'chaos'},
  {id:'df_017',name:'混沌之拳·真',category:'混沌',element:'chaos',dmgType:'true_damage',grade:'神级',realmReq:49,baseDmg:770,desc:'真正的混沌之拳',effect:'chaos_true_destroy',svgAnim:'chaos'},
  {id:'df_018',name:'无极而太极',category:'无极',element:'chaos',dmgType:'true_damage',grade:'神级',realmReq:47,baseDmg:650,desc:'无极生太极，太极归无极',effect:'yin_yang_cycle',svgAnim:'chaos'},
  {id:'df_019',name:'大道五十·天衍四九',category:'天道',element:'void',dmgType:'true_damage',grade:'神级',realmReq:49,baseDmg:780,desc:'天衍四九，遁去其一',effect:'heaven_dodge',svgAnim:'void'},
  {id:'df_020',name:'万物归虚',category:'道法',element:'void',dmgType:'true_damage',grade:'神级',realmReq:49,baseDmg:790,desc:'万物终将归于虚无',effect:'return_to_void',svgAnim:'void'},
];

export const COMBAT_TECHNIQUES_LINGJI: any = [
  {id:'lj_001',name:'紫霄神雷',category:'雷法',element:'lightning',dmgType:'elemental',grade:'玄级',realmReq:10,baseDmg:45,desc:'引动天雷轰击敌人',effect:'paralyze_15',svgAnim:'lightning'},
  {id:'lj_002',name:'九天玄刹',category:'雷法',element:'lightning',dmgType:'elemental',grade:'地级',realmReq:12,baseDmg:55,desc:'九天之上的玄雷',effect:'paralyze_20_stun_10',svgAnim:'lightning'},
  {id:'lj_003',name:'五行遁法·火遁',category:'遁法',element:'fire',dmgType:'elemental',grade:'玄级',realmReq:10,baseDmg:40,desc:'火遁攻击，从火焰中现身突袭',effect:'burn_15',svgAnim:'fire'},
  {id:'lj_004',name:'五行遁法·水遁',category:'遁法',element:'water',dmgType:'elemental',grade:'玄级',realmReq:10,baseDmg:38,desc:'水遁攻击，融入水中突袭',effect:'freeze_15',svgAnim:'water'},
  {id:'lj_005',name:'五行遁法·土遁',category:'遁法',element:'earth',dmgType:'elemental',grade:'玄级',realmReq:11,baseDmg:42,desc:'土遁攻击，从地下突袭',effect:'stun_15',svgAnim:'earth'},
  {id:'lj_006',name:'飞剑术·御剑',category:'飞剑',element:'metal',dmgType:'physical_sharp',grade:'玄级',realmReq:10,baseDmg:48,desc:'御使飞剑远程攻击',effect:'crit_up_15',svgAnim:'metal'},
  {id:'lj_007',name:'万剑诀',category:'飞剑',element:'metal',dmgType:'physical_sharp',grade:'地级',realmReq:14,baseDmg:60,desc:'万剑齐发，覆盖攻击',effect:'aoe_crit_10',svgAnim:'metal'},
  {id:'lj_008',name:'冰封千里',category:'冰法',element:'ice',dmgType:'elemental',grade:'地级',realmReq:13,baseDmg:52,desc:'大范围冰冻攻击',effect:'freeze_25_aoe',svgAnim:'ice'},
  {id:'lj_009',name:'三昧真火',category:'火法',element:'fire',dmgType:'elemental',grade:'地级',realmReq:14,baseDmg:58,desc:'道家真火，焚烧万物',effect:'burn_20_true',svgAnim:'fire'},
  {id:'lj_010',name:'春风化雨',category:'木法',element:'wood',dmgType:'elemental',grade:'玄级',realmReq:10,baseDmg:30,desc:'木系恢复法术',effect:'heal_20',svgAnim:'wood'},
  {id:'lj_011',name:'荆棘缠绕',category:'木法',element:'wood',dmgType:'elemental',grade:'玄级',realmReq:11,baseDmg:35,desc:'荆棘束缚敌人',effect:'bind_20',svgAnim:'wood'},
  {id:'lj_012',name:'金光咒',category:'金法',element:'metal',dmgType:'elemental',grade:'玄级',realmReq:12,baseDmg:44,desc:'金光护体兼攻击',effect:'def_up_15_atk_up_10',svgAnim:'metal'},
  {id:'lj_013',name:'风刃千杀',category:'风法',element:'wind',dmgType:'elemental',grade:'地级',realmReq:13,baseDmg:50,desc:'千道风刃切割',effect:'multi_hit_5_bleed_8',svgAnim:'wind'},
  {id:'lj_014',name:'地裂术',category:'土法',element:'earth',dmgType:'elemental',grade:'玄级',realmReq:11,baseDmg:42,desc:'大地开裂吞噬敌人',effect:'stun_20',svgAnim:'earth'},
  {id:'lj_015',name:'雷光拳',category:'拳法',element:'lightning',dmgType:'mixed',grade:'玄级',realmReq:10,baseDmg:46,desc:'拳上附雷，麻痹敌人',effect:'paralyze_15',svgAnim:'lightning'},

  {id:'lj_016',name:'天火流星',category:'火法',element:'fire',dmgType:'elemental',grade:'地级',realmReq:14,baseDmg:55,desc:'召唤天外流星火雨',effect:'burn_20_aoe',svgAnim:'fire'},
  {id:'lj_017',name:'玄冰盾',category:'冰法',element:'ice',dmgType:'elemental',grade:'玄级',realmReq:10,baseDmg:0,desc:'冰盾护体，冻结近身敌人',effect:'def_up_20_freeze_15',svgAnim:'ice'},
  {id:'lj_018',name:'青木回春',category:'木法',element:'wood',dmgType:'elemental',grade:'玄级',realmReq:10,baseDmg:25,desc:'木系灵力恢复气血',effect:'heal_30',svgAnim:'wood'},
  {id:'lj_019',name:'庚金剑阵',category:'飞剑',element:'metal',dmgType:'physical_sharp',grade:'地级',realmReq:15,baseDmg:58,desc:'庚金之气化为剑阵困杀',effect:'aoe_crit_15',svgAnim:'metal'},
  {id:'lj_020',name:'雷遁术',category:'遁法',element:'lightning',dmgType:'elemental',grade:'玄级',realmReq:12,baseDmg:40,desc:'以雷电之力瞬移攻击',effect:'speed_up_30',svgAnim:'lightning'},
  {id:'lj_021',name:'水龙吟',category:'水法',element:'water',dmgType:'elemental',grade:'地级',realmReq:14,baseDmg:52,desc:'水龙咆哮，席卷一切',effect:'freeze_15_aoe',svgAnim:'water'},
  {id:'lj_022',name:'厚土之墙',category:'土法',element:'earth',dmgType:'elemental',grade:'玄级',realmReq:11,baseDmg:0,desc:'召唤土墙防御',effect:'def_up_30',svgAnim:'earth'},
  {id:'lj_023',name:'碧落风斩',category:'风法',element:'wind',dmgType:'elemental',grade:'地级',realmReq:15,baseDmg:56,desc:'碧落之风化为无形斩击',effect:'multi_hit_3_bleed_10',svgAnim:'wind'},
  {id:'lj_024',name:'暗影突袭',category:'暗法',element:'dark',dmgType:'soul',grade:'玄级',realmReq:13,baseDmg:44,desc:'潜入暗影突袭敌人神魂',effect:'crit_up_20',svgAnim:'dark'},
  {id:'lj_025',name:'金光护体诀',category:'金法',element:'metal',dmgType:'elemental',grade:'玄级',realmReq:10,baseDmg:0,desc:'金光护体，刀枪不入',effect:'def_up_25',svgAnim:'metal'},
  {id:'lj_026',name:'紫霄神雷',category:'雷法',element:'lightning',dmgType:'elemental',grade:'地级',realmReq:16,baseDmg:62,desc:'紫霄神雷从天而降',effect:'paralyze_25_true',svgAnim:'lightning'},
  {id:'lj_027',name:'炎阳焚天诀',category:'火法',element:'fire',dmgType:'elemental',grade:'地级',realmReq:16,baseDmg:60,desc:'炎阳之力焚烧天地',effect:'burn_25_true',svgAnim:'fire'},
  {id:'lj_028',name:'冰魄寒光',category:'冰法',element:'ice',dmgType:'elemental',grade:'地级',realmReq:15,baseDmg:54,desc:'冰魄寒光冻结万物',effect:'freeze_25',svgAnim:'ice'},
  {id:'lj_029',name:'枯木逢春',category:'木法',element:'wood',dmgType:'elemental',grade:'地级',realmReq:14,baseDmg:30,desc:'枯木逢春，起死回生',effect:'heal_50_revive',svgAnim:'wood'},
  {id:'lj_030',name:'碎岳击',category:'土法',element:'earth',dmgType:'elemental',grade:'地级',realmReq:15,baseDmg:58,desc:'碎岳之力，山崩地裂',effect:'stun_25_aoe',svgAnim:'earth'},
  {id:'lj_031',name:'万剑诀·灵',category:'飞剑',element:'metal',dmgType:'physical_sharp',grade:'地级',realmReq:17,baseDmg:65,desc:'万剑齐发的灵技版本',effect:'aoe_penetrate_30',svgAnim:'metal'},
  {id:'lj_032',name:'暴风之眼',category:'风法',element:'wind',dmgType:'elemental',grade:'地级',realmReq:16,baseDmg:58,desc:'暴风眼中心的毁灭力量',effect:'aoe_multi_5',svgAnim:'wind'},
  {id:'lj_033',name:'暗月斩',category:'暗法',element:'dark',dmgType:'soul',grade:'地级',realmReq:17,baseDmg:60,desc:'暗月之力斩断灵魂',effect:'soul_dmg_20',svgAnim:'dark'},
  {id:'lj_034',name:'光耀审判',category:'光法',element:'light',dmgType:'elemental',grade:'地级',realmReq:17,baseDmg:62,desc:'圣光审判一切邪恶',effect:'purify_burn_15',svgAnim:'light'},
  {id:'lj_035',name:'毒龙钻',category:'毒法',element:'poison',dmgType:'mixed',grade:'地级',realmReq:14,baseDmg:48,desc:'毒龙旋转钻入敌人体内',effect:'poison_20_penetrate',svgAnim:'poison'},
  {id:'lj_036',name:'血祭·噬灵',category:'血法',element:'blood',dmgType:'mixed',grade:'地级',realmReq:16,baseDmg:50,desc:'以血祭之力吞噬敌人灵力',effect:'lifesteal_25_mp_steal_15',svgAnim:'blood'},
  {id:'lj_037',name:'幻影千重',category:'幻术',element:'dark',dmgType:'soul',grade:'地级',realmReq:15,baseDmg:42,desc:'制造千重幻影迷惑敌人',effect:'confuse_30_dodge_20',svgAnim:'dark'},
  {id:'lj_038',name:'九天玄刹',category:'雷法',element:'lightning',dmgType:'elemental',grade:'地级',realmReq:18,baseDmg:68,desc:'九天之上的玄雷',effect:'paralyze_20_stun_15',svgAnim:'lightning'},
  {id:'lj_039',name:'太乙分光剑',category:'飞剑',element:'light',dmgType:'physical_sharp',grade:'地级',realmReq:18,baseDmg:66,desc:'太乙之光化为万千剑影',effect:'multi_hit_6',svgAnim:'light'},
  {id:'lj_040',name:'混沌漩涡',category:'五行',element:'chaos',dmgType:'elemental',grade:'地级',realmReq:19,baseDmg:70,desc:'混沌之力形成吞噬漩涡',effect:'random_debuff',svgAnim:'chaos'},
  {id:'lj_041',name:'灵鹤展翅',category:'风法',element:'wind',dmgType:'elemental',grade:'玄级',realmReq:12,baseDmg:38,desc:'灵鹤展翅带动风刃',effect:'speed_up_15',svgAnim:'wind'},
  {id:'lj_042',name:'寒冰掌',category:'冰法',element:'ice',dmgType:'mixed',grade:'玄级',realmReq:11,baseDmg:40,desc:'寒冰掌力冻结经脉',effect:'freeze_15_atk_down',svgAnim:'ice'},
  {id:'lj_043',name:'烈焰刀',category:'火法',element:'fire',dmgType:'mixed',grade:'玄级',realmReq:12,baseDmg:44,desc:'烈焰化为刀刃劈斩',effect:'burn_12',svgAnim:'fire'},
  {id:'lj_044',name:'千藤缠绕',category:'木法',element:'wood',dmgType:'elemental',grade:'玄级',realmReq:13,baseDmg:36,desc:'万千藤蔓束缚敌人',effect:'bind_25',svgAnim:'wood'},
  {id:'lj_045',name:'金刚不坏体',category:'金法',element:'metal',dmgType:'elemental',grade:'玄级',realmReq:13,baseDmg:0,desc:'金刚之体，百毒不侵',effect:'def_up_30_immunity',svgAnim:'metal'},
  {id:'lj_046',name:'黄泉引路',category:'暗法',element:'dark',dmgType:'soul',grade:'地级',realmReq:19,baseDmg:64,desc:'引渡敌人入黄泉',effect:'soul_dmg_25_curse',svgAnim:'dark'},
  {id:'lj_047',name:'霓裳羽衣舞',category:'幻术',element:'wind',dmgType:'soul',grade:'地级',realmReq:18,baseDmg:46,desc:'优美的舞蹈暗藏杀机',effect:'confuse_25_dodge_25',svgAnim:'wind'},
  {id:'lj_048',name:'五行封印',category:'五行',element:'chaos',dmgType:'elemental',grade:'地级',realmReq:19,baseDmg:55,desc:'五行之力封印敌人灵力',effect:'mp_seal_30',svgAnim:'chaos'},
  {id:'lj_049',name:'天罡北斗阵',category:'雷法',element:'lightning',dmgType:'elemental',grade:'地级',realmReq:18,baseDmg:65,desc:'北斗七星之力降下雷罚',effect:'aoe_paralyze_20',svgAnim:'lightning'},
  {id:'lj_050',name:'虚空裂缝',category:'虚空',element:'void',dmgType:'true_damage',grade:'地级',realmReq:19,baseDmg:72,desc:'撕裂虚空的裂缝吞噬一切',effect:'void_pierce',svgAnim:'void'},
];

export const COMBAT_TECHNIQUES_SHENTONG: any = [
  {id:'st_001',name:'天地法相',category:'法相',element:'chaos',dmgType:'true_damage',grade:'地级',realmReq:20,baseDmg:80,desc:'凝聚天地法相，以巨力碾压',effect:'aoe_stun_20',svgAnim:'chaos'},
  {id:'st_002',name:'万剑归宗',category:'剑道',element:'metal',dmgType:'physical_sharp',grade:'天级',realmReq:24,baseDmg:120,desc:'万千飞剑合一，归于一击',effect:'penetrate_50_crit_30',svgAnim:'metal'},
  {id:'st_003',name:'焚天煮海',category:'火道',element:'fire',dmgType:'elemental',grade:'天级',realmReq:25,baseDmg:130,desc:'焚尽苍天，煮沸大海',effect:'burn_30_aoe',svgAnim:'fire'},
  {id:'st_004',name:'冰河世纪',category:'冰道',element:'ice',dmgType:'elemental',grade:'天级',realmReq:24,baseDmg:115,desc:'冰封千里，万物冻结',effect:'freeze_30_aoe',svgAnim:'ice'},
  {id:'st_005',name:'天劫雷罚',category:'雷道',element:'lightning',dmgType:'elemental',grade:'天级',realmReq:26,baseDmg:140,desc:'引动天劫之力惩罚敌人',effect:'paralyze_30_true',svgAnim:'lightning'},
  {id:'st_006',name:'虚空大手印',category:'虚空',element:'void',dmgType:'true_damage',grade:'天级',realmReq:27,baseDmg:150,desc:'虚空之力凝聚的大手印',effect:'void_shatter',svgAnim:'void'},
  {id:'st_007',name:'五行轮转',category:'五行',element:'chaos',dmgType:'elemental',grade:'地级',realmReq:20,baseDmg:85,desc:'五行之力轮转攻击',effect:'random_element',svgAnim:'chaos'},
  {id:'st_008',name:'大日如来掌',category:'佛道',element:'light',dmgType:'mixed',grade:'天级',realmReq:25,baseDmg:125,desc:'佛门至高掌法，净化一切',effect:'purify_burn_20',svgAnim:'light'},
  {id:'st_009',name:'天魔解体',category:'魔道',element:'dark',dmgType:'true_damage',grade:'天级',realmReq:28,baseDmg:180,desc:'自损八百伤敌一千',effect:'self_dmg_30',svgAnim:'dark'},
  {id:'st_010',name:'移花接木',category:'奇术',element:'wood',dmgType:'soul',grade:'地级',realmReq:22,baseDmg:60,desc:'转移伤害给敌人',effect:'reflect_30',svgAnim:'wood'},

  {id:'st_011',name:'一剑破万法',category:'剑道',element:'metal',dmgType:'physical_sharp',grade:'天级',realmReq:24,baseDmg:125,desc:'以一剑之力破尽万法',effect:'penetrate_60_true',svgAnim:'metal'},
  {id:'st_012',name:'雷帝降世',category:'雷道',element:'lightning',dmgType:'elemental',grade:'天级',realmReq:26,baseDmg:145,desc:'雷帝法相降临人间',effect:'paralyze_35_aoe_true',svgAnim:'lightning'},
  {id:'st_013',name:'九幽冥火',category:'火道',element:'dark',dmgType:'elemental',grade:'天级',realmReq:25,baseDmg:135,desc:'九幽地狱的冥火',effect:'burn_35_soul_dmg',svgAnim:'dark'},
  {id:'st_014',name:'冰封万里',category:'冰道',element:'ice',dmgType:'elemental',grade:'天级',realmReq:25,baseDmg:128,desc:'冰封万里，时空凝滞',effect:'freeze_40_time_slow',svgAnim:'ice'},
  {id:'st_015',name:'山河社稷印',category:'土道',element:'earth',dmgType:'true_damage',grade:'天级',realmReq:27,baseDmg:155,desc:'以山河之力镇压',effect:'stun_40_crush',svgAnim:'earth'},
  {id:'st_016',name:'风神怒',category:'风道',element:'wind',dmgType:'elemental',grade:'天级',realmReq:26,baseDmg:140,desc:'风神之怒，天翻地覆',effect:'aoe_multi_8_bleed_15',svgAnim:'wind'},
  {id:'st_017',name:'生死轮',category:'佛道',element:'light',dmgType:'soul',grade:'天级',realmReq:28,baseDmg:160,desc:'掌中生死轮转',effect:'lifesteal_40',svgAnim:'light'},
  {id:'st_018',name:'吞天魔功',category:'魔道',element:'dark',dmgType:'true_damage',grade:'天级',realmReq:28,baseDmg:170,desc:'吞噬天地之力为己用',effect:'mp_steal_40_atk_up_20',svgAnim:'dark'},
  {id:'st_019',name:'星辰变',category:'虚空',element:'void',dmgType:'true_damage',grade:'天级',realmReq:29,baseDmg:175,desc:'星辰之力改天换地',effect:'void_annihilate',svgAnim:'void'},
  {id:'st_020',name:'血海魔莲',category:'血道',element:'blood',dmgType:'mixed',grade:'天级',realmReq:27,baseDmg:145,desc:'血海中盛开的魔莲',effect:'lifesteal_35_aoe',svgAnim:'blood'},
  {id:'st_021',name:'六道轮回',category:'佛道',element:'chaos',dmgType:'soul',grade:'天级',realmReq:29,baseDmg:180,desc:'将敌人打入六道轮回',effect:'soul_shatter_curse',svgAnim:'chaos'},
  {id:'st_022',name:'太虚神拳',category:'拳道',element:'void',dmgType:'true_damage',grade:'天级',realmReq:28,baseDmg:165,desc:'太虚之力凝聚于拳',effect:'void_pierce_stun_25',svgAnim:'void'},
  {id:'st_023',name:'万毒噬心',category:'毒道',element:'poison',dmgType:'mixed',grade:'天级',realmReq:25,baseDmg:120,desc:'万种毒物噬咬心脏',effect:'poison_35_true',svgAnim:'poison'},
  {id:'st_024',name:'因果一击',category:'因果',element:'void',dmgType:'true_damage',grade:'天级',realmReq:29,baseDmg:190,desc:'斩断因果的必中一击',effect:'guaranteed_hit',svgAnim:'void'},
  {id:'st_025',name:'青帝木皇功',category:'木道',element:'wood',dmgType:'elemental',grade:'天级',realmReq:26,baseDmg:130,desc:'青帝之力，生生不息',effect:'heal_40_regen_30',svgAnim:'wood'},
  {id:'st_026',name:'白帝金皇斩',category:'金道',element:'metal',dmgType:'physical_sharp',grade:'天级',realmReq:26,baseDmg:148,desc:'白帝之斩，无物不破',effect:'armor_break_50_crit_25',svgAnim:'metal'},
  {id:'st_027',name:'黑帝水皇拳',category:'水道',element:'water',dmgType:'elemental',grade:'天级',realmReq:26,baseDmg:135,desc:'黑帝之拳，滔天巨浪',effect:'freeze_30_aoe_crush',svgAnim:'water'},
  {id:'st_028',name:'赤帝火皇指',category:'火道',element:'fire',dmgType:'elemental',grade:'天级',realmReq:26,baseDmg:142,desc:'赤帝之指，焚天煮海',effect:'burn_35_penetrate',svgAnim:'fire'},
  {id:'st_029',name:'黄帝土皇掌',category:'土道',element:'earth',dmgType:'true_damage',grade:'天级',realmReq:26,baseDmg:138,desc:'黄帝之掌，镇压山河',effect:'stun_35_crush_aoe',svgAnim:'earth'},
  {id:'st_030',name:'三头六臂',category:'法相',element:'chaos',dmgType:'mixed',grade:'天级',realmReq:27,baseDmg:150,desc:'法相三头六臂同时攻击',effect:'triple_hit',svgAnim:'chaos'},
  {id:'st_031',name:'天魔乱舞',category:'魔道',element:'dark',dmgType:'soul',grade:'地级',realmReq:22,baseDmg:90,desc:'天魔之舞扰乱心智',effect:'confuse_30_aoe',svgAnim:'dark'},
  {id:'st_032',name:'雷神之锤',category:'雷道',element:'lightning',dmgType:'elemental',grade:'地级',realmReq:23,baseDmg:100,desc:'雷神之锤轰然落下',effect:'paralyze_25_stun_20',svgAnim:'lightning'},
  {id:'st_033',name:'天火三玄变',category:'火道',element:'fire',dmgType:'elemental',grade:'地级',realmReq:22,baseDmg:95,desc:'三重天火叠加爆发',effect:'burn_20_x3',svgAnim:'fire'},
  {id:'st_034',name:'三千雷动',category:'雷道',element:'lightning',dmgType:'elemental',grade:'地级',realmReq:23,baseDmg:98,desc:'三千道雷电同时劈下',effect:'aoe_paralyze_20_multi_8',svgAnim:'lightning'},
  {id:'st_035',name:'大荒囚天指',category:'虚空',element:'void',dmgType:'true_damage',grade:'天级',realmReq:29,baseDmg:185,desc:'大荒之力囚禁天地',effect:'void_seal',svgAnim:'void'},
  {id:'st_036',name:'黄泉碧落',category:'暗道',element:'dark',dmgType:'soul',grade:'天级',realmReq:28,baseDmg:160,desc:'黄泉碧落无所遁形',effect:'soul_dmg_30_curse_20',svgAnim:'dark'},
  {id:'st_037',name:'破天拳',category:'拳道',element:'chaos',dmgType:'true_damage',grade:'天级',realmReq:27,baseDmg:155,desc:'一拳破天',effect:'true_crit_30',svgAnim:'chaos'},
  {id:'st_038',name:'剑二十三',category:'剑道',element:'none',dmgType:'physical_sharp',grade:'天级',realmReq:28,baseDmg:165,desc:'超越时空的剑法',effect:'time_stop_crit_40',svgAnim:'physical_sharp'},
  {id:'st_039',name:'万佛朝宗',category:'佛道',element:'light',dmgType:'soul',grade:'天级',realmReq:29,baseDmg:170,desc:'万佛之力汇聚一击',effect:'purify_true_aoe',svgAnim:'light'},
  {id:'st_040',name:'灭世天火',category:'火道',element:'fire',dmgType:'elemental',grade:'天级',realmReq:29,baseDmg:180,desc:'灭世级天火降临',effect:'burn_45_true_aoe',svgAnim:'fire'},
];

export const COMBAT_TECHNIQUES_WUJI: any = [

  {id:'wj_fist_01',name:'基础拳法',category:'拳法',element:'none',dmgType:'physical_blunt',grade:'凡级',realmReq:0,baseDmg:8,desc:'最基础的拳击，以拳面击打',svgAnim:'physical_blunt'},
  {id:'wj_fist_02',name:'冲拳',category:'拳法',element:'none',dmgType:'physical_blunt',grade:'凡级',realmReq:0,baseDmg:10,desc:'直线冲拳，快速有力',svgAnim:'physical_blunt'},
  {id:'wj_fist_03',name:'崩拳',category:'拳法',element:'earth',dmgType:'physical_blunt',grade:'凡级',realmReq:1,baseDmg:12,desc:'五行拳之一，以崩劲破敌',effect:'stun_10',svgAnim:'earth'},
  {id:'wj_fist_04',name:'炮拳',category:'拳法',element:'fire',dmgType:'mixed',grade:'凡级',realmReq:2,baseDmg:14,desc:'五行拳之一，如炮弹般轰出',effect:'burn_5',svgAnim:'fire'},
  {id:'wj_fist_05',name:'横拳',category:'拳法',element:'earth',dmgType:'physical_blunt',grade:'凡级',realmReq:1,baseDmg:11,desc:'五行拳之一，横击侧身',svgAnim:'physical_blunt'},
  {id:'wj_fist_06',name:'劈拳',category:'拳法',element:'metal',dmgType:'physical_sharp',grade:'黄级',realmReq:3,baseDmg:18,desc:'五行拳之一，如斧劈物',svgAnim:'metal'},
  {id:'wj_fist_07',name:'钻拳',category:'拳法',element:'water',dmgType:'physical_pierce',grade:'黄级',realmReq:3,baseDmg:16,desc:'五行拳之一，螺旋穿透',effect:'penetrate_15',svgAnim:'water'},
  {id:'wj_fist_08',name:'通背拳',category:'拳法',element:'none',dmgType:'physical_blunt',grade:'黄级',realmReq:4,baseDmg:20,desc:'通背发力，臂如长鞭',svgAnim:'physical_blunt'},
  {id:'wj_fist_09',name:'八极拳',category:'拳法',element:'earth',dmgType:'physical_blunt',grade:'黄级',realmReq:5,baseDmg:24,desc:'刚猛暴烈，近身贴靠',effect:'stun_15',svgAnim:'earth'},
  {id:'wj_fist_10',name:'形意拳·虎形',category:'拳法',element:'none',dmgType:'physical_blunt',grade:'玄级',realmReq:6,baseDmg:28,desc:'模拟猛虎扑击，刚猛无匹',svgAnim:'physical_blunt'},
  {id:'wj_fist_11',name:'形意拳·龙形',category:'拳法',element:'water',dmgType:'mixed',grade:'玄级',realmReq:7,baseDmg:32,desc:'模拟神龙游走，变化莫测',effect:'dodge_down_10',svgAnim:'water'},
  {id:'wj_fist_12',name:'太极拳',category:'拳法',element:'water',dmgType:'physical_blunt',grade:'玄级',realmReq:8,baseDmg:22,desc:'以柔克刚，四两拨千斤',effect:'counter_20',svgAnim:'water'},
  {id:'wj_fist_13',name:'降龙十八掌',category:'拳法',element:'fire',dmgType:'mixed',grade:'地级',realmReq:9,baseDmg:40,desc:'至刚至猛的掌法，每掌附带龙形气劲',effect:'burn_10_stun_10',svgAnim:'fire'},
  {id:'wj_fist_14',name:'铁砂掌',category:'掌法',element:'poison',dmgType:'mixed',grade:'黄级',realmReq:4,baseDmg:19,desc:'铁砂淬炼之掌，附带微量毒素',effect:'poison_3',svgAnim:'poison'},
  {id:'wj_fist_15',name:'如来神掌',category:'掌法',element:'light',dmgType:'mixed',grade:'地级',realmReq:9,baseDmg:45,desc:'佛门至高掌法，蕴含无上佛力',effect:'purify',svgAnim:'light'},

  {id:'wj_sword_01',name:'基础剑法',category:'剑法',element:'none',dmgType:'physical_sharp',grade:'凡级',realmReq:0,baseDmg:10,desc:'最基本的剑术劈砍',svgAnim:'physical_sharp'},
  {id:'wj_sword_02',name:'快剑',category:'剑法',element:'none',dmgType:'physical_sharp',grade:'凡级',realmReq:1,baseDmg:12,desc:'快速连续刺击',svgAnim:'physical_sharp'},
  {id:'wj_sword_03',name:'清风剑法',category:'剑法',element:'wind',dmgType:'physical_sharp',grade:'黄级',realmReq:3,baseDmg:16,desc:'如清风拂面，暗藏杀机',effect:'bleed_5',svgAnim:'wind'},
  {id:'wj_sword_04',name:'烈焰剑法',category:'剑法',element:'fire',dmgType:'mixed',grade:'黄级',realmReq:4,baseDmg:20,desc:'剑身附火，灼烧敌人',effect:'burn_8',svgAnim:'fire'},
  {id:'wj_sword_05',name:'寒冰剑法',category:'剑法',element:'ice',dmgType:'mixed',grade:'黄级',realmReq:4,baseDmg:18,desc:'剑气凛寒，冻结敌人',effect:'freeze_10',svgAnim:'ice'},
  {id:'wj_sword_06',name:'回风落雁剑',category:'剑法',element:'wind',dmgType:'physical_sharp',grade:'玄级',realmReq:6,baseDmg:26,desc:'剑势如风，连环攻击',effect:'multi_hit_2',svgAnim:'wind'},
  {id:'wj_sword_07',name:'夺命连环三仙剑',category:'剑法',element:'none',dmgType:'physical_pierce',grade:'玄级',realmReq:7,baseDmg:30,desc:'连环三剑，剑剑夺命',effect:'bleed_10',svgAnim:'physical_pierce'},
  {id:'wj_sword_08',name:'玄铁剑法',category:'剑法',element:'earth',dmgType:'physical_sharp',grade:'玄级',realmReq:7,baseDmg:28,desc:'重剑无锋，大巧不工',effect:'armor_break_15',svgAnim:'earth'},
  {id:'wj_sword_09',name:'独孤九剑',category:'剑法',element:'none',dmgType:'physical_sharp',grade:'地级',realmReq:9,baseDmg:38,desc:'破尽天下武学，无招胜有招',effect:'crit_up_25',svgAnim:'physical_sharp'},
  {id:'wj_sword_10',name:'太极剑法',category:'剑法',element:'water',dmgType:'physical_sharp',grade:'玄级',realmReq:8,baseDmg:24,desc:'以慢打快，绵绵不绝',effect:'counter_15',svgAnim:'water'},
  {id:'wj_sword_11',name:'辟邪剑法',category:'剑法',element:'dark',dmgType:'physical_sharp',grade:'玄级',realmReq:8,baseDmg:32,desc:'诡异极速，防不胜防',effect:'speed_up_20',svgAnim:'dark'},
  {id:'wj_sword_12',name:'两仪剑法',category:'剑法',element:'chaos',dmgType:'mixed',grade:'地级',realmReq:9,baseDmg:36,desc:'阴阳互济，刚柔并施',effect:'chaos_hit',svgAnim:'chaos'},
  {id:'wj_sword_13',name:'一字电剑',category:'剑法',element:'lightning',dmgType:'mixed',grade:'黄级',realmReq:5,baseDmg:22,desc:'闪电般的一刺',effect:'paralyze_10',svgAnim:'lightning'},
  {id:'wj_sword_14',name:'柔云剑法',category:'剑法',element:'water',dmgType:'physical_sharp',grade:'黄级',realmReq:3,baseDmg:15,desc:'剑如流水，柔中带刚',svgAnim:'water'},
  {id:'wj_sword_15',name:'万花剑法',category:'剑法',element:'wood',dmgType:'physical_sharp',grade:'玄级',realmReq:6,baseDmg:24,desc:'剑花朵朵，绚丽杀机',effect:'multi_hit_3',svgAnim:'wood'},

  {id:'wj_blade_01',name:'基础刀法',category:'刀法',element:'none',dmgType:'physical_sharp',grade:'凡级',realmReq:0,baseDmg:11,desc:'大开大合的基础劈砍',svgAnim:'physical_sharp'},
  {id:'wj_blade_02',name:'五虎断门刀',category:'刀法',element:'none',dmgType:'physical_sharp',grade:'黄级',realmReq:3,baseDmg:18,desc:'五式连环，虎虎生风',effect:'bleed_5',svgAnim:'physical_sharp'},
  {id:'wj_blade_03',name:'燃木刀法',category:'刀法',element:'fire',dmgType:'mixed',grade:'黄级',realmReq:4,baseDmg:20,desc:'刀身燃火，焚尽一切',effect:'burn_10',svgAnim:'fire'},
  {id:'wj_blade_04',name:'血刀刀法',category:'刀法',element:'blood',dmgType:'mixed',grade:'玄级',realmReq:6,baseDmg:26,desc:'以血祭刀，越战越勇',effect:'lifesteal_15',svgAnim:'blood'},
  {id:'wj_blade_05',name:'狂风刀法',category:'刀法',element:'wind',dmgType:'physical_sharp',grade:'玄级',realmReq:7,baseDmg:28,desc:'刀势如狂风暴雨',effect:'multi_hit_2',svgAnim:'wind'},
  {id:'wj_blade_06',name:'胡家刀法',category:'刀法',element:'ice',dmgType:'mixed',grade:'玄级',realmReq:7,baseDmg:26,desc:'寒冰刀气，冷冽刺骨',effect:'freeze_10',svgAnim:'ice'},
  {id:'wj_blade_07',name:'天龙八斩',category:'刀法',element:'fire',dmgType:'physical_sharp',grade:'地级',realmReq:9,baseDmg:38,desc:'八式连斩，势不可挡',effect:'bleed_15_burn_8',svgAnim:'fire'},
  {id:'wj_blade_08',name:'八卦刀',category:'刀法',element:'earth',dmgType:'physical_sharp',grade:'黄级',realmReq:5,baseDmg:22,desc:'八卦步法配合刀术',svgAnim:'earth'},
  {id:'wj_blade_09',name:'慈悲刀法',category:'刀法',element:'light',dmgType:'physical_sharp',grade:'玄级',realmReq:8,baseDmg:24,desc:'佛门刀法，降妖伏魔',effect:'purify',svgAnim:'light'},
  {id:'wj_blade_10',name:'断岳刀',category:'刀法',element:'earth',dmgType:'physical_sharp',grade:'玄级',realmReq:8,baseDmg:30,desc:'一刀断岳，厚重无比',effect:'armor_break_20',svgAnim:'earth'},
  {id:'wj_blade_11',name:'修罗刀法',category:'刀法',element:'dark',dmgType:'mixed',grade:'地级',realmReq:9,baseDmg:36,desc:'修罗杀道，以杀证道',effect:'bleed_15',svgAnim:'dark'},
  {id:'wj_blade_12',name:'庖丁解牛刀',category:'刀法',element:'none',dmgType:'physical_sharp',grade:'黄级',realmReq:4,baseDmg:16,desc:'精准切割弱点',effect:'crit_up_15',svgAnim:'physical_sharp'},

  {id:'wj_spear_01',name:'基础枪法',category:'枪法',element:'none',dmgType:'physical_pierce',grade:'凡级',realmReq:0,baseDmg:10,desc:'直线穿刺攻击',svgAnim:'physical_pierce'},
  {id:'wj_spear_02',name:'杨家枪法',category:'枪法',element:'none',dmgType:'physical_pierce',grade:'黄级',realmReq:3,baseDmg:18,desc:'杨家将传世枪法',effect:'penetrate_20',svgAnim:'physical_pierce'},
  {id:'wj_spear_03',name:'暴雨梨花枪',category:'枪法',element:'water',dmgType:'physical_pierce',grade:'玄级',realmReq:6,baseDmg:26,desc:'如暴雨般密集的刺击',effect:'multi_hit_3',svgAnim:'water'},
  {id:'wj_spear_04',name:'燎原百击',category:'枪法',element:'fire',dmgType:'mixed',grade:'玄级',realmReq:7,baseDmg:30,desc:'燎原之火般的百连击',effect:'burn_8_multi_3',svgAnim:'fire'},
  {id:'wj_spear_05',name:'盘龙枪',category:'枪法',element:'earth',dmgType:'physical_pierce',grade:'黄级',realmReq:4,baseDmg:20,desc:'如盘龙般旋转变幻',svgAnim:'earth'},
  {id:'wj_spear_06',name:'蛇矛十三刺',category:'枪法',element:'poison',dmgType:'mixed',grade:'玄级',realmReq:7,baseDmg:28,desc:'如毒蛇般的十三连刺',effect:'poison_5',svgAnim:'poison'},
  {id:'wj_spear_07',name:'霸王枪',category:'枪法',element:'earth',dmgType:'physical_pierce',grade:'地级',realmReq:9,baseDmg:38,desc:'西楚霸王的绝世枪法',effect:'stun_20',svgAnim:'earth'},
  {id:'wj_spear_08',name:'百鸟朝凤枪',category:'枪法',element:'wind',dmgType:'physical_pierce',grade:'玄级',realmReq:8,baseDmg:32,desc:'百鸟齐鸣般的连环刺',effect:'multi_hit_4',svgAnim:'wind'},
  {id:'wj_spear_09',name:'寒冰枪诀',category:'枪法',element:'ice',dmgType:'mixed',grade:'黄级',realmReq:5,baseDmg:22,desc:'冰属性附着枪尖',effect:'freeze_10',svgAnim:'ice'},
  {id:'wj_spear_10',name:'破甲锥',category:'枪法',element:'metal',dmgType:'physical_pierce',grade:'黄级',realmReq:4,baseDmg:19,desc:'专破铠甲防御',effect:'armor_break_25',svgAnim:'metal'},

  {id:'wj_finger_01',name:'一阳指',category:'指法',element:'light',dmgType:'physical_pierce',grade:'玄级',realmReq:6,baseDmg:24,desc:'以指代剑，光劲透体',effect:'penetrate_30',svgAnim:'light'},
  {id:'wj_finger_02',name:'六脉神剑',category:'指法',element:'metal',dmgType:'mixed',grade:'地级',realmReq:9,baseDmg:40,desc:'无形剑气从指尖射出',effect:'multi_hit_6',svgAnim:'metal'},
  {id:'wj_finger_03',name:'弹指神通',category:'指法',element:'wind',dmgType:'physical_pierce',grade:'玄级',realmReq:7,baseDmg:22,desc:'弹指间射出暗器或气劲',svgAnim:'wind'},
  {id:'wj_finger_04',name:'拈花指',category:'指法',element:'light',dmgType:'soul',grade:'玄级',realmReq:8,baseDmg:18,desc:'佛门指法，以柔克刚',effect:'stun_15',svgAnim:'light'},
  {id:'wj_finger_05',name:'九阴白骨爪',category:'爪法',element:'dark',dmgType:'physical_sharp',grade:'玄级',realmReq:7,baseDmg:28,desc:'阴毒爪法，撕裂血肉',effect:'bleed_15_poison_5',svgAnim:'dark'},
  {id:'wj_finger_06',name:'飞蝗石',category:'暗器',element:'earth',dmgType:'physical_blunt',grade:'凡级',realmReq:1,baseDmg:8,desc:'投掷石子攻击',svgAnim:'earth'},
  {id:'wj_finger_07',name:'暴雨梨花针',category:'暗器',element:'poison',dmgType:'physical_pierce',grade:'玄级',realmReq:6,baseDmg:22,desc:'机括发射毒针，密如暴雨',effect:'poison_10_multi_5',svgAnim:'poison'},
  {id:'wj_finger_08',name:'含沙射影',category:'暗器',element:'poison',dmgType:'mixed',grade:'黄级',realmReq:4,baseDmg:15,desc:'暗中偷袭的毒砂',effect:'blind_15',svgAnim:'poison'},
  {id:'wj_finger_09',name:'漫天花雨',category:'暗器',element:'none',dmgType:'physical_pierce',grade:'黄级',realmReq:5,baseDmg:18,desc:'同时发射大量暗器',effect:'multi_hit_5',svgAnim:'physical_pierce'},
  {id:'wj_finger_10',name:'擒龙功',category:'指法',element:'wind',dmgType:'physical_blunt',grade:'玄级',realmReq:8,baseDmg:20,desc:'隔空擒拿敌人',effect:'pull',svgAnim:'wind'},

  {id:'wj_kick_01',name:'无影脚',category:'腿法',element:'wind',dmgType:'physical_blunt',grade:'黄级',realmReq:3,baseDmg:16,desc:'快如无影的连环踢',effect:'multi_hit_2',svgAnim:'wind'},
  {id:'wj_kick_02',name:'旋风腿',category:'腿法',element:'wind',dmgType:'physical_blunt',grade:'黄级',realmReq:4,baseDmg:20,desc:'旋转踢击，横扫一片',effect:'aoe',svgAnim:'wind'},
  {id:'wj_kick_03',name:'鸳鸯连环腿',category:'腿法',element:'none',dmgType:'physical_blunt',grade:'玄级',realmReq:6,baseDmg:24,desc:'双腿交替连踢',effect:'multi_hit_3',svgAnim:'physical_blunt'},
  {id:'wj_kick_04',name:'谭腿',category:'腿法',element:'earth',dmgType:'physical_blunt',grade:'黄级',realmReq:5,baseDmg:22,desc:'刚猛腿法，力沉如山',svgAnim:'earth'},
  {id:'wj_kick_05',name:'凌波微步',category:'身法',element:'wind',dmgType:'none',grade:'玄级',realmReq:6,baseDmg:0,desc:'绝顶轻功，闪避极高',effect:'dodge_up_30',svgAnim:'wind'},
  {id:'wj_kick_06',name:'梯云纵',category:'身法',element:'wind',dmgType:'none',grade:'黄级',realmReq:4,baseDmg:0,desc:'纵跃轻功，可空中变向',effect:'dodge_up_15',svgAnim:'wind'},
  {id:'wj_kick_07',name:'神行百变',category:'身法',element:'wind',dmgType:'none',grade:'玄级',realmReq:7,baseDmg:0,desc:'百变步法，难以捉摸',effect:'dodge_up_25_speed_15',svgAnim:'wind'},
  {id:'wj_kick_08',name:'金雁功',category:'身法',element:'none',dmgType:'none',grade:'黄级',realmReq:3,baseDmg:0,desc:'轻灵身法，提升闪避',effect:'dodge_up_10',svgAnim:'wind'},

  {id:'wj_inner_01',name:'金钟罩',category:'内功',element:'earth',dmgType:'none',grade:'黄级',realmReq:3,baseDmg:0,desc:'护体硬功，减伤防御',effect:'def_up_20',svgAnim:'earth'},
  {id:'wj_inner_02',name:'铁布衫',category:'内功',element:'metal',dmgType:'none',grade:'凡级',realmReq:1,baseDmg:0,desc:'外功硬功，皮如铁铸',effect:'def_up_10',svgAnim:'metal'},
  {id:'wj_inner_03',name:'十三太保横练',category:'内功',element:'earth',dmgType:'none',grade:'玄级',realmReq:6,baseDmg:0,desc:'极致护体，刀枪不入',effect:'def_up_35',svgAnim:'earth'},
  {id:'wj_inner_04',name:'九阳神功',category:'内功',element:'fire',dmgType:'none',grade:'地级',realmReq:9,baseDmg:0,desc:'至阳内功，百毒不侵',effect:'def_up_25_regen_20',svgAnim:'fire'},
  {id:'wj_inner_05',name:'易筋经',category:'内功',element:'light',dmgType:'none',grade:'地级',realmReq:9,baseDmg:0,desc:'少林至高内功，脱胎换骨',effect:'all_stat_up_15',svgAnim:'light'},
  {id:'wj_inner_06',name:'紫霞神功',category:'内功',element:'light',dmgType:'none',grade:'玄级',realmReq:7,baseDmg:0,desc:'华山派内功，护体紫气',effect:'shield_15',svgAnim:'light'},
  {id:'wj_inner_07',name:'蛤蟆功',category:'内功',element:'poison',dmgType:'mixed',grade:'玄级',realmReq:8,baseDmg:25,desc:'蓄力吐息，毒劲伤人',effect:'poison_10_stun_10',svgAnim:'poison'},
  {id:'wj_inner_08',name:'先天功',category:'内功',element:'chaos',dmgType:'none',grade:'玄级',realmReq:7,baseDmg:0,desc:'全真教至高内功',effect:'exp_up_10',svgAnim:'chaos'},
  {id:'wj_inner_09',name:'吸星大法',category:'内功',element:'dark',dmgType:'soul',grade:'地级',realmReq:9,baseDmg:15,desc:'吸取敌人内力为己用',effect:'mp_steal_20',svgAnim:'dark'},
  {id:'wj_inner_10',name:'混元功',category:'内功',element:'chaos',dmgType:'none',grade:'黄级',realmReq:5,baseDmg:0,desc:'调和阴阳的基础内功',effect:'regen_10',svgAnim:'chaos'},

  {id:'wj_special_01',name:'判官笔',category:'奇门',element:'metal',dmgType:'physical_pierce',grade:'黄级',realmReq:3,baseDmg:14,desc:'点穴利器，专攻穴位',effect:'stun_10',svgAnim:'metal'},
  {id:'wj_special_02',name:'铁扇功',category:'奇门',element:'wind',dmgType:'physical_sharp',grade:'黄级',realmReq:4,baseDmg:16,desc:'铁扇开合间伤人',effect:'bleed_5',svgAnim:'wind'},
  {id:'wj_special_03',name:'拂尘功',category:'奇门',element:'light',dmgType:'physical_blunt',grade:'玄级',realmReq:6,baseDmg:20,desc:'道家拂尘，以柔克刚',effect:'disarm',svgAnim:'light'},
  {id:'wj_special_04',name:'九节鞭',category:'奇门',element:'metal',dmgType:'physical_blunt',grade:'黄级',realmReq:5,baseDmg:22,desc:'软兵器，变化多端',effect:'multi_hit_2',svgAnim:'metal'},
  {id:'wj_special_05',name:'峨眉刺',category:'奇门',element:'water',dmgType:'physical_pierce',grade:'黄级',realmReq:4,baseDmg:18,desc:'双手短刺，近身暗杀',effect:'crit_up_15',svgAnim:'water'},
  {id:'wj_special_06',name:'子母鸳鸯钺',category:'奇门',element:'metal',dmgType:'physical_sharp',grade:'玄级',realmReq:7,baseDmg:26,desc:'双钺合璧，攻防一体',effect:'multi_hit_2_def_up_10',svgAnim:'metal'},
  {id:'wj_special_07',name:'三节棍',category:'奇门',element:'none',dmgType:'physical_blunt',grade:'黄级',realmReq:5,baseDmg:20,desc:'可长可短，变化自如',svgAnim:'physical_blunt'},
  {id:'wj_special_08',name:'吴钩',category:'奇门',element:'metal',dmgType:'physical_sharp',grade:'黄级',realmReq:4,baseDmg:17,desc:'钩形兵器，勾锁敌刃',effect:'disarm',svgAnim:'metal'},

  {id:'wj_poison_01',name:'五毒功',category:'毒功',element:'poison',dmgType:'mixed',grade:'黄级',realmReq:4,baseDmg:14,desc:'五毒教入门毒功',effect:'poison_8',svgAnim:'poison'},
  {id:'wj_poison_02',name:'化功大法',category:'毒功',element:'poison',dmgType:'soul',grade:'玄级',realmReq:7,baseDmg:18,desc:'化去敌人功力',effect:'atk_down_20',svgAnim:'poison'},
  {id:'wj_poison_03',name:'千蛛万毒手',category:'毒功',element:'poison',dmgType:'mixed',grade:'玄级',realmReq:6,baseDmg:22,desc:'以毒蛛淬体，毒掌伤人',effect:'poison_15',svgAnim:'poison'},
  {id:'wj_poison_04',name:'腐尸毒',category:'毒功',element:'poison',dmgType:'mixed',grade:'黄级',realmReq:5,baseDmg:16,desc:'剧毒掌力，触之即腐',effect:'poison_10_corrosion',svgAnim:'poison'},
  {id:'wj_poison_05',name:'冰魄银针',category:'毒功',element:'ice',dmgType:'mixed',grade:'玄级',realmReq:7,baseDmg:20,desc:'冰属性毒针，寒毒入体',effect:'freeze_10_poison_8',svgAnim:'ice'},
  {id:'wj_poison_06',name:'断肠草',category:'毒功',element:'poison',dmgType:'mixed',grade:'凡级',realmReq:2,baseDmg:10,desc:'剧毒之物，腐蚀脏腑',effect:'poison_5',svgAnim:'poison'},
  {id:'wj_poison_07',name:'七虫七花膏',category:'毒功',element:'poison',dmgType:'mixed',grade:'黄级',realmReq:4,baseDmg:12,desc:'七种毒虫七种毒花合制',effect:'poison_12',svgAnim:'poison'},
  {id:'wj_poison_08',name:'碧磷毒功',category:'毒功',element:'poison',dmgType:'mixed',grade:'玄级',realmReq:8,baseDmg:24,desc:'碧绿毒焰，焚身蚀骨',effect:'poison_15_burn_5',svgAnim:'poison'},

  {id:'wj_sound_01',name:'狮子吼',category:'声波',element:'none',dmgType:'soul',grade:'玄级',realmReq:6,baseDmg:20,desc:'佛门怒吼，震慑心神',effect:'stun_20',svgAnim:'physical_blunt'},
  {id:'wj_sound_02',name:'碧海潮生曲',category:'声波',element:'water',dmgType:'soul',grade:'玄级',realmReq:7,baseDmg:18,desc:'以箫声惑敌，扰乱心神',effect:'confuse_20',svgAnim:'water'},
  {id:'wj_sound_03',name:'笑傲江湖曲',category:'声波',element:'wind',dmgType:'soul',grade:'地级',realmReq:9,baseDmg:28,desc:'琴箫合奏，音波伤人',effect:'aoe_confuse_15',svgAnim:'wind'},
  {id:'wj_sound_04',name:'梵音佛唱',category:'声波',element:'light',dmgType:'soul',grade:'黄级',realmReq:5,baseDmg:14,desc:'佛门梵音，净化邪念',effect:'purify_stun_10',svgAnim:'light'},
];

export const COMBAT_TECHNIQUES_XIANFA: any = [
  {id:'xf_001',name:'仙剑·斩天',category:'仙剑',element:'light',dmgType:'true_damage',grade:'天级',realmReq:30,baseDmg:200,desc:'仙人一剑可斩天',effect:'true_crit_25',svgAnim:'light'},
  {id:'xf_002',name:'太上忘情',category:'仙道',element:'void',dmgType:'soul',grade:'仙级',realmReq:34,baseDmg:280,desc:'忘情一击，直击大道本源',effect:'soul_shatter',svgAnim:'void'},
  {id:'xf_003',name:'九霄雷帝诀',category:'仙雷',element:'lightning',dmgType:'elemental',grade:'仙级',realmReq:35,baseDmg:300,desc:'仙帝级雷法，天劫之力',effect:'paralyze_40_true_aoe',svgAnim:'lightning'},
  {id:'xf_004',name:'焚天仙焰',category:'仙火',element:'fire',dmgType:'elemental',grade:'仙级',realmReq:33,baseDmg:260,desc:'仙火焚天，万物不存',effect:'burn_40_true',svgAnim:'fire'},
  {id:'xf_005',name:'永冻冰棺',category:'仙冰',element:'ice',dmgType:'elemental',grade:'仙级',realmReq:32,baseDmg:240,desc:'永恒冻结，时空停滞',effect:'freeze_40_time_stop',svgAnim:'ice'},

  {id:'xf_006',name:'仙帝一指',category:'仙道',element:'void',dmgType:'true_damage',grade:'仙级',realmReq:35,baseDmg:310,desc:'仙帝一指，虚空崩塌',effect:'void_annihilate_true',svgAnim:'void'},
  {id:'xf_007',name:'天道之剑',category:'仙剑',element:'light',dmgType:'true_damage',grade:'仙级',realmReq:36,baseDmg:330,desc:'以天道为剑，斩断一切',effect:'true_crit_40',svgAnim:'light'},
  {id:'xf_008',name:'混沌仙焰',category:'仙火',element:'chaos',dmgType:'elemental',grade:'仙级',realmReq:34,baseDmg:280,desc:'混沌仙焰焚烧大道',effect:'burn_45_chaos',svgAnim:'chaos'},
  {id:'xf_009',name:'时间长河·逆流',category:'仙道',element:'void',dmgType:'true_damage',grade:'仙级',realmReq:37,baseDmg:340,desc:'逆转时间长河',effect:'time_reverse_heal_50',svgAnim:'void'},
  {id:'xf_010',name:'仙魔一体',category:'仙魔',element:'chaos',dmgType:'true_damage',grade:'仙级',realmReq:36,baseDmg:320,desc:'仙魔之力合一',effect:'dual_hit_lifesteal_30',svgAnim:'chaos'},
  {id:'xf_011',name:'大道之音',category:'仙道',element:'light',dmgType:'soul',grade:'仙级',realmReq:35,baseDmg:290,desc:'大道之音直击神魂',effect:'soul_dmg_40_confuse_30',svgAnim:'light'},
  {id:'xf_012',name:'万仙大阵',category:'仙道',element:'chaos',dmgType:'elemental',grade:'仙级',realmReq:38,baseDmg:360,desc:'万仙之力凝聚的大阵',effect:'aoe_true_seal',svgAnim:'chaos'},
  {id:'xf_013',name:'仙风道骨',category:'仙风',element:'wind',dmgType:'elemental',grade:'仙级',realmReq:33,baseDmg:260,desc:'仙风化为万千刀刃',effect:'aoe_multi_10_bleed_20',svgAnim:'wind'},
  {id:'xf_014',name:'仙土·天地翻覆',category:'仙土',element:'earth',dmgType:'true_damage',grade:'仙级',realmReq:34,baseDmg:275,desc:'翻天覆地之威',effect:'aoe_stun_35_crush',svgAnim:'earth'},
  {id:'xf_015',name:'仙雷·天劫',category:'仙雷',element:'lightning',dmgType:'elemental',grade:'仙级',realmReq:36,baseDmg:320,desc:'仙人级天劫雷罚',effect:'paralyze_45_true_aoe',svgAnim:'lightning'},
  {id:'xf_016',name:'仙毒·万蛊噬仙',category:'仙毒',element:'poison',dmgType:'mixed',grade:'仙级',realmReq:33,baseDmg:250,desc:'万种毒蛊噬咬仙体',effect:'poison_40_true',svgAnim:'poison'},
  {id:'xf_017',name:'仙血·血河倒灌',category:'仙血',element:'blood',dmgType:'mixed',grade:'仙级',realmReq:34,baseDmg:270,desc:'血河倒灌吞噬万物',effect:'lifesteal_45_aoe',svgAnim:'blood'},
  {id:'xf_018',name:'仙木·生命古树',category:'仙木',element:'wood',dmgType:'elemental',grade:'仙级',realmReq:33,baseDmg:200,desc:'召唤生命古树恢复',effect:'heal_80_regen_40',svgAnim:'wood'},
  {id:'xf_019',name:'仙金·不朽神兵',category:'仙金',element:'metal',dmgType:'physical_sharp',grade:'仙级',realmReq:35,baseDmg:300,desc:'不朽神兵斩破虚空',effect:'penetrate_70_crit_35',svgAnim:'metal'},
  {id:'xf_020',name:'仙暗·永夜降临',category:'仙暗',element:'dark',dmgType:'soul',grade:'仙级',realmReq:37,baseDmg:335,desc:'永恒之夜降临',effect:'soul_dmg_45_blind_40',svgAnim:'dark'},
  {id:'xf_021',name:'仙光·普照万物',category:'仙光',element:'light',dmgType:'elemental',grade:'仙级',realmReq:37,baseDmg:340,desc:'仙光普照净化一切',effect:'purify_true_heal_30',svgAnim:'light'},
  {id:'xf_022',name:'仙冰·永恒寒冬',category:'仙冰',element:'ice',dmgType:'elemental',grade:'仙级',realmReq:35,baseDmg:290,desc:'永恒寒冬冻结时间',effect:'freeze_50_time_stop',svgAnim:'ice'},
  {id:'xf_023',name:'仙水·天河倒悬',category:'仙水',element:'water',dmgType:'elemental',grade:'仙级',realmReq:34,baseDmg:270,desc:'天河倒悬冲刷万物',effect:'aoe_freeze_30_crush',svgAnim:'water'},
  {id:'xf_024',name:'仙风·九天罡风',category:'仙风',element:'wind',dmgType:'elemental',grade:'仙级',realmReq:35,baseDmg:295,desc:'九天罡风切割一切',effect:'aoe_multi_12',svgAnim:'wind'},
  {id:'xf_025',name:'仙拳·碎星',category:'仙拳',element:'chaos',dmgType:'true_damage',grade:'仙级',realmReq:38,baseDmg:355,desc:'一拳碎星',effect:'true_crit_50',svgAnim:'chaos'},
  {id:'xf_026',name:'仙剑·一剑开天',category:'仙剑',element:'light',dmgType:'true_damage',grade:'仙级',realmReq:39,baseDmg:380,desc:'一剑开天辟地',effect:'open_heaven',svgAnim:'light'},
  {id:'xf_027',name:'仙阵·天罗地网',category:'仙阵',element:'chaos',dmgType:'elemental',grade:'仙级',realmReq:38,baseDmg:350,desc:'天罗地网困杀大阵',effect:'aoe_seal_40',svgAnim:'chaos'},
  {id:'xf_028',name:'仙魂·三魂七魄斩',category:'仙魂',element:'dark',dmgType:'soul',grade:'仙级',realmReq:39,baseDmg:365,desc:'斩灭三魂七魄',effect:'soul_annihilate',svgAnim:'dark'},
  {id:'xf_029',name:'仙法·言出法随',category:'仙道',element:'chaos',dmgType:'true_damage',grade:'仙级',realmReq:39,baseDmg:370,desc:'言出即法随',effect:'law_enforcement',svgAnim:'chaos'},
  {id:'xf_030',name:'仙劫·大道反噬',category:'仙道',element:'void',dmgType:'true_damage',grade:'仙级',realmReq:39,baseDmg:390,desc:'引动大道反噬',effect:'dao_backlash',svgAnim:'void'},
];

export const TECH_PROFICIENCY_LEVELS: any = [
  { level: 0, name: '入门', icon: '📖', color: '#888', desc: '初步掌握技法要领', dmgMult: 1.0, unlockLaw: false },
  { level: 1, name: '熟练', icon: '📘', color: '#6a9fd8', desc: '技法运用自如', dmgMult: 1.08, unlockLaw: false },
  { level: 2, name: '小成', icon: '📗', color: '#4a8a4a', desc: '技法略有小成', dmgMult: 1.18, unlockLaw: false },
  { level: 3, name: '大成', icon: '📙', color: '#c8a84e', desc: '技法大成，威力倍增', dmgMult: 1.3, unlockLaw: false },
  { level: 4, name: '入微', icon: '🔍', color: '#8e6aaf', desc: '技法入微，洞察秋毫', dmgMult: 1.45, unlockLaw: false },
  { level: 5, name: '登堂入室', icon: '🏛️', color: '#c67a3c', desc: '技法登堂入室，得其精髓', dmgMult: 1.65, unlockLaw: false },
  { level: 6, name: '圆满', icon: '⭕', color: '#d4a843', desc: '技法圆满，炉火纯青', dmgMult: 1.9, unlockLaw: false },
  { level: 7, name: '返璞归真', icon: '☯️', color: '#7a9a7a', desc: '返璞归真，大道至简', dmgMult: 2.2, unlockLaw: false },
  { level: 8, name: '入道', icon: '💫', color: '#b8860b', desc: '技法入道，触及本源', dmgMult: 2.6, unlockLaw: true },
  { level: 9, name: '三千大道', icon: '🌌', color: '#9b59b6', desc: '技近乎道，大道共鸣', dmgMult: 3.0, unlockLaw: true },
];

export const TECH_PROFICIENCY_THRESHOLDS: any = [1, 5, 15, 30, 60, 100, 200, 500, 1000, 2500];

export const TECHNIQUE_TIER_REALM_MAP: any = {
  wuji:      { name:'武技', minRealm:0, maxRealm:9, desc:'凡人至筑基期使用', icon:'👊', color:'#c9a96e' },
  lingji:    { name:'灵技', minRealm:10, maxRealm:19, desc:'金丹至元婴期使用', icon:'🌀', color:'#5bc0de' },
  shentong:  { name:'神通', minRealm:20, maxRealm:29, desc:'化神至大乘期使用', icon:'⚡', color:'#f1c40f' },
  xianfa:    { name:'仙法', minRealm:30, maxRealm:39, desc:'渡劫至仙人使用', icon:'☀️', color:'#e67e22' },
  daofa:     { name:'道法', minRealm:40, maxRealm:49, desc:'仙人之上使用', icon:'💫', color:'#9b59b6' },
  benyuan:   { name:'本源道法', minRealm:50, maxRealm:99, desc:'最高境界使用', icon:'🌌', color:'#8e44ad' },
};

export const TECH_DMG_CATEGORIES: any = {
  physical_blunt:  { name: '击打伤', icon: '👊', desc: '钝器击打，震荡内伤', penetration: 0.05 },
  physical_sharp:  { name: '切割伤', icon: '🗡️', desc: '利器切割，出血为主', penetration: 0.15 },
  physical_pierce: { name: '穿刺伤', icon: '🔱', desc: '深入穿刺，穿透护甲', penetration: 0.45 },
  elemental:       { name: '元素伤', icon: '🌀', desc: '元素攻击，附加效果', penetration: 0.20 },
  mixed:           { name: '混合伤', icon: '💥', desc: '物理+元素混合', penetration: 0.25 },
  soul:            { name: '灵魂伤', icon: '👻', desc: '直接攻击神魂', penetration: 0.80 },
  true_damage:     { name: '真实伤', icon: '💎', desc: '无视一切防御', penetration: 1.00 },
};

export const TECH_ELEMENT_TO_LAW: any = {
  '火': 'fire', '水': 'water', '木': 'wood', '金': 'metal', '土': 'earth',
  '雷': 'thunder', '风': 'wind', '冰': 'ice', '光': 'light', '暗': 'dark',
  '混沌': 'chaos', '空间': 'space', '时间': 'time', '生命': 'life',
  '死亡': 'death', '力': 'force', '剑': 'sword', '无': null,
};

export const TECHNIQUE_SVG_ANIMATIONS: any = {
  physical_blunt: { particles: 'impact', color: '#c9a96e', shape: 'circle', trail: false },
  physical_sharp: { particles: 'slash', color: '#c0c0c0', shape: 'line', trail: true },
  physical_pierce: { particles: 'pierce', color: '#95a5a6', shape: 'point', trail: true },
  fire: { particles: 'flame', color: '#e74c3c', shape: 'wave', trail: true },
  water: { particles: 'splash', color: '#3498db', shape: 'wave', trail: false },
  earth: { particles: 'crumble', color: '#d4a574', shape: 'circle', trail: false },
  metal: { particles: 'spark', color: '#c0c0c0', shape: 'line', trail: true },
  wood: { particles: 'vine', color: '#27ae60', shape: 'wave', trail: true },
  lightning: { particles: 'bolt', color: '#f1c40f', shape: 'zigzag', trail: true },
  wind: { particles: 'blade', color: '#1abc9c', shape: 'line', trail: true },
  ice: { particles: 'crystal', color: '#74b9ff', shape: 'circle', trail: false },
  dark: { particles: 'void', color: '#2c3e50', shape: 'circle', trail: false },
  light: { particles: 'beam', color: '#f39c12', shape: 'line', trail: true },
  poison: { particles: 'drip', color: '#2ecc71', shape: 'wave', trail: false },
  void: { particles: 'rift', color: '#8e44ad', shape: 'circle', trail: true },
  chaos: { particles: 'random', color: '#e67e22', shape: 'random', trail: true },
  blood: { particles: 'splash', color: '#c0392b', shape: 'wave', trail: true },
};
